### ISSUE TITLE
Due to large number of Freerdp CLI options can't a YAML config file make life easier 

### ISSUE THREAD

**Issue by bmullan** [FreeRDP/FreeRDP#10230]
It would seem to me that configs for a FreeRDP Session would be easier to understand & use if the config was in YAML format.

For instance an Audio section, a Video section, a printer section etc

**Comment by akallabeth** [comment]
not really, that just sounds like one more parser and dependency to take care of.

* there is the `rdp` file format for most stuff (we need compatibility with `ms` tools so that can not be stripped) - most likely what you are thinking of
* there is the command line which we need to keep anyway
* we already are required to link `json` parsers for full protocol support so if done then this format would be the one that does not introduce another dependency

and the best advice is just not to use too many options, most of them are for very specialized cases where you need to know what you do and the default (auto detection) is what you want. (we are talking about a `RDP` client, which does not control what will be used, it can just announce certain features and hope the server picks them up)

(note: we are trying to find a way to split the options in commonly useful ones, like `/sound`, `/microphone` and advanced options like `/sound:sys:alsa`)

**Comment by bmullan** [comment]
@akallabeth 
Thanks for the details !
