### ISSUE TITLE
FreeRDP_DisableWallpaper has no effect in 3.8.0

### ISSUE THREAD

**Issue by blapalp** [FreeRDP/FreeRDP#10752]
Hi, this worked in 3.5.1, but the background is shown again in 3.8.0 despite the flag set (same server).

**Comment by akallabeth** [comment]
@blapalp sounds like the setting is not properly handled by the server (this can happen due to some conditional settings)

I´ve done a test client side with the following patch applied to both versions:
```
diff --git a/libfreerdp/core/info.c b/libfreerdp/core/info.c
index a51563aa8..ff92f2975 100644
--- a/libfreerdp/core/info.c
+++ b/libfreerdp/core/info.c
@@ -555,6 +555,7 @@ static BOOL rdp_write_extended_info_packet(rdpRdp* rdp, wStream* s)
        /* clientSessionId (4 bytes), should be set to 0 */
        Stream_Write_UINT32(s, settings->ClientSessionId);
        freerdp_performance_flags_make(settings);
+       WLog_INFO(TAG, "xxxxxxxxx: 0x%08" PRIx32, settings->PerformanceFlags);
        Stream_Write_UINT32(s, settings->PerformanceFlags); /* performanceFlags (4 bytes) */
        Stream_Write_UINT16(s, cbAutoReconnectCookie);      /* cbAutoReconnectCookie (2 bytes) */
        ```
        
* `3.5.1` as well as `3.8.0` send ` [INFO][com.freerdp.core.info] - [rdp_write_extended_info_packet]: xxxxxxxxx: 0x00000180` with `+wallpaper` (or without that)
* `3.5.1` as well as `3.8.0` send `[INFO][com.freerdp.core.info] - [rdp_write_extended_info_packet]: xxxxxxxxx: 0x00000181` with `-wallpaper`

[\[MS-RDPBCGR\]](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/00f1da4a-ee9c-421a-852f-c19f92343d73) can help you here:
1. if `CONNECTION_TYPE_AUTODETECT` is used the server `MIGHT` ignore the `performance flags` (this is the default option for `FreeRDP`)
1. [\[MS-RDPBCGR\] Extended Info Packet](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/05ada9e4-a468-494b-8694-eb806a0ecc89) details the `performance flags`

**Comment by akallabeth** [comment]
note: the setting might also be ignored if you connect to an existing session, so best log out all sessions before testing this to have reproducible results
