### ISSUE TITLE
Test_GetComputerName failure

### ISSUE THREAD

**Issue by ondrejholy** [FreeRDP/FreeRDP#10961]
**Describe the bug**
I've just enabled tests for the Fedora package (https://src.fedoraproject.org/rpms/freerdp/c/914fc6bb015115e59638abc906d43af660748676?branch=rawhide) and the build failed in koji due to the `Test_GetComputerName` failure  (https://kojipkgs.fedoraproject.org//work/tasks/1216/126761216/build.log). It can be easily reproduced with `master` using the following steps.

**To Reproduce**
1. `$ hostname asdasdasasdasdasadasdasdasdasdasdasd`
2.  `$ ./build/Testing/TestSysInfo TestGetComputerName`
3. It fails with: `Test_GetComputerName: (5) GetComputerNameA returned wrong size 37 (expected something in the range from 2 to 32)`

**Expected behavior**
Test suceeded.

**Environment (please complete the following information):**
Fedora 41 (x86_64)

**Additional context**
I'm unsure whether this is a bug in the `GetComputerNameA` implementation that doesn't take `MAX_COMPUTERNAME_LENGTH` into account, or the test has wrong expectations about the returned value. The `gethostname` function doesn't guarantee that the returned value will be less than equal 32...

**Comment by akallabeth** [comment]
@hardening related to this, do you remember why in `ntlm_get_target_computer_name` `GetComputerNameExA(ComputerNameNetBIOS` is called ignoring the type requested completely?
also in `x509_get_default_name` we should fall back to `ComputerNamePhysicalDnsHostname` instead of `ComputerNamePhysicalNetBIOS` right?
