### ISSUE TITLE
Keyboard issues with Transformer

### ISSUE THREAD

**Issue by dhc01002** [FreeRDP/FreeRDP#1253]
I am having issues with the arrow keys, the home and end keys and the tab key on my transformer tablet with the keyboard attached.  They key strokes do not seem to register.

Let me know if you need any more information.

**Comment by bmiklautz** [comment]
I'm closing this issue because it has been inactive for a while.
Possibly we've already fixed the issue or it is not reproducible (anymore).

If you still encounter the reported problem with our [latest stable release](https://github.com/FreeRDP/FreeRDP/releases) please re-open this issue with updated information or create a [new bug report](https://github.com/FreeRDP/FreeRDP/issues/new?template=bug_report.md).

Thank you!
