### ISSUE TITLE
Clipboard feature does not work

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#1410]
Hi I'm on Ubuntu 13.04 and run "This is FreeRDP version 1.1.0-beta1 (git 1.1.0-beta+2013071101-226-g558d4)" compiled from git.
I connect to my Windows 7 Pro 64bit "  6 xfreerdp +smart-sizing +compression +clipboard -sec-nla /network:lan /workarea /v:192.168.1.2 /jpeg"

I can't copy and paste from Ubuntu to Windows.
It works using rdesktop.

**Comment by akallabeth** [comment]
Clipboard working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef

**Comment by pikkmees** [comment]
Looks like this problem is back:

Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

xfreerdp /version
<<<This is FreeRDP version 2.0.0-dev5 (8b22ea748)

Launching like:
xfreerdp /u:*** /d:**** /v:*****:3389 /g:******* +clipboard /size:1900x1024 /bpp:24
Working between host and client well until some day ago did update on xfreerdp(and more)

**Comment by pikkmees** [comment]
Srry, found it was already fixed:

@mfleisz
mfleisz Merge pull request #5480 from akallabeth/xfreerdp_clip_fix

Fix broken clipboard after file copy

Latest commit 5e672d4 22 hours ago

**Comment by mailinglists35** [comment]
>but to be sure kill the rdpclip process and restart.

thanks, this worked for me, win10 and 2.0.0~git2020031

I've never had to kill rdpclip, neither with windows client, nor remmina nor rdesktop.
