### ISSUE TITLE
smart-sizing feature does not work

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#1411]
Hi I'm on Ubuntu 13.04 and run "This is FreeRDP version 1.1.0-beta1 (git 1.1.0-beta+2013071101-226-g558d4)" compiled from git.
I connect to my Windows 7 Pro 64bit "  6 xfreerdp +smart-sizing +compression +clipboard -sec-nla /network:lan /workarea /v:192.168.1.2 /jpeg"

I can't resize the window

**Comment by molecular** [comment]
I got excited pre-maturely, it seems.

I compiled the newest master and checked out the /smart-sizing feature.

It doesn't do what I hoped for. I was hoping for the following behaviour: If the local X11 window size changes (I use a framing window manager and moving an 'app' between frames results in a window size change), the remote desktop geometry is changed to that new size.

This is obviously not what /smart-sizing feature does. I think it should be called /smart-scaling, because it just scales the offscreen bitmap to the local size (and quite badly, too).

Thank you guys for your great work anyway.

Is there any chance I can get the feature I'm looking for? As a layman I'm thinking it shouldn't be too hard if the rdp protocol allows for changing the remote screen size.

**Comment by eworm-de** [comment]
Same for me. ;) That current situation is really disappointing, at least given the name of the feature.

IMHO just scaling is everything but smart.

**Comment by nfedera** [comment]
guys, cut the crap please ...
Regarding the name please complain complain at Microsoft. FreeRDP always tries to use the same terms. And no, AFAIK the rdp protocol does not support client-initiated resizing during an activated session. Further reading: 
https://technet.microsoft.com/en-us/library/ff393693%28v=ws.10%29.aspx
http://blogs.msdn.com/b/rds/archive/2008/08/07/smart-sizing-the-ts-client.aspx
http://superuser.com/questions/98494/windows-rdp-possible-to-resize-resolution-on-the-fly

@molecular please elaborate regarding your comment "and quite badly too" ?
xfreerdp uses XRenderComposite with the bilinear filter to scale the content. Usually this gives the best balance between image quality and performance. If it looks totally bad then maybe your graphics driver is to blame. But I'd need to see a screen shot in order to judge.

**Comment by eworm-de** [comment]
Sorry, I did not want to be harsh.

I was pretty sure that latest versions of remote desktop protocal allows real resize (changing resolution). But I was wrong... So probably freerdp does the best it can do.

Still a bad idea from Microsoft to name it "smart". I do not think there is anything smart with scaling remote sessions.

**Comment by hardening** [comment]
@eworm-de I think the channel that support changing resolution (disp) is only supported in xfreerdp 1.2. Anyway I have no idea how you can use it in the client.

**Comment by nfedera** [comment]
@hardening cool! never took a closer look at the MS-RDPEDISP channel:
https://msdn.microsoft.com/en-us/library/dn366738.aspx
Obviously MS only implemented it in Windows 8.1 / Server 2012 R2.
But it seems that using that channel the client can trigger a session resize (resulting in a deactivation-reactivation sequence if egfx is not used).
There is already an implementation in FreeRDP: https://github.com/FreeRDP/FreeRDP/tree/master/channels/disp/
However, no integration in any client yet.

**Comment by molecular** [comment]
I will post screenshots of the scaling on my machine. Looks like nearest neighbor to me. Of course it might be my graphics card setup.

It's regrettable that the protocol doesn't support re-sizing.

To be honest: I probably wouldn't mind a reconnect on size-change (most probably will, though).

Another thing that would greatly easy the pain I have with my framing wm (notion) would be if xfreerdp would assume the window size upon startup if no geometry parameters are given. I'm not sure how exactly initial sizing of windows works. Probably X11 lets the app choose a window size initially and only later, when it's being bound to the frame, is it changed to fit the frame.

I understand the problems I have are specific to using a framing window manager and I didn't mean to come across negatively. I was just disappointed because I thought my long-running problem had been finally solved and it wasn't.

To say something positive: I discovered that clipboard syncing actually seems to work reliably now (not sure since when), so I'm switching back from rdesktop (where the clipboard sync only works in conjunction with certain other local apps (works with scite, for example), not with others (doesn't work with sublime text, for example) and sometimes not at all (even made a habit of hitting Ctrl-C on the remote machine 3 times to make it more reliable)) to xfreefdp.

Keep up the great work!
