### ISSUE TITLE
Problem with some menu in some apps running in RemoteApp mode

### ISSUE THREAD

**Issue by thunderamur** [FreeRDP/FreeRDP#1528]
1. DESCRIPTION

Have some critical problem in RemoteApp mode. Don't work menu in some apps.
On YouTube you can see this problem in extremly popular commercial app for business in Russia - 1C. And problem in other commercial app  - Megatec Master Agent.

http://youtu.be/cJAxr1edxR8

I understand that you would have some difficulties to find those apps and made video with Microsoft Office Word 2003

http://youtu.be/pqmVvfAheqk
1. COMMAND LINE

Remote Desktop (OK):
xfreerdp -u USER --ignore-certificate --plugin cliprdr IP

RemoteApp (Problem):
xfreerdp -u USER --ignore-certificate --plugin cliprdr --app --plugin rail --data "||WINWORD" -- IP
1. Windows Server 2008 R2
2. This is FreeRDP version 1.0.1
3. Ubuntu 13.04 (and 12.04) amd64

**Comment by tristan-k** [comment]
I'm having this issue on Ubuntu 14.04 LTS. It's extremly annoying. Any way to fix that.

**Comment by hardening** [comment]
@tristan-k, @tachylatus Some recent changes have been done on last master regarding remoteApp, could you give a try ? Thank you

**Comment by tristan-k** [comment]
Can you push the changes to the Remmina PPA for Ubuntu?

**Comment by hardening** [comment]
@tristan-k Remmina PPA for Ubuntu: no. binary deb: you may find nightly builds here: https://github.com/FreeRDP/FreeRDP/wiki/Prebuilds

**Comment by tristan-k** [comment]
Please see my comment here: https://github.com/FreeRDP/FreeRDP/issues/2662#issuecomment-107016969

**Comment by ripkooo** [comment]
Problem is actual (in 2018.04.18 nightly and all previous versions)
is actual for the winworld, is actual for 1C Enterprise (any menu).
when I in any way call the context menu, if at the moment of its appearance I will not hover menu with the mouse, it disappears, while I see in the taskbar how the "unnamed window" appears and disappears. and if I will to point the mouse at it, the menu does not disappear, the new "unnamed window" appears in the taskbar, the menu items work, and when trying to enter the submenu, the situation repeats.

**Comment by supertin** [comment]
I think I'm getting this in "Reckon Accounts 2018"... When I start entering a supplier in the "enter bills" section of Reckon, there's supposed to be a dropdown list of existing suppliers that match text being entered. Instead, I get an area that is transparent and shows the terminal behind the remoteapp window. Not an app killer because the first match is pre-filled in the still-visible text box anyway.

This transparent section makes me think this is either a bug in Windows or a poor design in Reckon causing the dropdown to be seen as a different program, and therefore not rendered as part of the remote app... Reckon appears to not use a standard Windows theme, so it could well be an entirely custom dropdown box.

I'm connected to a 2008R2 server and running the current Debian supplied version of FreeRDP (2.0.0-rc2 apparently).

**Comment by akallabeth** [comment]
@supertin Could you try if it works when adding `/rfx /gfx:avc444` to your command line? There are some rare operations in legacy RDP that do not work 100% reliable, so maybe with modern drawing these are fixed for you.

**Comment by supertin** [comment]
That does solve the Reckon dropdown problem... Which is fantastic because it was the one concern I had for switching the entire business to Linux in the next few months :smile:
Thanks for the tip.

**Comment by VasylHozda** [comment]
xfreerdp
the menu does not open when connected to remoteapp

This is FreeRDP version 2.0.0-dev

https://youtu.be/M2_FFe9MxUk
