### ISSUE TITLE
async-input appears to be on by default.  Help says off by default

### ISSUE THREAD

**Issue by takenit2far** [FreeRDP/FreeRDP#2338]
In master, turning async-input off with '-' fixes not being able to control the screen once a video is playing in a web browser. 

Help states its off by default,  but it would be appear that it is turned on.

**Comment by bmiklautz** [comment]
@takenit2far you are using xfreerdp?

**Comment by bmiklautz** [comment]
Just checked and it's off by default.

**Comment by takenit2far** [comment]
I know I heard that,   but if I turn it on it makes no difference..  Turning it off improves the situation dramatically.   Could anything else be flipping its behaviour?

**Comment by realjiangms** [comment]
@takenit2far 
I think you are using xfreerdp with an rdp server which supports rfx codec. 
I got same issue when I use a thin client (with ATOM 1.6GHZ cpu) and connect to an rdp server with Intel E31220 3.1Ghz, the server side is the shadow server in FreeRDP. I set the fps to 30 to get more stable output.

The default is sync-input, the issue exists and it only response to my keyboard/mouse every 5 seconds. According to the X11 client code, the reason should be poor CPU speed in thin client side. It decode rfx message much more slower than server side encoding the rfx message. Therefore when it returns from decoding current frame, the PDU of next frame has already arrive, and the upper layer function(transport_check_fds() in libfreerdp/core/transport.c) will continue processing next PDU since it exists. Then we run into an endless loop and busy displaying the video. In very rare case we could get a respite (such as, the full black frame in video) and transport_check_fds returns, then the keyboard/mouse event get a chance to be handled.

I would expect that the +async-input, but no, it makes it worse. I added printf in event handler subroutine and it shows that once I press a key, the event is get handled and sent to the server. And in network monitor, when I move mouse and press keyboard, it shows about 100KB/s data is transferred to the server. So I think it works in client side but there may be some race condition and we may violate some rules in protocol, so the server side never handle the event PDU in this case.

@takenit2far 
Finally I come up with a workaround. In libfreerdp/core/transport.c, comment out the following:
```
        /**
         * Loop through and read all available PDUs.  Since multiple
         * PDUs can exist, it's important to deliver them all before
         * returning.  Otherwise we run the risk of having a thread
         * wait for a socket to get signaled that data is available
         * (which may never happen).
         */
        for (;;)
       {
                /**
                 * Note: transport_read_pdu tries to read one PDU from
                 * the transport layer.
                 * The ReceiveBuffer might have a position > 0 in case of a non blocking
                 * transport. If transport_read_pdu returns 0 the pdu couldn't be read at
                 * this point.
                 * Note that transport->ReceiveBuffer is replaced after each iteration
                 * of this loop with a fresh stream instance from a pool.
                 */
                if ((status = transport_read_pdu(transport, transport->ReceiveBuffer)) <= 0)
                {
                        return status;
                }
```
=================> comment out the 'for (;;)' and make it always return when finish with a pdu

I'm still investigating on server side that why the async-input doesn't not work.

@bmiklautz @takenit2far 
The ' for (;;)' seems added by Mike McDonald at 2014-03-10, do you know whether it's necessary? If we can remove it we will no longer have this issue in X11 client

**Comment by realjiangms** [comment]
Finally I found why async-input doesn't work.
We do create a thread to peek input event from X, but in async input mode, the event is not sent to server immediately. Instead, we generate a message into FREERDP_INPUT_MESSAGE_QUEUE.
But in xfreerdp, the FREERDP_INPUT_MESSAGE_QUEUE is processed in main client thread! So we still suffer the side effect from the endless loop in transport_check_fds.

Another issue #2429 also mentioned it and it seems +async-transport and +async-update helps.

After checking the corresponding code in windows client and Mac client (wfreerdp and mfreerdp), I think the behavior of async-input need to be changed. In wfreerdp and mfreerdp, the async input thread process the FREERDP_INPUT_MESSAGE_QUEUE, so the async input thread in xfreerdp should do so, too.

**Comment by duhow** [comment]
As the original title says, this is currently fixed, so can be closed?
