### ISSUE TITLE
Mouse pointer incorrect transformed

### ISSUE THREAD

**Issue by antonstv** [FreeRDP/FreeRDP#2369]
FreeRDP version 1.2.1-dev (git ed3d952)
VMWare VSphre Client in console guest OS Windows XP cursor disappears (invisible), in putty mouse cursor black and white to be, in Danware Netop Guest cursor disappears. In version 1.0.2 is correctly, but /multimon not available.

В Vsphere client и Netop курсор исчезает, в putty курсор становится черным на черном фоне, а должен быть белым.  В версии 1.0.2 корректно, но нет опции нескольких мониторов.

**Comment by bmiklautz** [comment]
@antonstv can you give us more details what client you use or how you connect?

**Comment by antonstv** [comment]
Ubuntu 10.04 LTS, GPU Intel® Ivybridge Desktop 
FreeRDP 1.2.1 get from https://github.com/FreeRDP/FreeRDP.git
compile: cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON
connect string(xterminal):  xfreerdp /multimon /u:user033@office.local /v:192.168.103.33

Connecting RDP to Win7 Enterprise.

**Comment by antonstv** [comment]
whith /bpp:32 in VSphre Client and Netop cursor is correctly. In putty coursor is black. In version 1.0.2 cursor dotted white.

**Comment by nfedera** [comment]
I'm pretty sure you're experiencing the issue that inverted color cursors aren't supported under X11.
See https://msdn.microsoft.com/en-us/library/windows/hardware/ff556143%28v=vs.85%29.aspx

In case of putty this is what it should look like:
![image](https://cloud.githubusercontent.com/assets/670606/6102950/7dd8a232-b03e-11e4-8296-c162ad4a41bc.png)

If the AND mask and XOR mask values are both 1 we set that pixel to black since inversion is not supported under X11 (AFAIK).

See https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/codec/color.c#L1505
```
else if (andPixel && xorPixel)
    *pDstPixel++ = 0xFF000000; /* inverted (set as black) */
```

The most simple soulution would be setting white and black alternately, something like this:
```
int bw=0;
...
else if (andPixel && xorPixel)
    *pDstPixel++ = bw++ % 2 ? 0xFF000000 : 0xFFFFFFFF;
```

**Comment by antonstv** [comment]
Thanks

**Comment by bmiklautz** [comment]
@nfedera is that something we could possibly add upstream?

**Comment by nfedera** [comment]
Reopened the issue as this is definitely a common problem that deserves being solved.
@bmiklautz sure, but hopefully someone has an idea for a more aesthetically pleasing workaround.

**Comment by pffff** [comment]
still not solved?

**Comment by bmiklautz** [comment]
@pffff pull requests are very welcome..

**Comment by akallabeth** [comment]
Since a solution exists with @2868 closing.
