### ISSUE TITLE
clipboard and files

### ISSUE THREAD

**Issue by azhel12** [FreeRDP/FreeRDP#2424]
Clipboard works, but I can not copy any file via it. Copy/paste text works fine. This options works in standart windows rdp-client(mstsc). So I think that it must work in FreeRDP too.

**Comment by bmiklautz** [comment]
@azhel12 the clipboard channel doesn't support file copies yet.
If you want to copy from your remote machine to the local machine you need to use the drive channel.

**Comment by azhel12** [comment]
I thought the same, but I tried to do it in Windows default client and it works here! Also I have written small program on C# with using MSTSCLib. My program (it is about 10 code lines) supports copy files via clipboard.

**Comment by meanbunny** [comment]
This would be an awesome feature!

**Comment by ilammy** [comment]
Well, I have an implementation of file clipping in X11 client somewhere. IIRC, it worked pretty well for me. (Except for some issues with large files.) Because reasons it did not make it to public, but I can try find it and rebase onto current master.

**Comment by azhel12** [comment]
I think you are speak russian then write russian. If I was wrong, write me
about it, pls. Доброго времени суток. Пишу по поводу Вашего ответа "Well, I
have an implementation of file clipping in X11 client somewhere. IIRC, it
worked pretty well for me. (Except for some issues with large files.)
Because reasons it did not make it to public, but I can try find it and
rebase onto current master."
Посмотрел Ваш аккаунт на github и сделал вывод, что Вы носитель русского
языка, поэтому пишу по-русски) Делаю небольшой проект, где бы классно было
использовать FreeRDP, но нужна передача файлов через буфер обмена. Я так
понял, что у Вас это реализовано. Где я могу это найти? В вашем форке и
ветке master?

2015-04-01 15:09 GMT+03:00 ilammy <notifications@github.com>:

**Comment by bmiklautz** [comment]
@azhel12 please not that the official language for FreeRDPs issues is English. Thank you.

**Comment by ilammy** [comment]
@azhel12, yes, I know Russian, but others here maybe do not, so I am writing in English. Drop me an email if you are more comfortable with Russian.

The file clipping implementation is not anywhere on Github, it was somewhere on my hard drive about  a year ago. I will look for it and keep you (and others) posted.

**Comment by bmiklautz** [comment]
@ilammy thanks!

**Comment by azhel12** [comment]
Sorry, I wanted to write only to ilammy. But made a mistake( Ok, my email: azhel12reg@gmail.com

**Comment by ilammy** [comment]
Duh, it seems that I could not save the code. So this will take some time to get file clipping running on Linux...

Also, I have talked it over with azhel12, and it seems that file clipping is not working in Windows client. (He had Windows client in mind, not X11.) However, #1732 added the support for it and that code has not gone anywhere. @zhangzl2013?

**Comment by antenore** [comment]
@ilammy Any news about this? It would be amazing to have file clipping with X11 client!

Unlucky I don't know (yet) where to start to try to hack this. 

Is this https://github.com/ilammy/FreeRDP/commits/x11-cliprdr/files/remote-to-local code still valid/tested?

Thanks!

**Comment by lemonmojo** [comment]
Is there any news about file transfers via clipboard redirection on OS X (or even Linux)?
It looks like the wfreerdp client supports it but the code doesn't look portable.

**Comment by meanbunny** [comment]
This would be awesome, sometimes when dealing with large file structures
doing drive passthrough takes forever to just copy one file

Thanks,
Steven Combs
Meanbunny LLC, Owner
423-799-0365

**Comment by ilammy** [comment]
Linking the pokemons: #3532

**Comment by akallabeth** [comment]
I've dug a bit into that. There is no real portable way to do this thing.
Copying from local to remote is easy (just open a file/directory and send headers / data)
The other way is the tricky part. OS X and Linux (or anything I've encountered except windows) expect a URI to copy from. So something fuse based or similar would be the way to go (If I'm not missing something)
Provide a local view of the files available for copying and modify the URI pasted to clipboard to the corresponding path.
Whenever something is pasted the data is requested from the server.
Caching may be something to consider (what if the data is pasted twice?)

So now we're just looking for someone with time to implement that ;)
any volunteers?

**Comment by ilammy** [comment]
What about temporary directories? Pre-download the files before announcing local clipboard content, then just tell that we can paste from `file:///tmp/xfreerdp.<pid>/cliprdr.<seq>`. As I recall, there is also a possibility to use redirected disk drives as a temporary storage.

However, this approach has a downside in comparison with the FUSE one: double copying causes visible delays for large files. So for the sake of user experience it would be better to avoid that. But it may be an option if libfuse is not available.

**Comment by akallabeth** [comment]
@ilammy yes that is an option. although you need some code to clean up afterwards and of course the space needed on the temporary drives.

**Comment by ilammy** [comment]
Actually, I was wandering around some old commits of mine which aspired to implement the thing, and I just recalled another pitfall about file clipping. Copying from local to remote may not be as easy as just open(2), lseek(2), read(2), close(2).

Gnome-based Linux desktop environments use `x-special/gnome-copied-files` format which is a list of URLs. These URLs actually come from the GVFS file system and they are not always `file:///local/directory/with/a/file`. For example, if a user opens an FTP connection in a file manager like Nautilus then it is totally possible for them to copy-paste remote files which will have URLs like `ftp://server/remote/file` stored in the clipboard data. These ones can be pasted to local desktop, etc. It would make sense to have them available in the RDP session as well, but we will have to use GFile and other stuff from GIO lib to handle them. (Or just ignore anything that is not a local `file://`)

No idea what KDE does, they may do something entirely different. The same goes for macOS. So it may be hard to implement the whole thing in platform-agnostic manner, having something like `wClipboard` in common code to handle the magic. So I'd just left most of this as client implementation details.

Another note on GVFS is for the remote-to-local transfers. GVFS does not provide any API so it is not possible to write a plugin of a sort in order to provide some magic URLs `xfreerdp://cliprdr/pid/...` to local applications in order to seamlessly integrate remote clipboard as if it were a remote-mapped resource like an FTP server. I guess we will have to have our own FUSE module and provide `file:///run/freerdp/pid/cliprdr/...` URLs which are mapped onto remote clipboard content.

**Comment by ilammy** [comment]
And some more thoughts.

Using libgio and GFile may also be not as straightforward as it seems for those remote `ftp://` files. Cliprdr protocol allows arbitrary seeking in the file which may not be available for the remote files. While servers do ask for the contents in a sequential manner (IIRC), we should be ready for the unexpected.

Finally, caching, prefetching, and other leaking abstractions may be an issue for large transfers. Like, imagine the server which asks for file contents in 4K increments and for each request we create a new GFile instance, seek it, read a block, close the file (while in background GVFS opens a new FTP connection for each our request, fetches the whole file from scratch into a temporary directory, seeks it, reads it, provides us the data, and then removes the file because it can). However, I believe that we can ignore it and say that the users should use disk drive redirection for large files if speed matters for them. After all, cliprdr does not support files larger that 2 GB.

**Comment by ilammy** [comment]
![onemorething](https://cloud.githubusercontent.com/assets/1256587/23192416/f1a43a3e-f8ab-11e6-8cbb-b913aa344f0f.png)
And one more thing!

There's that wacky case of transferring files between two remote sessions. We can be either ~~dumb~~ straighforward and treat the other session just like any other application (care should be taken), or we can try being smart and organize some IPC to proxy clipboard file requests between two remote servers.

**Comment by akallabeth** [comment]
@ilammy GVFS should be no problem, they provide a local mount point for every type of URI

**Comment by ilammy** [comment]
@akallabeth But we will still have to use some stuff from libgio to get that, right?

I'm wondering whether this would be okay to link FreeRDP against these libraries. As I understand it, there should be no problem with requiring libfuse, glib, libgio, etc. at build time, and linking the resulting binaries against them in order to support file clipping. We only need to ensure that these dependencies are kept optional and `#if !(defined(HAVE_FUSE) && defined(HAVE_LIBGIO))` then FreeRDP should just say to the server that it does not support file clipping and ignore any file formats in local clipboard, while having everything else working as before.

**Comment by ilammy** [comment]
Okay, my conscience was very persistent, so I have started working on the thing. See ilammy/FreeRDP#4 for tracking progress. (That PR is my notes, I will make a proper one to FreeRDP when something is ready.)

/cc @akallabeth

**Comment by akallabeth** [comment]
@ilammy Nice! Dependencies of channels may vary from the core (best keep them optional). If you have some issues I'm in IRC (and also give feedback during daytime, CET that is)

**Comment by dbanet** [comment]
@ilammy double-copying can be prevented when using temporary files if a named pipe file is being used instead. I would also suggest to not hard-wire this essential function to GNOME, as named or unnamed pipes or plain file writes to a specified directory may suffice for some users.

Defining a simple API that (1) does one and only one thing very well, (2) is easy to use, (3) prevents double-copying, and (4) is largely respected and supported across many different platforms seems the Unix way to do it (whether one likes it or not).

All in all, I preach creating a named pipe in a local directory (specified by an option and defaulted to `/var/run/xfreerdp/$pid/`?) for each file copied on a remote machine. Named pipes are part of POSIX standard. Then the intricacies of various blown-out-of-proportion desktop environments a user wishes to or not to use may indeed be left as client implementation details.

**Comment by ilammy** [comment]
@dbanet I suppose using pipes can cause problems.

* One thing is that we would restrict the applications in what they can do with the pasted files. For example, it will not be possible for multiple applications to simultaneously read the pasted file.

* Another issue is that FreeRDP will have to keep an open file descriptor for each and every pasted file, and there are limits on the number of open file descriptors for a process.

On the other hand, GNOME actually does _not_ help with this in any way as well, so I did not intend to use anything from it for pasted remote files. For this I plan to use FUSE which hosts files in the local filesystem. Then applications can use the usual POSIX API to access them as if they are local.

I plan to add ability to use GNOME-specific things for transferring local files to the remote system. This mainly concerns the use case when the user has a remote server mapped to their local filesystem (say, they have connected to the FTP server and can select and copy files in their file manager). For some stupid reason, when we request the list of files on the clipboard we do not get local filesystem mappings. Instead we are provided with remote URIs (like `ftp://example.com/file`) of the files which we can't pass to open(2), even when gvfs-fuse and stuff is installed and configured and there are mappings in `/run/user/$UID/gvfs`.

However, that thing should be totally optional. I intend to implement support for `text/uri-list` format with only `file://` URI scheme supported via POSIX API as the lowest common denominator for Linux systems. This should allow copying local files from the file managers. The users which need to paste remote-mapped files from their Nautilus/Konqueror/Whatever will have to use desktop-specific subsystems, or somehow teach their software to provide local filesystem paths.

**Comment by akallabeth** [comment]
Closing this as #4703 is tracking the remaining missing part and the client to server copy part has been merged.
