### ISSUE TITLE
BIO synchronization issue causing unpected connection drops intermittently

### ISSUE THREAD

**Issue by llyzs** [FreeRDP/FreeRDP#2497]
Currently the BIO read/write methods could be accessed from multiple threads (main thread and virtual channels) simultaneously without protection. Particularly, there is no protection between the SSL_read and SSL_get_error call (and so SSL_write and SSL_get_error), but I am not sure there will be other cases. We have observed cases from time to time, in which SSL_read returned from normal blocking state (SSL_ERROR_WANT_READ etc), but then the following SSL_get_error call returns a critical unknown error SSL_ERROR_SYSCALL instead, because the internal SSL and BIO state were changed by another thread which was trying to write something else.

**Comment by llyzs** [comment]
As a minimum solution, I think bio_rdp_tls_read/write must be protected as a whole, but I am not sure if this is actually a more serious design problem. Any input?

**Comment by awakecoding** [comment]
@llyzs read and write should be doable in parallel, but parallel read/read or write/write should not be doable. The original OpenSSL BIOs were unfortunately not compatible with full duplex, as the read and write operations both started with resetting the BIO retry flag. This meant that in certain cases, the read operation would get to test the retry flag as false as in parallel the write operation had just reset it. Our BIOs reset the retry flag if and only if we detect that the transport is truly down to avoid this issue. If you observe parallel write/write and read/read calls, the problem is not in the BIO but in the code calling the BIO. read and write are not reentrant, and I think don't we want/can make them reentrant. It doesn't make sense anyway to allow our application to make multiple read or write calls in parallel, only one read and one write call in parallel at the same time (full duplex).

**Comment by llyzs** [comment]
@awakecoding thanks for the hint, I think I found the real problem on our side. Closing this one for now.
