### ISSUE TITLE
Problem starting xfreerdp-server

### ISSUE THREAD

**Issue by believeyourself** [FreeRDP/FreeRDP#2528]
I was trying to compile freerdp as a server by building 
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_SERVER=ON.
But I am able to start up the server with command xfreerdp-server. Its showing command not found.
I have also followed two links. http://askubuntu.com/questions/475776/can-freerdp-be-used-as-server 
and https://github.com/FreeRDP/FreeRDP/issues/1060 . But neither works.

**Comment by hardening** [comment]
@believeyourself  please inquiry a little before posting issues. If it's a "command not found" error it's because the binary (pick one or more item):

* hasn't been compiled;
* hasn't been installed;
* is installed in a location that is not not in your PATH;

Anyway the issue tracker is not the place for so basic help requests, you have IRC or the mailing list for this.
