### ISSUE TITLE
Error connecting to RemoteApp through Remote Desktop Gateway (0x2000D)

### ISSUE THREAD

**Issue by gojensen** [FreeRDP/FreeRDP#2542]
I've been trying to get this thing working since I found a site (http://ifconfig.dk/freerdp/) claiming that FreeRDP is the ONLY solution to connect to our RemoteApps through our RDGateway.

Servers: Windows Server 2012R2, 1 broker, 1 gateway/RDWeb and 2 session hosts
Client: running Xfreerdp 1.2.1-dev (git n/a) on Ubuntu Desktop 14.04.1 LTS (kernel 3.16.0-34) xfreerdp binary downloaded from the nightly Ubuntu repo

The same solution works just fine on Windows computer (using browser or the Microsoft Remote Desktop app) and Mac/iOS (using the Microsoft Remote Desktop App) so I know the server side things are working just fine. We're also using fully signed USERTrust certificates so we don't have any certificate errors...

I'm trying to launch through the downloaded RDP files supplied by RDWeb service but a manual connect gives the same error message...

$ bin/xfreerdp Downloads/cpub-WinSCP-ITapps-CmsRdsh.rdp /u:user@company.com /g:remote.company.com /p:password
[10:24:43:190] [3493:3494] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[10:24:43:190] [3493:3494] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[10:24:43:190] [3493:3494] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[10:24:43:190] [3493:3494] [INFO][com.freerdp.client.common.cmdline] - loading channel rail
[10:24:43:406] [3493:3494] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[10:24:43:411] [3493:3494] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1

or...

$ bin/xfreerdp /v:BROKER.company.com.no /u:user@company.com /p:password /g:remote.company.com /gu:user@company.com /gp:password /app:'||WinSCP'
[10:39:42:043] [3668:3669] [INFO][com.freerdp.client.common.cmdline] - loading channel rail
[10:39:47:367] [3668:3669] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[10:39:47:381] [3668:3669] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1

I also tried to download the master from git and compile that, but it's the same version and gives the same errors.

**Comment by dbungert** [comment]
I see that you're running from git, but I literally just pushed a fix that looks relevant, so make sure you're running 4e1194c53bb18868a642ba0b655e1e6950537e84 or later.

**Comment by jurikolo** [comment]
Unfortunately this fix doesn't help me, just checkout latest master. See log:
[someuser@t2001542]$ /usr/local/bin/xfreerdp /v:someserver /cert-ignore /u:someuser
Password: 
[18:38:29:525] [10942:10943] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[18:38:29:526] [10942:10943] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1
[someuser@t2001542]$ /usr/local/bin/xfreerdp /version
This is FreeRDP version 1.2.2-dev (git bfccc06)

**Comment by gojensen** [comment]
Hi dbungert - I'll be trying this shortly, I've been having some strange issues reinstalling Ubuntu on my VM test machine that I need to sort out before I can try this again on a clean system.

**Comment by dlfu** [comment]
Hi all, is there a fix for this? im running into this issue also on master version 1.2.2-dev

**Comment by LGLumi** [comment]
Both master v. 1.2.2 and the latest (git?) 1.2.4 are not working for me in the same way. 1.2.0 works but it is not quite stable through GW. (freezing from time to time)

**Comment by a-a** [comment]
can confirm that 87c5377 still has this bug

[mak0@rikka ~]$ xfreerdp /g:gw.example.net /cert-ignore /v:mypc /d:example.net /u:user /p:lolpassword
[13:37:49:288] [5841:5842] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[13:37:49:288] [5841:5842] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1
[mak0@rikka ~]$ xfreerdp --version
This is FreeRDP version 1.2.4-dev (git 87c5377)

**Comment by LGLumi** [comment]
Hello,

what distribution of linux do you have?
Why aren’t you using also /gd: /gu: /p: or is it the same? Try it with it aswell… Btw, how do you specify username?

Henry

Von: a-a [mailto:notifications@github.com]
Gesendet: Donnerstag, 02. Juli 2015 13:40
An: FreeRDP/FreeRDP
Cc: Mican Jindrich
Betreff: Re: [FreeRDP] Error connecting to RemoteApp through Remote Desktop Gateway (0x2000D) (#2542)


can confirm that 87c5377<https://github.com/FreeRDP/FreeRDP/commit/87c5377f422cc31824d83962289539a19cc9072c> still has this bug

[mak0@rikka ~]$ xfreerdp /g:gw.example.net /cert-ignore /v:mypc /d:example.net /u:user /p:lolpassword
[13:37:49:288] [5841:5842] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[13:37:49:288] [5841:5842] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1
[mak0@rikka ~]$ xfreerdp --version
This is FreeRDP version 1.2.4-dev (git 87c5377<https://github.com/FreeRDP/FreeRDP/commit/87c5377f422cc31824d83962289539a19cc9072c>)

**Comment by a-a** [comment]
I've just had some success with with 87c5377 by explicitly telling it /gt:rpc - during this time, the RD gateway manager on server 2012r2 I'm connected through shows me as connected with RPC-HTTP listed under the transport column.

Using /gt:auto, /gt:http or completely omitting the /gt (I believe /auto is the default in this case?) causes the errors, but for me, /gt:rpc seems to work.
I am not great at Git but I will try later when I am not meant to be working, to download an older code and see if this behaviour is the same on 1.2.0, as I recall /gt:auto worked well for me previously.

LGLumi, I am using Arch Linux, installed from only two days ago. As far as I'm aware /gd: and /gu: are recycled from /u: and /p: when you connect via a gateway and don't otherwise specify what credentials to use.

**Comment by LGLumi** [comment]
Ah, forgot about that… yeah, /gt:rpc does help aswell… Kinda missed that you didn’t have it there.

Yep, /gd /gu should work in that way, I thought it is better to try out even that option.

But /gt:rpc should be the right fix for W2k12.

Von: a-a [mailto:notifications@github.com]
Gesendet: Donnerstag, 02. Juli 2015 14:05
An: FreeRDP/FreeRDP
Cc: Mican Jindrich
Betreff: Re: [FreeRDP] Error connecting to RemoteApp through Remote Desktop Gateway (0x2000D) (#2542)


I've just had some success with with 87c5377<https://github.com/FreeRDP/FreeRDP/commit/87c5377f422cc31824d83962289539a19cc9072c> by explicitly telling it /gt:rpc - during this time, the RD gateway manager on server 2012r2 I'm connected through shows me as connected with RPC-HTTP listed under the transport column.

Using /gt:auto, /gt:http or completely omitting the /gt (I believe /auto is the default in this case?) causes the errors, but for me, /gt:rpc seems to work.
I am not great at Git but I will try later when I am not meant to be working, to download an older code and see if this behaviour is the same on 1.2.0, as I recall /gt:auto worked well for me previously.

LGLumi, I am using Arch Linux, installed from only two days ago. As far as I'm aware /gd: and /gu: are recycled from /u: and /p: when you connect via a gateway and don't otherwise specify what credentials to use.

**Comment by MarcusMoeller** [comment]
I still see this error 0x2000D sometimes, no matter if  /gt:rpc is set or not.

I can try to connect using the same connection string for a few times  one after another and sometimes I got:

[13:33:01:850] [26660:26661] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[13:33:01:850] [26660:26661] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1

and sometimes it works.

**Comment by i92guboj** [comment]
Same problem here. I tried latest git and I was already using /gt:rpc, that helped with some other servers, but not with the one in Azure.

**Comment by fcharlier** [comment]
Encountered this issue too, using `/gt:rpc` seems to work fine for now

**Comment by fulcop** [comment]
Same problem (with or without /gt:rp) for one user with xfreerdp compile yesterday (version 1.2.4-dev git dfa2980)
I don't have the pb with my account on his computer (Debian 7) (to connect to a Windows 2012 R2 Standard)

**Comment by fulcop** [comment]
I solve my problem by adding users/groups in the Windows 2012 group "remote desktop"

**Comment by akallabeth** [comment]
Closing this issue as resolved (`/gt:rpc`)
Reopen or create a new issue if it should really be detected by `/gt:auto`
