### ISSUE TITLE
Compiler flags conflict due to ARM_FP_API option

### ISSUE THREAD

**Issue by floppym** [FreeRDP/FreeRDP#2586]
A user reported the following build failure on Gentoo Linux.

https://bugs.gentoo.org/show_bug.cgi?id=547246

```
ld: error: libfreerdp.so.1.2.1 uses VFP register arguments, CMakeFiles/freerdp.dir/codec/rfx_neon.c.o does not
```

This seems to be the result of some source files being built with `-mfloat-abi=softfp`, and others with `-mfloat-abi=hard`. It looks like this strange behavior was introduced in response to #980.

It seems to be a problem that will occur whenever CFLAGS contains `-mfloat-abi=hard` and ARM_FP_ABI is unspecified, causing it to default to softfp. It doesn't really make sense to me to have cmake override CFLAGS from the environment.

I see a couple of solutions here:

1. Remove the cmake logic for ARM_FP_ABI and adds -mfloat-abi to COMPILER_FLAGS. I'm really not sure why that resolved #980 in the first place. It seems like that issue was a result of CFLAGS being set incorrectly in the build environment, or possibly CFLAGS not being respected in that old version of the code.

2. Add some option to make the above mentioned behavior optional.

I can certainly submit a pull request if some some decision can be made on a suitable solution.

**Comment by bmiklautz** [comment]
@floppym the response to #980 was PR #987 which basically just made the ABI configureable - instead of having it hardcoded to softfp. If you run cmake with the define ARM_FP_ABI set to the float-abi type of your system it should work without a problem.
Anyway the solution was just a work around and needs a better fix. I think we should go for 1. and completely get rid of ARM_FP_ABI since the float-abi used is something the build environment/configuration should specify. In the meanwhile it should be sufficient to remove all occurrences of ARM_FP_ABI including the configuration option.  But I don't have only an Android build environment for testing..

If you can provide a PR this would be great.
