### ISSUE TITLE
Graphical update issue

### ISSUE THREAD

**Issue by bsagal** [FreeRDP/FreeRDP#2618]
The remote screen is not updating properly

I have tested using master (f219d341f1f88159cf67578390390a554a4b4083).
The server runs 2008R2

![image](https://cloud.githubusercontent.com/assets/846911/7629438/2a82e2a0-fa35-11e4-94ea-f887c15c8510.png)

**Comment by hardening** [comment]
@bsagal what's the bug ? the background should be white instead of blue ?

**Comment by bsagal** [comment]
The background should be white, what is showing in the background is the login screen that was shown before the window

**Comment by bsagal** [comment]
correct screen

![image](https://cloud.githubusercontent.com/assets/846911/7630232/bacba5b6-fa3c-11e4-9b92-f82a7154320d.png)

**Comment by nfedera** [comment]
@bsagal please post the command line you're using and what happens if you add /gdi:sw ?

**Comment by bsagal** [comment]
with master (f219d34) i get a seg fault.

when I changed to 1.2.1_pre20150326 it seams to help.

**Comment by nfedera** [comment]
@bsagal I've fixed the /gdi:sw segfault issue in pr #2620. It should get merged into master soon.
Please try again and report ...
1. Your complete xfreerdp command line which causes the graphical issue
2. If you're running your 2008R2 server in administration or remote desktop mode
3. If adding /gdi:sw fixes the issue

**Comment by bsagal** [comment]
1) xfreerdp /v:SERVER
2) administration
3) yes

**Comment by nfedera** [comment]
@bsagal thx, do you see the issue only in MS SQL Server Management Studio or also in some other applications ?

**Comment by bsagal** [comment]
I have only noticed it with  MS SQL Server Management Studio, but that is also my main usage on the server

**Comment by nfedera** [comment]
I've installed SQL Server 2014 Express including SQL Server Management Studio on a 2008R2.
I can reproduce/confirm the issue. For future reference:
- open SQL Server Management Studio 
- open the Activity Monitor
- select the Processes view
- close all other applications/windows so that SQL Server Management Studio is the first/only window directly "above" the windows desktop
- maximize SQL Server Management Studio window
- disconnect the rdp session
- reconnect without specifying a password and use window's logon ui
- after logon the logon/welcome desktop background will be visible in the background of the SQL Server Management Studio Activity Monitor's process view.

Additional info:
- only xfreerdp (mac and linux) seems to be affected 
- /gdi:sw "fixes" the issue

**Comment by nfedera** [comment]
Disabling the polygonsc/polygoncb caps also  "fixes" the issue. I guess the problem might be the x11 implementation of the polygonsc order.

**Comment by hardening** [comment]
@bsagal could you give a try to @nfedera 's patch ? Thank you.

**Comment by nfedera** [comment]
Update: the problem is fixed on master. The actual issue was the x11 client's calculation of the damage region caused by polygon orders.
@bsagal please test current master and close and/or comment if it works for you.

**Comment by bsagal** [comment]
seems to work in master, thank you
