### ISSUE TITLE
Getting RAIL_EXEC_E_FAIL error when trying to connect to remote app on Windows Server 2012

### ISSUE THREAD

**Issue by ahorn42** [FreeRDP/FreeRDP#2712]
Hi, 

I try to connect to a remote app on a Windows Server 2012 R2 from a Kubuntu 14.04 LTS with the following command (I am using freerdp 1.0.2)

```
xfreerdp --ignore-certificate -u Administrator -p Admin111 --app --plugin rail.so --data 'wordpad.exe:%HOMEDRIVE%\Program Files\Windows NT\Accessories:' -- -x 0x80 -a 32 winapphost.lan
```

The command is basically created by the programm winconn, but I executed it manually. The connection fails with the following ouput:

```
loading plugin rail.so
connected to winapphost.lan:3389
RAIL exec error: execResult=RAIL_EXEC_E_FAIL NtError=0x2
```

I run a similar setup with Windows Server 2008 R2 and on this setup it works with the exact same command without any problems. To be more precise, I upgraded the 2008 virtual machine to 2012. I also have snapshots to switch between 2008 and 2012. The result, with 2008 it works with 2012 it doesn't.

With the Windows RDPClient on a other windows machine I am able to connect to the remote app on 2012 and 2008.

Any ideas how to fix this bug or what I might have missed to do after the upgrade? If you need more information please let me know!

best regards

**Comment by hardening** [comment]
I'd bet that the application is not allowed to be run. There's a registry key listing allowed commands... (google is your friend)

**Comment by guitar1** [comment]
Hmm - but I am able to use the remote app with the windows rdp client on a windows machine. Shouldn't it also have some troubles, if a registry key is missing?

**Comment by pvgoran** [comment]
@guitar1 Did you resolve your issue? I have a few suggestions that may help investigating it.

**Comment by guitar1** [comment]
@pvgoran no, till now my workarround is a downgrade to Server 2008 R2

**Comment by hardening** [comment]
@guitar1 we have done some changes around rails in last master, would you give a try ? I'm quite sure it will not change the observed behaviour, but just in case...

**Comment by pvgoran** [comment]
1. How exactly do you connect via the Windows RDP client? Can't it be that it's set up to run the registered remote application via its alias instead of the file name?

2. Could you try with the git version using the new syntax and the full application file name? Like this:
`xfreerdp /cert-ignore /u:Administrator /p:Admin111 /app:'%HOMEDRIVE%\Program Files\Windows NT\Accessories\wordpad.exe' /v:winapphost.lan`
(No idea what `-- -x 0x80 -a 32` means in the original command line, is it something important?)
Also, you may want to replace `%HOMEDRIVE%` with `%SYSTEMDRIVE%`, just in case these variables are set in different ways by Windows.

The point is, I *was* able to run remote applications in Windows Server 2012 R2, using the git version of freerdp (and also some earlier version from around March). The thing that didn't work for me was passing parameters to applications: it works for 2008 but not for 2012 R2. Maybe your issue is somehow related, because you also pass something other than the application file name (I mean the `%HOMEDRIVE%\Program Files\Windows NT\Accessories` part which is probably the directory that Windows should change to before executing the application).

**Comment by akallabeth** [comment]
This looks like a configuration issue with server .
Closing, reopen if some more details are known pointing to a client issue.
