### ISSUE TITLE
1.2.4. /u: required otherwise replaced by current user - intended?

### ISSUE THREAD

**Issue by LGLumi** [FreeRDP/FreeRDP#2730]
While testing (without success) connection through GWs I have noticed that /u: is now required or replaced by current user which I do not think is good deal. If I have more users that might connect from same machine I come to conclusion that only way to actualy fix it is to set /u:"" but tbh, why this change? If someone wanted fixed user, he used it, but such automatic way does not seem good and then we get to longer lines... 

On the another hand, if I fill /gd: and not /d: would is it working in the way that it then uses for /d: the same, or would it be possible in that way if not mentioned?

Thanks.

**Comment by akallabeth** [comment]
@LGLumi If you would like to enter your credentials afterward, have a look at #2723 which allows skipping all credentials on the command line and requesting them on connect.

**Comment by bmiklautz** [comment]
@LGLumi this change is around quite a while (since December 2014 to be precise). One common use case, for example when administering remote machines, is to simply connect (often without any extra arguments except the host name). In this case it is very practical to have a name set. But besides that when testing it is also very convenient. 

About your complaint: I don't know your exact setup but if you connect with NLA a username is required otherwise a connection won't work. I personally also don't see a real problem if you use the same local shared for multiple users for rdp connections. The only thing happening (without nla) and if the local user matches the remote user is that the user is pre filled or pre selected.
And as you correctly described you can always alter and change this behavior with /u:"" if you don't like this.

As for /gd: and /d:. If you use remote gateway and don't supply /u: or /d: the username, domain name and password of /gd: /gu: /gp are used for /d: /u: /p: respectively.

**Comment by LGLumi** [comment]
I just meant that it is not nessesary, not that it is faulty. If you connect to Windows RDP then you can log afterwards, in that case passive role of ignoring missing username was quite nice. So, I meant it might confuse people that do exactly the same thing. 

For the GW/not GW should it be switched? There might be point when you are authorising by another credentials to GW and you want to log with another to remote desktop - in the case I guess you use blank /u: again instead of non.

Anyway, thanks a lot for your answers. ;)
