### ISSUE TITLE
MAC OSX FreeRDP Server - Segmentation Fault

### ISSUE THREAD

**Issue by meanbunny** [FreeRDP/FreeRDP#2771]
Hey All,

I have downloaded the latest source and compiled from master on osx. I have freerdp-shadow configured to run at login and it runs successfully. I haven't been able to pinpoint the exact issue, but when "sometimes" when I connect and then hover my mouse over the FeeRDP window that gets created I receive the following error on the server side (the osx side). 

    interleaved_compress: width is not a multiple of 4

The window then closes and reports on my client on 

    Segmentation fault      (core dumped)

It happens randomly and I can't really figure out the frequency or the how on why its happening. Currently I am connected and using it just fine. Once it connects successfully and can handle the mouse movement I have 0 issues throughout the remainder of that session. So it must just be something on initial mouse hover or entry.

**Comment by realjiangms** [comment]
This is because in shadow_client_send_bitmap_update(), the code to align nWidth and nHeight is not correct:

    if ((nWidth % 4) != 0)
    {
        nXSrc -= (nWidth % 4);
        nWidth += (nWidth % 4);
    }

    if ((nHeight % 4) != 0)
    {
        nYSrc -= (nHeight % 4);
        nHeight += (nHeight % 4);
    }


If we want nWidth  to be multiple of 4, we need to make it as nWidth += (4-(nWidth % 4)).
But I haven't been able to understand the code completely to fix it, and it looks to me that the nSrcX and nSrcY have chance to be negative according to the code. So I haven't give it a fix.

Currently the rfx encoder in shadow-server is stable. You can try to specify /rfx if you are using clients from FreeRDP. For windows please use rdp in Win7 or later

**Comment by realjiangms** [comment]
Fixed in #2913
