### ISSUE TITLE
/p has to be set when connection through gateway

### ISSUE THREAD

**Issue by LiohMoeller** [FreeRDP/FreeRDP#2773]
When connecting through a gateway, I have to define the /p:"MyPassword" parameter in order to make it work. If I leave it out, I am not prompted for a password.

I guess it has something to do with the fact that /gu /gd and /gp are substituted with the values of /u /d /p when they are not set.

**Comment by LGLumi** [comment]
@MarcusMoeller Well, from my experience only thing that has to be set is /g: /:gd: /gu: /gp: ... ofc, if it is different from RDP credentials. But as I am using it, I do not have /p set, it is actualy only thing... I do keep /u:"" because otherwise it does automaticaly fill with current username and I don't want that. But /p: is definetly not nessesary. 

/gp: password for GW credentials
/p: password for RDP 

I think you know it, I am just writting it to make it obvious.

Actually when I do not fill /u /p /d I am not sure, if it going to /g ... but vice versa it works I think. 
It would not be even nice to be prompted for password before actual RDP connection, I would not like that for sure.

**Comment by MarcusMoeller** [comment]
Why not? What's the advantage of giving a password in plain text as command line parameter?

From my experience, when you do a direct connection you can just leave the /g.. stuff:

xfreerdp /g:mygateway /u:... /d:... /p:"..." /v:server

as it gets substituted. But you cannot ommit /p here. When using a rdp file, from my experience all parameters have to be set:
xfreerdp myfile.rdp  /u:... /d:... /p:"..."  /gu:... /gd:... /gp:"..." /gt:rpc

Also I have to set /gt:rpc with 2012r2 gateway here which does not seem to be necessary in first case.

**Comment by LGLumi** [comment]
@MarcusMoeller I never said that it's an advantage. I am not filling password and it is working as intended.

**Comment by MarcusMoeller** [comment]
So could you please paste an example connection string, I could try?

**Comment by LGLumi** [comment]
xfreerdp /f /sec:rdp /gt:rpc -sec-nla /d:interndomain /gd:gwdomain /v:sessionhost /g:gateway /gu:xxx /gp:xxxxxx /gu:"" 

Of course, you give away GWuser & GW-p/w but that user should have no rights at all other than connecting through GW. Plain text is kind of a problem, if you won't fill its password, it will prompt you for sure while it cannot get through GW. 

/gu:"" is there just for being sure that it won't fill current user in username, so you don't need to delete it on session host when loggin' in.

**Comment by MarcusMoeller** [comment]
So you giving a plain pw on cli but for a different user account which only has access to the gw? We are using the same credentials for gw and rdp access here.

**Comment by LGLumi** [comment]
Yes, it is user which is absolutely stripped off any rights, only right is has is to go through GW, it has completely different password than everything else ofc. And noone even knows (from users) that it exists, so noone even comes to using it. If there would be any log of this user accessing or trying to access anything, it will get blocked instantly. 

Security wise it is only option with FreeRDP how to ensure some kind of security while connecting through GW. You should not use same credentials for GW and user account if you want to say that you are secure. From my own experience I always prefered two authentifications to its security, 

Examples: 
1) GW account credentials get stolen - ofc it depends then about your internal security, if that account does not get blocked for suspicious activity or you simply don't have such a tools. BUT, that user has no immediate access to any files or another resources.
2) You have single account for user to authentificate to GW and it is also user account... If credentials get stolen, you immediately lose date or your data are compromised. 

Counts for whatever that does not come with another level of authentification like certificates. 

It is exactly same reason why administrator accounts should not be at same time their normal-work-accounts (like for mail etc). Because when admin account gets stolen, it is big problem. Think about domain admin getting compromised - your whole company might get in problems.

**Comment by MarcusMoeller** [comment]
Ok, but this still does not explain why /gp cannot be promted instead of giving it as cli argument.

**Comment by LGLumi** [comment]
Well, that is not an answer I can give you. Would be nice to know, ofc it would not be a problem to make script for it. That it always prompts for GW pass and then user has to log on session host aswell. 

Ofc, even FRDP should it, but at least you can train your scripting skills, right? ;-) Just kidding, I guess devs will tell you more than me. I am just trying to help around while thanks to other people I was able to do what I needed, so I feel that is nessesary that I do the same thing.

**Comment by hardening** [comment]
Need to check but I think this could be closed.

**Comment by akallabeth** [comment]
the callbacks have been refactored
