### ISSUE TITLE
Can't use redirected USB devices

### ISSUE THREAD

**Issue by HenryJacques** [FreeRDP/FreeRDP#2832]
Hello,

I am using the latest master from a Ubuntu 14.04 64 bits to connect to a Windows 7 SP1 32bits.
I am redirecting an USB device using the /usb:id,dev command line.
The device is correctly redirected (I had to first enable RemoteFX on the target), the driver is correctly installed and the device appears in the Device Manager.

However, I noticed that the device appears to be connected from a very high USB port number (61 in my case as shown in the screenshot).
If I use a Windows 7 workstation with mstsc as a client, the usb device is also redirected but it appears with a "normal" USB port number (5 or 6).

Like I said the device is correctly redirected and installed, but I can't use it in my application, or at least it doesn't find the device. If I use mstsc it works fine.

Do you think my lead about the USB number being to high is correct? (maybe because my application doesn't enumerate USB devices up to such high numbers?)

Thanks in advance!

![usb](https://cloud.githubusercontent.com/assets/11716929/9255890/7ba283a8-41ec-11e5-84e2-f8660be2484a.jpg)

**Comment by HenryJacques** [comment]
In fact my lead was wrong. I've tested it this morning again. This time, the redirected devices appeared to be connected from the Port number 0006 which is something more regular but the behaviour remains the same: the device is redirected (or "half-redirected" - you'll see later why), the driver is correctly installed and the device appears in the device manager.

I've tested this with several USB devices:
- webcam
- fingerprint sensors
- scanner

*every* time the devices seems to be correctly redirected (driver installed and so on) but *when it comes ti really use* the device, it does not respond at all. Using mstsc with the same devices work like a charm.
--> Does the USB redirection works at all?
--> Has anyone succeeded in *really* using a device in the remote session? (i.e. more than just seeing it in the device manager)

**Comment by bjcollins** [comment]
@HenryJacques I have tested about 5 different webcams with this(2 form Microsoft and 3 from Logitech) and only one of the Microsoft cameras actually works for me. So, I know it can work. I have attributed my problems with the others to trying to use raw usb redirection with webcams which need high bandwidth and use isochronous transfers.

I have set "#define HAVE_NEW_LIBUSB 1" inside of "channel/urbdrc/client/libusb/libusb_udevice.c" in my builds.

**Comment by HenryJacques** [comment]
@bjcollins thanks for your feedback.

However one camera working out of 5 is not a satisfactory behaviour for me... 
I do not understand the difference between the one that works with freerdp and the 4 others. How do know it has something to do with "raw usb redirection which need high bandwidth and isochronous transfers"?
How do you know if a USB device use isochronous transfer? I presume you also set the camera who works in the freerdp command line the same way as the 4 others, no? I mean you also use raw usb redirection for the one who works? 
And by "working", can you use the highest resolution available for your camera?

I am not sure if high bandwidth is the only problem, because for example one of my usb device that I can't use with freerdp (optical fingerprint sensors) don't use so much bandwidth!

Thanks for the hint about the HAVE_NEW_LIBUSB declaration, I wasn't aware of that. What exactly does this bring to freerdp? Did your camera work before that?

Last but not least, two freerdp arguments are still cryptic to me: 
+async-input (default:off)  asynchronous input
+async-update (default:off) asynchronous update

What are the purposes of those? 
Is it related to the isochronous transfers.you've mentioned?

I'm sorry to bombard you with so much questions, and I don't know if you have the answers but there are some much aspects of freerdp which are not documented at all...

Thanks!

**Comment by HenryJacques** [comment]
I'm answering to myself concerning the USB transfer types. By using lsusb -vvv you get the bmAttributes which tells if the device works in Bulk or Isochronous transfer mode.
All the USB devices (except the webcam) I'm using are working with Bulk mode...

**Comment by bjcollins** [comment]
@HenryJacques I am no expert in this area. but here are some answers to your questions.

I was not trying to say that I thought that 1 of 5 webcams working was satisfactory, I just wanted to let you know that at some level things were not completely broke with the USB redirection code. The webcam that I see work is a Microsoft Lifecam VX-3000. By working I meant works at all. Other webcams just became unhappy and stop responding quickly when I go to use them redirected.

My concern with high bandwidth and isochronous transfers was only applied to webcams as the drivers for most webcams do not behave properly with all of the extra latency from redirecting the entire USB device. I have only been concerned with redirecting webcams as a backup option to more robust solutions for handling webcam redirection from other vendors(basic not using RDP protocol) which actually interface with the webcam locally and only have to transfer compressed/audio video over the wire.

There is nothing special you do as a user for a device which uses isochronous transfers on the command-line or otherwise. I do not know exactly what those async-input and async-update CLI options are for but they are unrelated to USB redirection.

I do not know much about the HAVE_NEW_LIBUSB option, just something for you to try. I believe it just uses the libusb library for some operations that it otherwise uses local functions for. I had no success before I set the HAVE_NEW_LIBUSB option.

**Comment by HenryJacques** [comment]
@bjcollins Many thanks for your answer and for the time you took.

I agree with you with the fact that the USB redirection code is at some point working. Indeed, my first post was about the fact that some part of the code is working (I can see the redirected devices in Windows) and the other not (I can't really use the devices I'm interested in).

My webcam is a Fujitsu WebCam 130 HD Portable which works "well" up to 640x480 but can't go higher... But this device is not the most important one for me, it only serves me to easily test the USB redirection (for example it is harder for me to "test" the correct behaviour of a fingerprint sensor).

You've also pointed something interesting about the Windows driver which can also behave the wrong way with the extra latency.... But I don't have any lever about this... :(

As for the HAVE_NEW_LIBUSB option, like you said, I'll try it and see for myself if it works for me.

Again thank you!

**Comment by HenryJacques** [comment]
Closing this issue as it has been answered. The subject is too vast and I will open a new case more specific.
