### ISSUE TITLE
two issues relate to ARM and full screen

### ISSUE THREAD

**Issue by cleric333** [FreeRDP/FreeRDP#2875]
I think it's better to have two issues with one post

issue one:

I am now trying to use Raspberry as a thin client, but the actual performance are very very bad

I use

Raspberry Pi2 B+ with 1GB RAM
Ubuntu Mate
as client 

Windows 2008 Enterprise plus Hyper-V as Host and Win7 Ultimate as the virtual machine

Problem: when I play a video, the video is very slow at the beginning and become better in about 100 sec, BUT when the video started playing better, the machine doesn't receive my mouse clicks and keyboard/ it needs about over 50 sec to respond a single click.

are there somebody with some experience on Raspberry? I am now not sure if the issue is from compiling XfreeRDP or the Raspberry itself.

issue two:

simple
with a normal X86 client (I5 4670 with Ubuntu 14), I am not able to get XfreeRDP into full screen, any advise?

**Comment by uforgetmenot** [comment]
You can try to use  graphic acceleration to impove xfreerdp performance!
https://github.com/FreeRDP/FreeRDP/issues/2858

**Comment by akallabeth** [comment]
@cleric333 FreeRDP currently only supports software decoding, so if you are running 1080p (just assuming ;)) then the raspberry will be too slow.

**Comment by cleric333** [comment]
I know a project called RPiTC (Rpitc.blogspot.hk). It puts XfreeRDP into it's system, and a video about playing a 3D game with Raspberry, but I am not able to make it work ( it should, cause there isn't any configure to do)....

**Comment by GothicIII** [comment]
Coincidentally I was working on exactly such problem. I conclude that raspberry+virtualisation with a rdp-session is not a good choice performance wise.

You will have two major problems, which slows the rdp-session down:
- The graphics acceleration on the raspberry
- The graphics acceleration on the virtualizationserver

The first problem is not very simple to handle because xfreerdp uses the X11-session for acceleration. Unfortunately there is no hardwareacceleration for X11 because the IGP of the Rpi is not opensource and the reverse-engineering of that was never completed. There exist beta-driver though they only work on a very old kernel-version (2.6 maybe). So freerdp can only use software-rasterizing.
Your best bet for this is the API with Directfb and the "dfreerdp" version from here. Its performance is superior compared to the x11-variant. Directfb works really well because it doesn't need a firmware/kernelsupport for the IGP, the API is communitcating with the graphics-hardware directly through a device-node. The downsite is that freerdp has dropped directfb support some time ago. You will have e.g. keyboard-mapping problems etc.
Another possibility to accelerate graphics performance is to use wayland. But there is still no freerdp-fork for it. So thats a bummer.

If you manage to get hardware-acceleration working on Pi the RDP performance will be better, but still sluggish because the visualization-software (hypervisor) needs hardware-rendering. This is done with a seperate graphicscard from NVIDIA/AMD and VMware/Virtualbox as virtualizazionsoftware.
Or you use a dedicated hardwarecluster with Hyper-V and remotefx. But this is for commercial use and is pretty expensive.

My solution was to buy a minnowboard MAX which has hardware-acceleration with X11 from day1. This one works great if you compile freerdp with the OpenH264-Codec. For the unresponding keyboard-/Mouse commands, which happen if you play a video, use the "+async-input" switch of freerdp.

Greetings GothicIII

**Comment by akallabeth** [comment]
@GothicIII Client side there is also the GFX-H264 extension to RDP allowing the client to more or less just play a H264 video. Requires more recent remote RDP server implementations (8.0 and up) but should be easily accelerateable on the raspberry. Of course this does not solve the server side performance issue.

**Comment by cleric333** [comment]
thank you very very much GothicIII

I actually use a separate server for the virtualization server running Hyper-V, and my Raspberry is only for connecting to the VPSes, I will have a look for Wayland. 

But for RPiTC, I am not able to have it running (screen turns to black for one sec and goes back to system when use freeRDP integrated in its system) but there is a video that he plays a 3D game on it with a OK speed.if here is any body use this script, mind to confirm?

And for Minnowboard.... it's too expensive for the purpose I can have any H81+I3+4G with the price of 199 USD, but really, thank you very much for the explain >: )

**Comment by cleric333** [comment]
http://blog.pi3g.com/2013/07/high-performance-rdp-on-the-raspberry-pi/
stopped?
https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=28294
stopped?
https://wiki.tizen.org/wiki/Weston_RDP_access
stopped?

**Comment by akallabeth** [comment]
so, closing this as it is a performance issue.
more recent versions of freerdp also support ffmpeg as backend for `/gfx:avc444` which may speed things up (if a ffmpeg with hardware acceleration is used)
