### ISSUE TITLE
xfreerdp randomly disconnecting

### ISSUE THREAD

**Issue by gh-user-7392** [FreeRDP/FreeRDP#3030]
Please help, this is driving me crazy. Using the latest master against a Windows 2012 R2 RDS server.
Clients are getting randomly disconnected. When this occurs the following three errors show up in the event logs:
1. RDP_GFX: An error was encountered when transitioning from PipeStateEncoding in response to PipeEventOnProtocolClosedFailed (error code 0x80070057).
2. RDP_GFX: An error was encountered when transitioning from PipeStateError in response to PipeEventOnError (error code 0x80070057).
3. The RDP protocol component WD detected an error (303) in the protocol stream and the client was disconnected.

In addition, the +auto-reconnect option does not have any effect. Here is the command line used:

$BIN/xfreerdp /rfx +compression -menu-anims -bitmap-cache -offscreen-cache -glyph-cache -themes -wallpaper /d:DOMAIN /sec:nla /cert-ignore /f /bpp:32 +auto-reconnect /u:$USER /p:$PASS /v:$IP

I have one client that has never been disconnected that uses the above command line with two additional options: /gfx +gfx-progressive

Do any FreeRDP gurus know anything I can try to solve this problem. The fact that the +auto-reconnect does not kick in really puzzles me.

Thanks

**Comment by bmiklautz** [comment]
@freerdp-bot with what version are you encountering this problem?

**Comment by freerdp-github** [comment]
This is FreeRDP version 2.0.0-dev (git 57fe581) from Dec 13th but it has been happening with all versions up until then as well.

**Comment by bmiklautz** [comment]
@freerdp-github can you try without /rfx or without compression?

**Comment by freerdp-github** [comment]
Yes, I will try that and see how the clients respond. BTW, I noticed that I am getting network detection disabled errors also if that helps. Specifically, I am getting this pair per every connection:

1. The network characteristics detection function has been disabled because of Reason Code: 2(Server Configuration)..

2. The network characteristics detection function has been disabled because of Reason Code: 1(Client not supported)..

I understand that the network detection is new part of RDP 8.1 so it may not be implemented. Just thought I would mention it.

**Comment by freerdp-github** [comment]
I am trying two different approaches based on your input and the messages received First, on all of our thin clients, I have taken off the +compression option to see if that helps. Second, I have added the /gfx +gfx-progressive options to a random sample of thin clients because I know of one other client that has never been disconnected using this combination. I will see if there are any disconnects during this weeks testing. BTW, my OS is Ubuntu 14.04.3 LTS. Thanks for any help.

**Comment by hardening** [comment]
@freerdp-github just to explain, there's basically 2 cases:

* if you use the /gfx flag, then the client uses the new shiny egfx channel and all graphical orders are transported in this channel. RemoteFx can also be done within the egfx channel;
* with "only" /rfx, the graphical stream will be transported in more traditional (aka old) surface commands;

This explanation just to say that the code path is really different depending on the used command line switches.

**Comment by freerdp-github** [comment]
@hardening I appreciate the explanation. I will summarize my findings from this weeks testing later today. I do find it strange however to get RDP_GFX errors during a connection (and subsequent disconnect) that only used /rfx on the command line. It could be possible that MS is doing that as these errors emanate from the server. I also want to confirm that you are saying normally you would not use the /rfx flag and /gfx flag together as they do the same thing. In other words, /gfx is the new /rfx?

**Comment by freerdp-github** [comment]
FreeRDP disconnect testing summary:

1. Took +compression off command line on all thin clients. Turns out, this does not matter because the default state for compression is on anyway.

2. Added /gfx +gfx-progressive option to all thin clients. This fixed the disconnect problems. I no longer get the RDP_GFX related Event Log errors.

3. Took the /rfx option off and left only the /gfx +gfx-progressive option. No disconnects as well. Not sure yet about if the user experience is any different (graphics) because of this change. I would not think so.

4. Adding the /gfx +gfx-progressive option disrupts the synchronization of the NUMLOCK state between client and server (see issue 2822, 2083, etc. ).

Discussion:

Final command line used to eliminate disconnects in our environment: 
$BIN/xfreerdp /gfx +gfx-progressive -bitmap-cache -offscreen-cache -glyph-cache -themes -wallpaper /d:BCS /sec:nla /cert-ignore /f +auto-reconnect /u:$USER /p:$PASS /v:$IP

I could not test whether auto-reconnect worked because it did not disconnect. When just /rfx is used without the /gfx options I get RDP_GFX errors.  @hardening mentioned that the code for RFX and GFX are independent of each other. However, in order to not get disconnected and use RFX, we must add the GFX options. This was determined by chance because I was using the GFX options for one particular thin client, which is a little unsettling. If /rfx is removed we do not get any disconnects as well. Another unwanted side-effect of using the GFX options is that the NUMLOCK synchronization problem arises once again. I'll leave that to the developers to decide on the best course of action to fix that. The GFX options are nice because the user experience with our CAD applications using the experimental RDP8 graphics pipeline code has been very positive.

Finally, at this point however, I am reluctant to upgrade my master build for fear of having to go through these iterations again. I realize you should not use the master for production but as of late it appeared very stable as a possible 2.0 release version nears.

Thanks for the hard work!

**Comment by akallabeth** [comment]
@freerdp-github Does this issue persist after #3015 has been merged?

**Comment by freerdp-github** [comment]
I don't believe this is related to my problem because we are on the LAN and TCP issues like this should not be occurring. I believe the problem is caused because I was using both the /rfx and /gfx command line option simultaneously which I believe is not correct.

**Comment by akallabeth** [comment]
@freerdp-github Those options do not interfere with each other. They merely enable support for different features which are only activated if both, client and server support them.

**Comment by akallabeth** [comment]
Any update on this one?

**Comment by gh-user-7392** [comment]
With the latest git master, the gfx performance has been much better. We still need to use the progressive codec for best performance. To the point however, this issue is no longer a problem so I am closing it. Thank you for all your help.
