### ISSUE TITLE
Broker redirect - second login

### ISSUE THREAD

**Issue by SaibotCook** [FreeRDP/FreeRDP#3089]
When i start the connection with FreeRDP i get to the Windows loginscreen.
When i enter my username and password i then get redirected to a different session by the broker and have to re-enter my username and password.
Is there any way to enable SSO?

Im running FreeRDP with this command
`xfreerdp /v:rd-farm /d:DOMAIN /kbd:0x00000407 /bpp:32 /f /cert-ignore -sec-nla`

**Comment by hardening** [comment]
Hi, it would be interesting to know more about the redirect packet that is sent, would you recompile with WITH_DEBUG_REDIR activated and send us the output ?
You didn't tell but I suppose you're running master ?

**Comment by SaibotCook** [comment]
Could you explain to me how to recompile with WITH_DEBUG_REDIR and what "running master" refers to?
I'm new to FreeRDP.
Thanks in advance.

**Comment by hardening** [comment]
OMG, well first we need to know more about your environment (where you FreeRDP came from and which version it is), that's really the basic.

And "running master with WITH_DEBUG_REDIR"  means checking out FreeRDP source code and recompile with this option activated (ccmake is your friend to activate it).

**Comment by Hobby-Student** [comment]
correct me if I'm wrong... Doesn't "-sec-nla" connect without pre-auth? (So you see the Server-Loginscreen and type in username and password. When Session Broker is redirecting same screen on the "free" server is shown.)

IMHO this is by design, also with the MS RDP client...

**Comment by bmiklautz** [comment]
@SaibotCook did you test your setup with the Microsoft client without NLA as well. As @Hobby-Student wrote when no NLA is used no auth is done and the SSO only works when you already have a running session you re-connect to.

**Comment by nfedera** [comment]
@SaibotCook What @bmiklautz and @Hobby-Student wrote is right. IMHO no one seems to be sure if this is a bug or really by design.

However, if 1.) the credentials are not entered at the rdp client but in the windows session **and** 2.) the terminal server farm members are configured to participate in Connection Broker Load-Balancing ...

![image](https://cloud.githubusercontent.com/assets/670606/14378585/0dda7308-fd76-11e5-9309-b9a1444bf711.png)
... you'll have to reenter the credentials if you're redirected.

You can easily reproduce this in mstsc by by setting `enablecredsspsupport:i:0` in a rdp file (nb this only works if the server does not enforce NLA)
