### ISSUE TITLE
Wiki Compilation - says Plugins are installed in /usr/local/lib/freerdp

### ISSUE THREAD

**Issue by bmullan** [FreeRDP/FreeRDP#3127]
I am on ubuntu 15.10 64bit.   I have followed the instructions for debian multple times now to build freerdp.

Each time I see no errors and afterwards I do end up with xfreerdp v2.0.0-dev

But despite the Wiki indicating that the plugins would be found in /**usr/local/lib/freerdp**,

> Plugins are installed in /usr/local/lib/freerdp:
>
> awake@envy:/usr/local/lib/freerdp$ ls
> cliprdr.so  disk.so  drdynvc.so  printer.so  rail.so  rdpdbg.so  rdpdr.so  rdpsnd_alsa.so  rdpsnd.so

I don't find them there?   Is the Compilation Wiki page still accurate?

**Comment by bmiklautz** [comment]
@bmullan first of which wiki page are you referring to?
The search path basically depends on how FreeRDP is built. In a default build, without modifying the paths cmake uses, the location /usr/local/lib/freerdp should be the right one. However what the page doesn't seem to state is that channels are built statically since a while and linked together into libfreerdp-client.so. If you want/need the channels to be installed as separate libraries you need to specify -DSTATIC_CHANNELS=OFF when running cmake.
