### ISSUE TITLE
Android aFreeRDP client too slow

### ISSUE THREAD

**Issue by kerbymart** [FreeRDP/FreeRDP#3203]
Compared to the Windows client, the android app is very slow and barely usable even on LAN connections.

**Comment by akallabeth** [comment]
android client is currently lacking hardware support.
to ease your problems check the resolution settings, if I remember correctly it is using native by default which usually is way too high

**Comment by realjiangms** [comment]
What's your server and client device? It is running on mobile device and should only be able to connect via WLAN which is slower and has higher latency than normal LAN. 
I tried it on my Nokia N1 (Less than $200) and mobile phone (Less than 150$) and connect to an RFX enabled server in WLAN, with 1080p video it could have over 20 FPS (reported from server).

Android client now only support software GDI, I agree it could cause performance hit

**Comment by akallabeth** [comment]
@realjiangms I've began work on color fixes for software render path, https://github.com/FreeRDP/FreeRDP/tree/color_conversion_fix_v4 
It already contains great improvements for image quality and reduced artifacts.
I'm currently testing against windows xp, 7, 8, 8.1 and 10 (in all GDI, RFX and GFX modes)

**Comment by realjiangms** [comment]
@akallabeth Thanks for your effort on color conversion. Android client now still have some artifacts on my Nokia N1 for GFX and normal image update (image compression without RFX/GFX), however, it works fine on another ARM based android phone. I guess it could be fixed by your improvement.

By the way, will you use android media framework to implement h264 client instead of software openh264? I found it has terrible performance with openh264 on android due to low CPU ability.

**Comment by akallabeth** [comment]
@realjiangms Good to hear that it works at least in some cases. As for H264, for the time being no hardware support is planned.

**Comment by akallabeth** [comment]
Closing issue as no improvement is planned.
If someone is interested in hardware acceleration support I may be able to give some guidance.
