### ISSUE TITLE
Input speed regression when video buffer full

### ISSUE THREAD

**Issue by BanHammor** [FreeRDP/FreeRDP#3264]
When I try to play a fullscreen video on a remote machine with my ARM-based device as an xfreerdp client, I have to wait an indefinite amount of time (or however much it takes for the video i'm playing to become briefly static) in order for my keypresses and mouseclicks to have any effect.
The issue becomes much worse with bigger screen resolutions, as on a 640x480 screen the keypresses only have moderate amounts of lag (<1 sec).

Options like /async-input and /async-update were tried, but seemed to have an adverse effect on video refresh rate without being effective at reducing input lag.

Issue only concerns the 1.2.0 (master) branch and not 1.1/1.0. On the current stable-1.1 keypresses register in a reasonable amount of time.

Steps to reproduce:
1. Start up xrdp on server machine
2. Connect to server machine on a client with weak CPU via `xfreerdp /v:<server-ip> /f`
3. Play a video with a lot of movement on full screen via FreeRDP.
4. Try to use your mouse or keyboard to, for example, stop video playback.

What happened:
Video didn't stop until ~25 seconds later

What was expected to happen:
Video would stop immediately as the keyboard button was pressed.

**Comment by bmiklautz** [comment]
@BanHammor what git version did you test with? Just to clarify the described behavior occurs when you test with xrdp on Linux? - Did you test against a Windows server as well?

**Comment by hardening** [comment]
I feel like if xrdp sends 25s of video stream without caring if the client can handle it, xrdp is to blame. I guess that xrdp have some tips that the client wants less frames, like blocking write and such (missing frame acks).

On the other side, perhaps that on the xfreerdp side we could limit the amount of packets we treat from the network when we're in the main loop, so that we would treat a bunch of packets (not all) and then go back to treating inputs. Just an idea.

**Comment by WarheadsSE** [comment]
Is this related to what might happen when you're doing a large about of putImage calls to X? We have seen things akin to this behavior (delayed input due to overwhelming the X stack with repaints) on multiple versions, and can reliably replicate it on systems with poor 2D GPU support in X. One such test case we have is connecting to a Windows 2003R2 server with Excel opening a very large sheet and scrolling down by clicking (and holding) on the empty space between slide and the down arrow on the scroll bar.

**Comment by hardening** [comment]
@BanHammor @WarheadsSE would you mind give a try to this branch that limits the number of PDUs treated per loops, and should give you a smoother feedback of the inputs https://github.com/hardening/FreeRDP/tree/limit_frames ?

**Comment by WarheadsSE** [comment]
@hardening While this does prevent the session from freezing on my client, the delay in further input can still be quite significant. (I test on: 2003 R2, Outlook 2007, Inbox with > 10K items, holding down the scroll space between the scroll bar and the down arrow)

**Comment by hardening** [comment]
I have updated my patch to limit the time spent, instead of the number of PDU, would you mind give a try ?
https://github.com/hardening/FreeRDP/tree/limit_frames

**Comment by akallabeth** [comment]
The patch from @hardening is working, therefore closing.
