### ISSUE TITLE
FreeRDP clipboard MonitorReady event

### ISSUE THREAD

**Issue by sergsalo** [FreeRDP/FreeRDP#3331]
it seems to me that in FreeRDP v2.0xx event MonitorReady is not sent anymore. We used this event as an indicator that clipboard is ready to be used. Client and Server are both windows 2012 r2 hosts.

**Comment by byteboon** [comment]
We are using 2.0xx code and do receive the MonitorReady call.

We have a PubSub_SubscribeChannelConnected hook that watches for the channel name of CLIPRDR_SVC_CHANNEL_NAME and initializes the cliprdr context callbacks (including MonitorReady). After that, we get the event fine --- so I know it works.

Is this something you had working previously?

**Comment by sergsalo** [comment]
seems like that's exactly what we do. 
yes, it worked with 1.xx
Good to know it works, so I'll keep digging

**Comment by sergsalo** [comment]
@byteboon what version of FreeRDP are you using? maybe i can try build that one and see if there is any difference.

**Comment by byteboon** [comment]
We're using an older version of 2.0 with patches in production, but I was able to test with master as of yesterday and it was still working.

**Comment by spimenov** [comment]
We run into similar problem with the new FreeRDP version. MonitorReady was not sent and clipboard didn't work. Problem was in our ServerCapabilities function that returned 1. It looks like old FreeRDP version ignored the return value and our code worked fine. Now FreeRDP checks the returned values and MonitrReady was not sent after that. The fix was simple - ServerCapabilities returns 0. As all other callback functions.
