### ISSUE TITLE
Special characters in password

### ISSUE THREAD

**Issue by stephenl03** [FreeRDP/FreeRDP#3448]
When special characters are being used in the password, freerdp fails to connect.

xfreerdp /cert-ignore +clipboard /bpp:16 /size:1280x960 /g:gateway.domain.com /gd:DOMAIN /gu:username /gp:pa$$word /v:vts.DOMAIN.com:3389 /d:DOMAIN /p:pa$$word /u:username
[15:21:49:284] [7121:00081000] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[15:21:49:305] [7121:00081000] [INFO][com.freerdp.client.x11] - Property 296 does not exist
[15:21:49:597] [7121:00081000] [ERROR][com.freerdp.core.gateway.tsg] - tsg_check failure
[15:21:49:597] [7121:00081000] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[15:21:49:597] [7121:00081000] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]
[15:21:49:597] [7121:00081000] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[15:21:49:597] [7121:00081000] [ERROR][com.freerdp.client.x11] - Freerdp connect error exit status 1

xfreerdp /cert-ignore +clipboard /bpp:16 /size:1280x960 /g:gateway.DOMAIN.com /gd:DOMAIN /gu:username /gp:'pa$$word' /v:vts.DOMAIN.com:3389 /d:DOMAIN /p:'pa$$word' /u:step9170
[15:07:56:673] [6821:00081000] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[15:07:56:686] [6821:00081000] [INFO][com.freerdp.client.x11] - Property 296 does not exist
[15:08:00:968] [6821:00081000] [INFO][com.freerdp.core.gateway.tsg] - TS Gateway Connection Success
[15:08:03:599] [6821:00081000] [INFO][com.freerdp.core.gateway.tsg] - TS Gateway Connection Success

**Comment by T3N4K4** [comment]
I guess this is not a FreeRDP bug since you have to quote most of the special characters especially "$" which is used for variable names in linux distributions..

**Comment by troyengel** [comment]
Unfortunately, when you remove the /gp: or /p: from the commandline and let FreeRDP prompt for it, the connection then hangs with the process spinning at 100% on a CPU and no output (nothing graphical either) when using the Balabis SCB device as a gateway. Running a strace() on it doesn't provide anything too useful, hard to tell exactly what's wrong. As such we manually prompt for the password then attempt to pass it to xfreerdp as a workaround.

For reasons I cannot yet determine, attempts to pass the $ character in a password from a bash script to xfreerdp fails no matter what, even when you hard code single quotes around it, prefix it with an escape character, use array words instead of single variables, and every other hack and trick I personally have tried. They *look* good when you trace it and pass the code over (bash -x e.g.), but something in the subprocess is eating that $ character which befuddles my attempts to get working.

**Comment by bmiklautz** [comment]
@troyengel did you try to escape the whole parameter like
```
'/p:pa$$word'
```
That way your shell shouldn't interpret the $$ and FreeRDS doesn't get any additional quotes (which would probably be included in your example from above).
There is also a PR from @akallabeth (#2570) that tries to handle quoted arguments as well. If the quoting like described above doesn't work give that branch (https://github.com/akallabeth/FreeRDP/tree/cmdline_escaped_argument_support) a try.

**Comment by troyengel** [comment]
I see the commit in his tree and it looks like something that might help - yeah so far I've tried a ton of things like:
````
'/p:pa$$word'
/p:'pa$$word'
/p:pa'$$'word
/p:pa\$\$word
````
...etc. I really do think it has something to do specifically with bash passing the options when launching it, even when I use an array like so (fake various examples):
````
declare -a XFLAGS
XFLAGS+=(/p:pa'$$'word /'gp:pa$$word')
xfreerdp "${XFLAGS[@]}"
````
When run under bash -x, it *looks* like it's preserving all the quoting and stuff, but it fails. If you simply type on the commandline the exact same things it works -- I feel it's something very unique to passing the data as variables to the process in a script, just can't figure out how to get it working right.

(side note: due to a very similar issue with the space character, using arrays to send the parameters as word objects is required - another discovery we made)

**Comment by HenryJacques** [comment]
@troyengel 

Using Master from May 27th works perfectly well on my setup (Ubuntu Trusty and bash):

`xfreerdp /v:server /u:user '/p:$$ test' /sec:nla`

I really do thins it has something to do with your in-band gateway (a Balabit SCB right?)

Can you test directly (without the gateway)?

**Comment by troyengel** [comment]
If you run it like you mentioned directly on the commandline, it works -- if you write a simple bash script like this:
````
MYPASS='/p:$$ test'
xfreerdp ... ${MYPASS}
````
...does that still work? It has to do *specifically* with passing it from a bash wrapper as a variable, not using it directly. (sadly, I do not have the option of not using the Balabit SCB - I agree this appliance might be part of the problem)

**Comment by HenryJacques** [comment]
@troyengel 

Yes it works in a script.
You have to use this instead:

`MYPASS='/p:$$ test'`
`xfreerdp ... "${MYPASS}"`

**Comment by troyengel** [comment]
yeah I get the " need, I was just typing quickly - that wasn't meant verbatim. Unfortunately this is what we can't get working (and many variants of it), and it has to be an array for the space issue - it's possible this is limited to the old default version of bash on Mac OS X (3.2) but the testers have tried brew bash (v4) with no better results. We'll keep banging on it - if you escape the $ (\$) there is a high ability to segfault xfreerdp depending on which exact code is in use.

This project needs to start tagging official releases, it's a gamble which piece of code any one workstation is on because they're all compiling at that time with brew from HEAD from github. Even the main Linux distros (Ubuntu, Arch, Fedora) are all over the map as to which exact FreeRDP code is in use, it's a real PITA to develop working solutions like this...

**Comment by akallabeth** [comment]
Assuming this is not a FreeRDP issue, closing.
Feel free to reopen if you think this is.
