### ISSUE TITLE
Switch layout (alt+shift) doesn't work on wayland

### ISSUE THREAD

**Issue by masepi** [FreeRDP/FreeRDP#3475]
alt+shift change main layout, not remote machine laout.

**Comment by masepi** [comment]
Fedora 24
xfreerdp 2.0.0-dev
Gnome 3.20 + wayland

**Comment by bmiklautz** [comment]
@masepi would you please add more details? Not sure what main layout and remote machine layout is.

**Comment by Durlyn** [comment]
Does not work switching keyboard layouts in xfreerdp+wayland.
client: Fedora 25
FreeRDP version 2.0.0-dev (git n/a)
Gnome 3.22 + wayland session.

server: Windows 10 Pro.

**Comment by hardening** [comment]
@Durlyn if by xfreerdp+wayland you mean wlfreerdp, then a lot of xfreerdp's feature aren't currently implemented in wlfreerdp.

**Comment by Durlyn** [comment]
No. xfreerdp runing in wayland session.

**Comment by prg318** [comment]
I know this is a really old bug, but i'm running into a potentially similar issue and will add my two cents to this one. It looks like X11 and Wayland handle keyboard shortcuts differently.

When running the xfreerdp client in an X11 session, you can press a hotkey combination recognized by both the local X11 WM and remote rdp session (such as alt-tab, win-d, win-e - depending on your OS or WM) and the hotkeys will be grabbed by the xfreerdp client, and not the X11 session.  For example, pressing alt-tab in an X11 xfreerdp window will switch the active window on the remote RDP session.

When running the xfreerdp client in a wayland session (tested with plasma-wayland), when pressing a hotkey combination recognized by both the local wayland WM and the remote rdp session (such as alt-tab) and the hotkeys will be grabbed by the local wayland session and will not be passed to the freerdp client.  For example, pressing alt-tab in a wayland freerdp window will switch the active window in the local wayland session.

I personally really like being able to use shortcuts in a remote RDP session without having to remap everything, which is one of the many reasons that I have stuck to using X11 instead of wayland, but I figured I would pass this along in case this could be potentially handled differently on wayland somehow.

**Comment by akallabeth** [comment]
tested on `xwayland` on `fedora 36` with `2.7.0:

* all Keyboard shortcuts work as intended if `xfreerdp` has focus (e.g. you have mouse moved/clicked into the window)
* Just switching with `alt + tab` will not do.
