### ISSUE TITLE
AVC 444 mode

### ISSUE THREAD

**Issue by puneet101** [FreeRDP/FreeRDP#3490]
What are the plans to update FreeRDP to implement the changes announced my MSFT for RDP 10?

**The main challenge to use AVC/H.264 as the one and only Codec in Remote Desktop scenarios is that text shows a halo effect with typical implementations of AVC/H.264. This is caused by the color conversion process that happens as part of the compression which throws away some of the**

https://blogs.technet.microsoft.com/enterprisemobility/2016/01/11/remote-desktop-protocol-rdp-10-avch-264-improvements-in-windows-10-and-windows-server-2016-technical-preview/

**Comment by ilammy** [comment]
@puneet101, FreeRDP actually supports AVC444. The `/gfx:AVC444` command line option should enable it. However, there are several issues with AVC444 support on the server-side.

**Comment by puneet101** [comment]
Can you describe the several issues you allude to above? 

How do you decide the default option and what do you think is the default coming in the MSFT mstsc client? 

Thanks!

**Comment by ilammy** [comment]
First of all, for some reason some Windows 10 systems refuse to use AVC444 unless _Prioritize H.264/AVC 444_ GPO is set. Apparently this has been fixed with some latest update and now systems behave as described in that blog post. Then we've seen servers to send malformed AVC444 data to the client which breaks the encoder after some time, like 5 to 30 minutes.

mstsc.exe client from Windows 10 supports AVC444 and has it enabled by default. I am not aware of any way to disable it.

**Comment by puneet101** [comment]
Thanks! AVC444 is pretty standard now. Should be enabled by default. 

Has this been tested only on Win client or other platforms also?

**Comment by ilammy** [comment]
I believe all FreeRDP clients should support it with software GDI enabled (`/gdi:sw`). X11 client has also 'hardware' support.

**Comment by akallabeth** [comment]
AVC444 server side support for FreeRDP is not there yet, but client side is working as @ilammy pointed out. As for Win10 not defaulting to it, we can't do much about it ;)
