### ISSUE TITLE
RemoteAPP - Maximized windows are restored down after minimizing

### ISSUE THREAD

**Issue by mrpink37** [FreeRDP/FreeRDP#355]
When minimizing a RemoteApp window to taskbar and subsequently maximizing it again the window is restored down and not maximized anymore.

Applications Tested: MS Office 2010, Acrobat X
Client: Ubuntu 11.04 Gnome 2.32

**Comment by albert-a** [comment]
The same with 2.0

**Comment by bmiklautz** [comment]
I'm closing this issue because it has been inactive for a while.
Possibly we've already fixed the issue or it is not reproducible (anymore).

If you still encounter the reported problem with our [latest stable release](https://github.com/FreeRDP/FreeRDP/releases) please re-open this issue with updated information or create a [new bug report](https://github.com/FreeRDP/FreeRDP/issues/new?template=bug_report.md).

Thank you!
