### ISSUE TITLE
Performance with Full Screen Video / Animations on Chrome

### ISSUE THREAD

**Issue by DanAztec** [FreeRDP/FreeRDP#3811]
Hey Guys!

We're currently running a scenario where we have multiple users on Thin Clients - currently when a user browses to a website with a full screen video background it's locking the machines up, is there a switch within FreeRDP we can use to offload some/all of the rendering to the server? (Current Parameter is -maximized -e "xfreerdp /jpeg /rfx +compression +fonts /cert-ignore /f /d:check.local /v:???.???.com /g:???.???.com /load-balance-info:'tsv://MS Terminal Services Plugin.1.Full_Desktop.NBI'")

**Comment by akallabeth** [comment]
@DanAztec ```/rfx``` and ```/gfx``` family already encode the whole desktop server side and the client is only doing decoding. 
These options require server support. The client can just announce availability but the server selects the actual mode used, so depending on your OS the results may vary.

**Comment by DanAztec** [comment]
@akallabeth I was unaware that there is a /gfx switch? Just looking at enabling /rfx server side and it's a bit beyond what we want to do at the moment. Otherwise would there be any other switches or tweaks you could recommend that may help with sites such as https://prezi.com/ ?

**Comment by akallabeth** [comment]
@DanAztec Well, depends on your setup. But since you have quite a lot of dynamic content in your example these are your best options. (classic GDI does send everything as bitmap that is not mappable to GDI calls)
Since your question seems to be answered I'll close this one.
Just for reference, please use the mailing list for questions such as these in the future.
