### ISSUE TITLE
Screen "corrupt" in RAPPS mode - sometimes

### ISSUE THREAD

**Issue by meersjo** [FreeRDP/FreeRDP#4012]
When opening the initial connection for RAPPS mode, FreeRDP initially allocates a full-screen window showing the windows login screen across all monitors - I understand this is by design, I presume bc it allocates a buffer of that size.

However, sometimes - not every time, always on initial connection and impossible to reliably reproduce - this will cause an issue with my X display where some, but not all, pre-existing windows are no longer visible. One of the typical victims is Firefox; but Terminator windows are affected only sometimes; even some of them affected and some of them not in the same occurrence.

I understand that this is a pretty vague description, and probably going to be damnably hard to pin down; so my main question is whether there is a way to have FreeRDP allocate that initial buffer in a window instead of at (I presume) root level? Other workarounds also welcome, of course; the only remedy I currently have is to force-kill my X session.

**Comment by bmiklautz** [comment]
@meersjo Please have a look to https://github.com/FreeRDP/FreeRDP/wiki/BugReporting and add more information. It's really a little bit vague ;).

**Comment by ilammy** [comment]
When starting a remote app FreeRDP can create a window if the server needs to draw something like a login screen. It should close the window once the server finally starts the remote app mode.

I'm not really an X server, window manager and compositor expert (as opposed to Xlib), so I have no clue why the windows can disappear. From what I can guess it seems that the compositor runs out of memory due to FreeRDP's large requests, and other applications can't recover.

Also, what do you mean by "no longer visible"? Are the window invisible (even after minimize-restore)? Or are they obstructed by FreeRDP's window being on top of everything?

You can try fiddling with `xf_rail_{enable, disable}_remoteapp_mode()` in xf_rail.c (called when switching modes), `xf_create_window()` in xf_client.c (called to setup the initial window, may not create the desktop window at all if we are starting in remote app mode initially), `xf_CreateDesktopWindow` in xf_window.c (creates the actual desktop window). xf_CreateDesktopWindow() really first creates the window with root window as parent (see XCreateWindow() call there), but that's a normal way to create a top-level window.

RAIL issues are hard 😭

**Comment by meersjo** [comment]
> what do you mean by "no longer visible"?

The windows still appear in the taskbar, but don't show up even after minimize/maximize. I don't think they're obstructed by the RDP root window, as others are still accessible. It does seem to close the original login window, so you might be right that it might be the composer's problem - this laptop only has generic intel graphics, after all. I have the impression (but it's really just that) that it's more likely to happen when the laptop has been running for a few days as opposed to when it's freshly booted, so that may also point at a composer problem.

@bmiklautz , Yeah, I know it's horribly vague. I'll try to take some more notes next time it happens.

For reference, I'm currently on Linux Mint 17.3 64-bit XFCE edition; when and if I get around to upgrading to 18.x I'll see if it still happens there, too.

**Comment by bmiklautz** [comment]
@meersjo what FreeRDP version you are using there?

**Comment by meersjo** [comment]
@bmiklautz: 2.0.0-dev (git 8569102c3). It's not been limited to that version, however - I've occasionally had it for quite a while, on various builds. I don't pass any special parameters for the build, I simply follow the wiki instructions.

I just had it again; the only visible window was a terminal, so I managed to take a screenshot this time.

This is the first time that it happened when using a window that was already opened succesfully; typically it occurs when starting a remote application. In trying to screenshot, I found that new windows also do not appear - you can see the icons in the taskbar.

![screenshot_2017-07-17_14-57-19](https://user-images.githubusercontent.com/1178044/28272880-13d27a66-6b0d-11e7-9b92-513d2c61afa8.png)

Clicking the taskbar buttons yields no effect; but it does toggle the focus on the remaining terminal window, so presumably the windows are still there but don't get drawn. That is corroborated by the fact that the xfce4-screenshooter command required interaction to confirm the filename to save; pressing enter did confirm that and save the file, as the window got focus when it launched.

**Comment by hardening** [comment]
@meersjo do you get the same with another WM ?

**Comment by meersjo** [comment]
I have not used another wm in years, as xfce has been tuned to my liking on my work laptop. I'll see if I can install another and work with it a few days, but as I can't consistently reproduce the problem there's no guarantee.
