### ISSUE TITLE
warning: #warning "FFMPEG does not support H264 encoding (GFX H264 server mode)

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#4057]
I compile for openSUSE Tumbleweed with:

-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_SKIP_INSTALL_RPATH=ON -DWITH_CUPS=ON -DWITH_CLIENT=ON -DWITH_PCSC=ON -DWITH_ALSA=ON -DWITH_PULSE=ON -DWITH_OSS=OFF -DWITH_DIRECTFB=OFF -DWITH_JPEG=ON -DWITH_GSM=ON -DWITH_GSTREAMER_1_0=ON -DWITH_IPP=OFF -DWITH_OPENSSL=ON -DWITH_CHANNELS=ON -DWITH_X11=ON -DWITH_XCURSOR=ON -DWITH_XEXT=ON -DWITH_XKBFILE=ON -DWITH_XI=ON -DWITH_XINERAMA=ON -DWITH_XRENDER=ON -DWITH_XV=ON -DWITH_ZLIB=ON -DWITH_KRB5=ON -DBUILTIN_CHANNELS=OFF -DWITH_SERVER=OFF -DWITH_SSE2=ON -DWITH_DEBUG_SCARD=OFF -DWITH_SMARTCARD_INSPECT=ON -DWITH_WAYLAND=ON -DWITH_LIBSYSTEMD=ON -DCMAKE_NO_BUILTIN_CHRPATH=ON 

Together with the available devel-libraries this results in:
-DWITH_FFMPEG=ON
-DWITH_X264=OFF
-DWITH_OPENH264=OFF 

Now I get this message:

[   55s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/codec/h264_ffmpeg.c:29:2: warning: #warning "FFMPEG does not support H264 encoding (GFX H264 server mode). Please review your configuration!" [-Wcpp]
[   55s]  #warning "FFMPEG does not support H264 encoding (GFX H264 server mode). Please review your configuration!"
[   55s]   ^~~~~~~

Is this expected with above options?
For legal reasons the openSUSE packages do not support any patent encumbered codecs.

**Comment by ilammy** [comment]
[`libfreerdp/codec/h264_ffmpeg.c`](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/codec/h264_ffmpeg.c) has an unconditional #warning directive there which produces the message. So I guess currently it will show up in any builds with ffmpeg. Apparently, that has been introduced as a memo for developers because H.264 encoding with ffmpeg is really not implemented. However, this has nothing to do with configuration: we're not using a broken ffmpeg or something, it's FreeRDP that has no implementation. So maybe we should change the message or even move it somewhere to CMakeLists.txt.

**Comment by akallabeth** [comment]
@hendwolt As @ilammy pointed out there is no encoder backend for FFMPEG so shadow server and such will not work. This is work in progress, as #4053 adds rudimentary encoder support (still needs parameter tuning) and will resolve this issue.

**Comment by akallabeth** [comment]
Fixed with #4053
