### ISSUE TITLE
Don't use deprecated gethostbyname(), migrate to getaddrinfo() - support IPv6

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/FreeRDP#4147]
Following http://udrepper.livejournal.com/16116.html this function should not be used in 
winpr/libwinpr/winsock/winsock.c and
winpr/include/winpr/winsock.h

**Comment by weberhofer** [comment]
A IPv6 connection problem was just reported to https://bugzilla.opensuse.org/show_bug.cgi?id=1061874 . I think, it's related.
Also the tickets #1949 and #4132 are related to this ticket.

**Comment by bmiklautz** [comment]
@weberhofer I don't think they are related. FreeRDP's IPv6 support is still very very basic not all paths are tested (or even implemented - thinking about redirection). Therefore what it currently does is to prefer IPv4 if it's available in DNS.

**Comment by thomasschaeferm** [comment]
@bmiklautz 
"Therefore what it currently does is to prefer IPv4 if it's available in DNS." 

That is a very bad situation. 

I know that IPv6-deployment is in very different stages - world wide. But nevertheless, your decision  breaks a lot of networks configurations or the traffic  takes the wrong way. 
It doesn't work at the moment on an IPv6-only/NAT64-access, despite the server is correctly configured. ( the app would fail the apple-appstore-NAT64 compatibility test)
It uses the wrong way (in my case ipv4-CGNAT at mobile, ipv4-NAT-portforwarding at the Server at home) instead of the direct connection(IPv6).
Other people (e.g. cable isp in Germany, but also some classic DSL-isp) have only unstable IPv4 (CGNAT, DS-lite) in one direction and no IPv4 in the opposite direction, but they have a solid IPv6-access to the internet.

**Comment by bmiklautz** [comment]
@thomasschaeferm I'm aware that the current solution isn't ideal. However there are multiple places in the code where IP addresses are handled and all of those need to be tested if v6 support doesn't cause any issues. To name some:
* gateway support
* redirection (load balancing)
* wtsapi

It's quite some effort to test, and possibly fix, all of them (multiple test scenarios and environments needed..). But we haven't come around to work on this yet. But **pull request are very welcome**.
Therefore the taken approach was to add basic support and use it when a ipv6 address is explicitly set or only a AAAA is available.

As for "breaking a lot of networks". If an A record is configured it should work otherwise either don't expose it or there is something broken in the setup.

Anyway. What would simply be possible is to add an /ipv6 switch to force the usage of ipv6. This would at least allow regular connections to prefer ipv6.

**Comment by thomasschaeferm** [comment]
The switch /ipv6 may a good idea, because most people cannot manipulate the DNS.
Providing A-records is usually a thing of the server site. The server admin has no influence how the clients are connected to the internet.  DS-lite, CGNAT may still work, but networks with IPv6-only/NAT64 don't, such networks exist already. 
(don't think about 464xlat, it is an ugly hack and often not available or wrong implemented)
I am a sysadmin and a very bad programmer, so I can't provide pull requests, sorry.

**Comment by akallabeth** [comment]
The functions are nowhere used in the library, but WinPR exports wrapper functions that may be used by other software.
Closing this as there is nothing to remove.
IPv6 support is tracked by #1949

**Comment by weberhofer** [comment]
Doesn't line 1215 in winpr/libwinpr/winsock/winsock.c just call gethostbyname()?

**Comment by akallabeth** [comment]
@weberhofer That is the wrapper function WinPR exports, but it is not used by libfreerdp

**Comment by weberhofer** [comment]
Isn't it then an issue of WinPR - it doesn't function properly if used through WinPR.

**Comment by akallabeth** [comment]
@weberhofer This is a wrapper function for gethostbyname (or windows equivalent) which has (by definition) the same issues as gethostbyname.

**Comment by weberhofer** [comment]
Thanks for clarifying that! So it's intentionally offering the function for legacy application. I will see that out packaging-system stops worrying about that.
