### ISSUE TITLE
[RDPEA] Implement AAC and MP3 codecs

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#4165]
The sound redirection is missing AAC and MP3 codecs for transport. Only PCM for high quality and low quality compression codecs are implemented curently.

**Comment by metalefty** [comment]
I was going to raise the request. I also willing the feature.

**Comment by hardening** [comment]
I guess https://github.com/FreeRDP/FreeRDP/pull/3827 is related even if the author have not done any feedback from quite a long time.

**Comment by akallabeth** [comment]
@hardening No, that pull is for multimedia redirection only

**Comment by metalefty** [comment]
BTW, please consider also adding ADPCM and Opus because MP3 and AAC are not patent-free. I know some patents on MP3 has been expired but not all.  There's no warranty that LAME doesn't contain patented codes. AFAIK, ADPCM is patent-free. Opus is not patent-free but royalty-free.

See comment on FreeBSD ports.
https://svnweb.freebsd.org/ports/head/audio/lame/Makefile?revision=452032&view=markup#l17
> http://www.mp3licensing.com/ only talks about the FhG and Technicolor patent portfolio
> but there are also portfolios from Sisvel (from Philips) and
> Nokia (from AT&T -> Lucent -> Alcatel).
> Some "old" patents are now expired, but there are more recent MP3 patents. Some
> of the more recent ones are multi-channel related, which is not implemented in LAME.
> There was no investigation (in the LAME project) about which patent exists, which
> one is implemented in LAME, and which one is not (yet) expired. As such it is not
> known if LAME could now be distributed as a binary package or not.
> Linux distributions seem to go the "let's see if get sued" way, FreeBSD doesn't
> follow this.

Regarding ADPCM, [sox](http://sox.sourceforge.net/) is a good library to handle ADPCM. It is included in RHEL package repository. RHEL has very few numbers of multimedia libraries.

I'm planning to add ADPCM to xrdp. See also:
* https://github.com/neutrinolabs/xrdp/pull/833
* https://github.com/neutrinolabs/xrdp/issues/634

Regarding Opus, the priority to introduce Opus codec to FreeRDP will be low because Windows doesn't support Opus neither as RDP server nor as RDP client. xrdp already supports Opus. It is a good royalty-free alternative codec between xrdp and FreeRDP.

I know implementing them all is a hard work but please consider.
