### ISSUE TITLE
Device and Desktop scaling lost on resolution change

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#4324]
```xf_disp_sendLayout``` and ```xf_disp_sendResize``` set the scale factor to a fixed value.
Should take the values from settings.

**Comment by hardening** [comment]
I'm seeing too that using xrandr we have a lot more informations on the physical size of monitors and their orientation.

**Comment by argonym** [comment]
I'm not sure if it's the same issue but since merging the "Dynamic resolution improvements" #4318 (ec027bf) the new /dynamic-resolution feature effectively stopped to work. After connection the window is initially marked as re-sizable, but the first resize attempt seems not to be carried out, instead the resize capabilities get removed from the window.

**Comment by akallabeth** [comment]
@argonym you sure? Open a new issue for that, with detailed description on how to reproduce.
Does work on my test machine quite well, so I'd be very interested in that use case ;)

**Comment by hardening** [comment]
@argonym any details on the command line invocation ?

**Comment by argonym** [comment]
Here you go: #4330
