### ISSUE TITLE
black screen with gfx and suppress output in hardware gdi

### ISSUE THREAD

**Issue by bmiklautz** [FreeRDP/FreeRDP#4371]
When hardware GDI is enabled and gfx used  supress output leads
to a black screen until a update would happen from the server.

Happens on 2.0.0-dev2.

Steps to reproduce:
* run xfreerdp /gdi:hw /gfx 
* switch workspace
* switch back
* as result xfreerdp stays black

**Comment by gh-user-7392** [comment]
Using xfreerdp version 2.0.0-dev2 (b6a1af0) I can confirm this also using the gfx options line:

/gfx +gfx-progressive

I assume because /gdi:hw is the default, this occurs with any other gfx parameters.

As an aside, when switching workspace now or toggling fullscreen (CTRL-ALT-ENTER), the taskbar is now clipped (see attached pic).

![taskbar-clipped](https://user-images.githubusercontent.com/16350618/35122323-6d399b54-fc42-11e7-965a-74214ffda7f5.png)

Please let me know if you want me to start another thread about this, sorry.

**Comment by akallabeth** [comment]
@gh-user-7392 Please open a new one for that with some more details about your setup. (Guess you're using xfce/openbox?)
