### ISSUE TITLE
Memory leaks on resize

### ISSUE THREAD

**Issue by tditsch** [FreeRDP/FreeRDP#4388]
Hi, I get memory leaks when resizing the window multiple times. (using 2.0.0-dev2)

Steps to reproduce:
  - Connect with **xfreerdp /dynamic-resolution /gfx** (tried Server 2012R2 and 2016)
  - resize the window multiple times

On the initial connect it uses around 40MB memory, after about 10 resizes it uses 145MB Memory.
I also tried to profile it with massif, but the memory gets perfectly freed during profiling..

**Comment by hardening** [comment]
ASAN doesn't detect any leak either, perhaps it's some memory that is kept in a pool, and so is released at program termination (but kept unused during program life). Does it ring any bell ?

**Comment by akallabeth** [comment]
@tditsch Does it grow any further or does the memory consumption stay at the value the highest resolution did require?

**Comment by tditsch** [comment]
It grows further even if you resize to a smaller resolution

**Comment by akallabeth** [comment]
@tditsch And the growth does not stop after some time? There are some caches that get filled during the first few minutes like @hardening mentioned.

**Comment by tditsch** [comment]
@akallabeth I just tried it again, it seems to stop after a while (depending on how many resizes I make). 
But I still don't get it why this doesn't happen when I run it with massif (valgrind). 

Is there any way to turn the caching off? I already tried **-bitmap-cache -offscreen-cache**, but that didn't change the memory usage.

**Comment by akallabeth** [comment]
@tditsch No, this is caused by the memory pools used within freerdp. They grow if required but usually don't shrink again (as memory used once during runtime is most likely be required again)
Just to clarify, growing stops after a while or only if you stop resizing?
As for massif/valgrind, there is no leak, just a larger runtime allocation released when the application is quit.

**Comment by tditsch** [comment]
@akallabeth Growing stops once it reaches around 150MB, when I reach that point (after 10-15 resizes) it doesn't grow anymore. So it looks like it doesn't depend on the time but on the number of resizes or amount of memory used.

I was thinking massif shows memory usage generally (not like memcheck only looking for leaks). I checked the memory usage with **ps aux** too when massif was running and the memory usage was totally different:

Resizing from small to big increased memory usage (as expected) and when resizing back to the initial resolution it reduced the memory back to the inital size.
Without massif it grows also when resizing back to the smaller window.
Maybe I just don't understand it, but it seems odd to me.

**Comment by akallabeth** [comment]
@tditsch don't know exactly, but memory profilers do tend to commit changes immediately whereas normal usage tends to release stuff 'when there is time' (they overwrite the C memory allocator with their own version, so that may explain the difference)
Closing this for now as (from your comment) I see no real memory leak here and ~150MB sounds reasonable for normal usage.

**Comment by tditsch** [comment]
@akallabeth ok, thanks for the help and explanation.
