### ISSUE TITLE
Can't send CTRL-ALT-DEL to remote desktop

### ISSUE THREAD

**Issue by dbrandesky** [FreeRDP/FreeRDP#455]
I see that commands like "Alt-F4" have been fixed in the past, but I can't seem to send a ctrl-alt-del to my RDP clients through freerdp. If the RDP window is active the command does seem to be grabbed by that window (Ubuntu doesn't offer me the shutdown dialog box) but the client definitely doesn't receive it; taskmgr doesn't appear in windows XP, and I can't log into my Windows Server 2003 machine because it requires that key sequence at login. I searched around and didn't see anyone else with this issue, so if I missed something obvious please let me know. Thanks!

**Comment by antiflu** [comment]
I'm on Linux Mint and the Ctrl-Alt-Del as well as the Ctrl-Alt-End buttons are taken by the OS as shortcuts. Only after you remove them in Preferences-Keyboard, FreeRDP will pick them up.

**Comment by kefir-** [comment]
This still appears to be an issue on Ubuntu 16.04. It'd be nice if there were some way to define and send special key combos. Most other similar software I've seen have that, like VirtualBox, other VNC clients, and other remote console applications.

**Comment by amtlib-dot-dll** [comment]
It seems that Wayland deliberately forbids global key grabbing due to [keyloggers](https://lists.fedoraproject.org/archives/list/desktop@lists.fedoraproject.org/thread/BBPOOC4GVBJXHLKSSFLGERG6GYAU6M6U/) and this issue may not be fixed in a [long time](https://bugzilla.redhat.com/show_bug.cgi?id=1285770), so I suggest that FreeRDP to provide an extra console receiving commands, for example users can type commands like `send ^~del` to send Ctrl-Alt-Del to the remote computer when `xfreerdp` is launched from a terminal window.
