### ISSUE TITLE
Screen artefacts and disappearing dropdown menus bug are still present [rail plugin]

### ISSUE THREAD

**Issue by yoklmn** [FreeRDP/FreeRDP#4660]
Hello. I use actual nightly version 2.0.0-dev3 (9460f4292) on Ubuntu 18.04 on Gnome Flashback session. Bugs, described here are still present:
https://github.com/FreeRDP/FreeRDP/issues/3997
https://github.com/FreeRDP/FreeRDP/issues/3656

Dropdown menus show briefly and then disappear. only on 10-20 prompts menu displayed, then starts disapear again. Sometimes I see background apps or desktop. I shot the video where shown disapearing menus and on the end of video shown artifact in right bottom corner

[record-16.23.38[17.05.2018].zip](https://github.com/FreeRDP/FreeRDP/files/2013301/record-16.23.38.17.05.2018.zip)

I try run by there commands:
```
/opt/freerdp-nightly/bin/xfreerdp /u:username /p:password /app:"||myprogram" /v:myserver:3389
/opt/freerdp-nightly/bin/xfreerdp /u:username /p:password /app:"||myprogram" /v:myserver:3389 +decorations +clipboard +fonts +window-drag +aero +menu-anims /gdi:hw
/opt/freerdp-nightly/bin/xfreerdp /u:username /p:password /app:"||myprogram" /v:myserver:3389 +decorations +clipboard +fonts +window-drag +aero +menu-anims /gdi:sw
/opt/freerdp-nightly/bin/xfreerdp -u username -p password --app --plugin rail --data "||myprogram" -- myserver:3389

```

**Comment by akallabeth** [comment]
@yoklmn does it work more reliable when adding `/rfx /gfx`?

**Comment by yoklmn** [comment]
If I run with /rfx and /gfx, or only /rfx problem still present. But if run only with /gfx key it work finely, but not enough:

[record-00.09.34[18.05.2018].zip](https://github.com/FreeRDP/FreeRDP/files/2014763/record-00.09.34.18.05.2018.zip)

**Comment by gnshkl1** [comment]
@yoklmn screen recording does not showing any graphics artifacts issue.

**Comment by yoklmn** [comment]
@gnshkl1 artifact shows on 01:04 on the tape. Here is screenshot from that screen recording http://prntscr.com/jqlt6w

**Comment by akallabeth** [comment]
@yoklmn Could you run with `/lob-level:trace` and add the log? Would be interesting which operation is failing there.

**Comment by nornic** [comment]
We hit the same issue today on:
```
$ xfreerdp --version
This is FreeRDP version 2.0.0-rc4 (n/a)
```

Problem exists when you connecting with RemoteApp.
I've tested it on Ubuntu Mate and latest Arch. In all cases, when we try to use right-click, File or any other drop-down menus, they would show up and almost instantly disappear. No chance to click on anything.

The quick patch @mokyle provided actually helps a lot. I can use the remote app without issues and dropdown menus stay on. I don't know the ramifications of hashing out `xf_rail_send_activate` but it would be most welcomed if we could get it fixed this way or another.

I've added the [trace.log](https://github.com/FreeRDP/FreeRDP/files/3091596/trace.log) but I can't see any errors. Only thing in this snippet is highlighting the File menu and clicking on it once. Of course the menu disappeared almost instantly.

Please let me know if you need any more details or how I could help to get this sorted.

Thank you

**Comment by hugleo** [comment]
Same problem here. For now using the @mokyle changes and working ;-)

**Comment by hugleo** [comment]
About the screen artefacts are also present about the changes. 
Currently I'm using kde, and when I move any windows I see the Desktop background (transparent). So what I note for freedrp: After I right click and get a dropbox menu I see the Desktop background (for about 1 second, flickering) instead of remote app background (That what I call screen artefacts ;-))

**Comment by Golovchenko83** [comment]
Такая же проблема есть ли решение. меню при клике либо сразу исчезает либо вообще не открывается.

**Comment by Golovchenko83** [comment]
The same problem is whether there is a solution. the menu disappears immediately or does not open at all when clicked.

**Comment by johndoe7000** [comment]
Hello devs,

this problem is still here with freerdp 2.6.1.
The patch from mokyle still works with 2.6.1 when rebased. I really don't understand, why nobody of you look into this.
RemoteApp support is really bad...

1. Resizing issues.
2. Minimize issues.
3. Sometimes black boxes appear.
4. No XDG MIME support.

Forgive me... I don't know you and do not have insight into your life and the problems you are faced with. Freerdp works great since years for the "full" desktop experience. I wish you would give RemoteApp more love.

**Comment by akallabeth** [comment]
@johndoe7000 well, the fix got lost (don't speak chinese and no pull request was created)

**Comment by unicon221** [comment]
Since this is the thread where the drop-down menu problem was reported (and the maintainer noted back
then that the fix got lost), a pointer for anyone landing here from a search:

I filed the *dialog* half of this separately as **#13420** —
"X11 RemoteApp: dialog window collapses to 1px (window size feedback loop between `WND_SIZE` and
`xf_rail_adjust_position`)" — together with a patch against `3.31.1` that **also contains the menu
workaround discussed in this issue** (stop reporting window activation from the X11 client in
`xf_event_FocusIn()` / `FocusOut()`).

Measured in the same setup (Windows 10 22H2 guest, RemoteApp Notepad, X11 client on a tiling Wayland
compositor):

| | before | after |
|---|---|---|
| drop-down / context menu | flashes, unusable | opens, stays open, submenus work |
| `Help → About` dialog | collapses to 1x330 | natural size 993x847, stable |

Patch and analysis: https://github.com/FreeRDP/FreeRDP/issues/13420
