### ISSUE TITLE
iOS Build Error - Xcode 9.4.1

### ISSUE THREAD

**Issue by rakesh1504** [FreeRDP/FreeRDP#4834]
I downloaded the source then following steps:
1) ./scripts/OpenSSL-DownloadAndBuild.command 
2) cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode

After that when I open the xcode and try to compile it. It gives following error

clang: error: invalid iOS deployment version '-mios-simulator-version-min=11.4', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]

Where I have to set for latest iOS version(11.0)?

Thanks

**Comment by akallabeth** [comment]
@rakesh1504
* You need to build OpenSSL with the correct SDK version and remove architectures no longer supported. (check the script, the variables are at the beginning)
* Check the CMake variables `CMAKE_OSX_ARCHITECTURES` and `CMAKE_OSX_DEPLOYMENT_TARGET` for the freerdp build.

Since we do not test iOS that often, it would be nice if someone using it could write up what has changed (pull request/wiki/...)

hope that helps.

**Comment by akallabeth** [comment]
`iOS` is deprecated as nobody is working on that.
