### ISSUE TITLE
How to execute a batch script that will perform UI tasks

### ISSUE THREAD

**Issue by nkv16786** [FreeRDP/FreeRDP#4986]
Hi,

I have a batch script that perform some UI tasks like opening chorme browser and then opening a page.
I need to execute this script using xfreerdp and also i need this task  of opening of browser and page to be seen in the rdp session.

Currently, is this possible??

**Version** :- 
This is FreeRDP version 1.1.0-beta1

Note:- My batch script accepts page url as argument.

**Comment by bmiklautz** [comment]
While automation is technically possible it won't work out of the box. If xfreerdp needs to do the jobs you would need to do some coding and send the corresponding mouse clicks and inputs you need.

If you just want to open a browser and show a page (and nothing else) you might have a look on how remote apps work. This way you could run the browser as app and if it takes a URL as command line pass it as parameter.

**Comment by bmiklautz** [comment]
And p.s.: For questions please use the mailing list or our irc channel.

**Comment by informatimago** [comment]
nkv16786 Perhaps there is some confusion.  

RDP works mainly at the level of the pixels and low-level events (mouse movements, mouse clics, key presses).  It doesn't know what program or system runs on the remote side, and knows nothing about browsers.
What you seem to be wanting could be attained by an "out-of-band" communication. 
If the remote system was a unix system, it would be a simple matter to use ssh in your script, and assuming firefox as browser, since I don't know chrome:
```
xfreerdp /u:${user} /v:${remote} &
sleep 30
ssh ${user}@${remote} firefox -newtab "${url}"
```
If your remote is a Windows system, then you would have to launch in advance a sshd service there. (I did that with cygwin, there are probably other sshd servers for Windows).  There may be some authentication difficulties to solve, to let the programs from the ssh connection talk to the desktop open by rdp, (in X11 it's simple enough to solve, I don't know anything about Windows, so I can't say there).

In any case, we could image that RDP could help here, to transmit such commands, but unfortunately, it would: 1- be an extension to the protocol, 2- depend on the server, so again, you're back to installing servers on the remote Windows workstations.

Perhaps the best we could do, staying with RDP, is to script the keying of a command, eg. thru the Windows Key which would open the start menu, with the search box for programs, there we could send the keys to launch cmd.exe RET wait a second or two, and send further keys to type the command such as: firefox -newtab http://... RET

Notice that this kind of interaction would be hazardous, since I would assume an application could disable the Windows key to call up the start menu, and other events could intervene in the stream (eg. if the user was typing something), to break everything.

Finally, depending on your exact purposes and environment, a good solution could be for you to write a little Windows service that would listen to network requests from your script (you would have to deal with authentication, thru eg. ssl and managing certificates), and that would run the browser command to open the urls received from your script. This would be an alternative to the installation of a full sshd server on the Windows workstations.

**Comment by nkv16786** [comment]
I have a selenium script to do UI tasks(opening chrome and then a page in it). I just need a way in which i am able to see the tasks that script is performing on the particular rdp session i am starting.
