### ISSUE TITLE
FreeRDP ignores xmodmap settings

### ISSUE THREAD

**Issue by kekekeks** [FreeRDP/FreeRDP#505]
I have keys near arrows (originally they are Back and Next media keys ) remapped to PgUp/PgDown, but FreeRDP seems not to send them to remote side at all (at least a test WinForms application doesn't recieve any key events).

**Comment by heroxbd** [comment]
I am voting for this issue.  Please support sending local X keyboard customizations (by xmodmap) over RDP.

**Comment by marblenix** [comment]
Dear googlers of the future: here's how I got my DasKeyboard to recognize a keymap over xfreerdp (I'm on Arch Linux).

Resources:

* https://bbs.archlinux.org/viewtopic.php?id=177533

* https://bbs.archlinux.org/viewtopic.php?id=170915

* https://wiki.archlinux.org/index.php/Map_scancodes_to_keycodes

* https://ask.fedoraproject.org/en/question/46201/how-to-map-scancodes-to-keycodes/


Steps I took for my machine (YMMV):

* Make sure udev is installed and working

* setkeycodes will not work with usb keyboards, you must use evtest, if you are on a non-usb keyboard [this page may be all you need](http://really.zonky.org/?p=1622). I have not tested this since I no longer have anything but a usb keyboard.

-----

1) Figure out how to reference your keyboard in udev:
  * `lsusb` -> find your keyboard
  * find the text right after "ID", should look something like this:
```
Bus 001 Device 005: ID 04d9:2013 Holtek Semiconductor, Inc. Keyboard [Das Keyboard]
```
  * You want 04d9:2013

2) Figure out the correct keycode of the key you want to replace:
  * Install `evtest` if you don't already have it
  * Run `evtest`, select the input you want to test (mine was 3)
  * Enter the key you want to change (in my case it was caps lock), save this information for later
```
Event: time 1444849017.168133, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70039
Event: time 1444849017.168133, type 1 (EV_KEY), code 58 (KEY_CAPSLOCK), value 0
Event: time 1444849017.168133, -------------- SYN_REPORT ------------
Event: time 1444849017.872162, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70039
Event: time 1444849017.872162, type 1 (EV_KEY), code 58 (KEY_CAPSLOCK), value 1
```
  * You want 70039
  * Enter the key you want to replace the first key with (In my case it was left control)
```
Event: time 1444849019.152181, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e0
Event: time 1444849019.152181, type 1 (EV_KEY), code 29 (KEY_LEFTCTRL), value 1
Event: time 1444849019.152181, -------------- SYN_REPORT ------------
Event: time 1444849019.376152, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e0
Event: time 1444849019.376152, type 1 (EV_KEY), code 29 (KEY_LEFTCTRL), value 0
``` 
  * you want LEFTCTRL (yes, I know, udev is weird)

-----

3) make a *new* file in udev:
  * `sudo vim /etc/udev/hwdb.d/90-caps-to-control.hwdb`
  * put in the following information:
```
evdev:input:*v04D9p2013*
  KEYBOARD_KEY_70039=leftctrl
```
  * where v04D9p2013 references the device id from earlier (any letters from the device id must be in uppercase) and KEYBOARD_KEY_XXXXX must be the key id found earlier and leftctrl is the full name of the key you want to replace it with (any letters must be in downcase, unless you specifically want to replace a key with, say 'Y').

-----

4) Run the following commands:
```
sudo udevadm --debug hwdb --update
sudo udevadm trigger
sudo udevadm info /dev/input/by-path/*-usb-*-kbd | grep KEYBOARD_KEY
```
  * You should see the change you made in the udev file, mine looks like this:
```
E: KEYBOARD_KEY_70039=leftctrl
```

-----

You can further verify this by running `evtest` again and making sure that the changes have been made.

```
Event: time 1444849705.680741, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70039
Event: time 1444849705.680741, type 1 (EV_KEY), code 29 (KEY_LEFTCTRL), value 1
```
  * Note how 70039 now refers to LEFTCTRL instead of CAPSLOCK

**Comment by cizra** [comment]
Here's how I got my Caps Lock to work as Control over FreeRDP:
edit `FreeRDP-2.0.0-rc4/libfreerdp/locale/keyboard_xkbfile.c`
find and edit the line with `evdev 66` to say `{ "CAPS", RDP_SCANCODE_LCONTROL },	// evdev 66`
