### ISSUE TITLE
Clipboard encoding

### ISSUE THREAD

**Issue by nickkolok** [FreeRDP/FreeRDP#5255]
Greetings from Russia, comrads!

Our university library is slowly migrating from Windows to Linux. So, some librarians got PCs with Linux Ubuntu 14.04. However, the main library database interface in running on Windows. So, a script was written, which launches `xfreerdp` with certain arguments, and a window with the library interface appears.

The problemis: when a librarian copies a piece of text from browser or another application running on Linux, it is copied as UTF-8 (or some kind of Unicode). When it is pasted into the application inside FreeRDP, the application displays it as CP1251 or as a sequence like this: `\uXXXX\uXXXX`, where XXXX is the code of Cyrillic symbols. This is very sad, because librarians have to re-type the text from one window to another.

One of the librarian told me about this problem and I want to help. The system administrators (i.e. stuff who has `root` access) said that the problem is unsolvable. However, I managed to write a [userscript for Firefox](https://greasyfork.org/ru/scripts/377737-copy-as-cp1251) which naively converts to CP1251 all the text being copied from web pages. This workaround is working. However, the main problem is still unsolved because the Firefox is not the only application, which the librarians have to copy the text from.

Is there a way to make FreeRDP convert the clipboard from one encoding to another automatically?

I cannot install a new version of FreeRDP, because I have no root access, but I can change the script which launches FreeRDP. However, there is no `+clipboard` option in the script (or In was not careful enough).

If I have to provide any information about FreeRDP or the whole OS, please list the commands which I should run.

Thank you in advance.

P.S. Maybe #3461 is connected.

**Comment by ilammy** [comment]
IIRC, FreeRDP implements remote clipboard for text data in a... funny way. It requests UTF-8 from local applications running on Linux, but then sends the acquired bytes _as is_ to the remote side, without doing any code page conversion whatsoever.

Locally xfreerdp always requests UTF8_STRING and is able to convert into into CF_TEXT, CF_OEMTEXT, CF_UNICODETEXT (whatever requested by the remote application):

https://github.com/FreeRDP/FreeRDP/blob/f0e9c95f44a75900418c06f1ff68bddc76d4c8b9/client/X11/xf_cliprdr.c#L586-L591

However, the CF_TEXT conversion is kinda broken and just assumes the remote encoding to be UTF-8 as well:

https://github.com/FreeRDP/FreeRDP/blob/f0e9c95f44a75900418c06f1ff68bddc76d4c8b9/winpr/libwinpr/clipboard/synthetic.c#L41-L84

That is, it seems to always output UTF-8 after converting UNIX line endings to Windows ones.

The proper fix will involve getting the remote locale somehow so that we know what ANSI encoding to use for CF_TEXT and CF_OEMTEXT. Preferably we'll need a command-line switch to manually override the guess (or if accurate information is not available).

As a workaround you can implement some 'clipboard manager' on the remote side which will fixup the encoding in broken CF_TEXT and CF_OEMTEXT formats. It should be possible to more or less reliably detect UTF-8 encoding in arbitrary byte streams and try decoding and reencoding it into whatever ANSI encoding remote side expects.

However, that's a workaround. The core reason here seems to be a bug in FreeRDP which produces incorrect CF_TEXT and CF_OEMTEXT values.

**Comment by ilammy** [comment]
Another option that may be worth exploring is using CF_LOCALE format. [According to MSDN](https://docs.microsoft.com/en-us/windows/desktop/dataxchg/standard-clipboard-formats), this format may be used to set the encoding for CF_TEXT format. FreeRDP could try setting it to UTF-8 (no idea how) and that may tell the system and the application to interpret the data as UTF-8 instead of CP1251.

**Comment by nickkolok** [comment]
@ilammy, thank you for quick reply!
Now I'll be sure that our administrators didn't forget something easy.

> tell the system and the application to interpret the data as UTF-8 instead of CP1251

I'm not sure if this proprietary thing knows about UTF-8.

Moreover, there is a problem in choosing the way how the bug should be fixed: there are many encodings, not only CP1251. Should there be a separate CLI-switch for each of them? Probably no.

I can suggest a rough, crude way: adding an option to launch an arbitrary shell script every time when the clipboard is requested. This script should get the actual clipboard content to the standart input and produce the content for remote application in its standart output. For example, in our situation it can be
```
iconv -c -t cp1251 -f utf8
```
And, of course, a CLI-switchable script for reverse convertion - when some text is copied from remote app to local.

Another way is to create CLI-switchto specify target and ource encodings and to use an appropriate library for it (`libiconv`?). However, I'm not sure that this is Unix-way.

**Comment by ilammy** [comment]
> I'm not sure if this proprietary thing knows about UTF-8.

Yeah, that's most likely. If it supported Unicode then it'd request CF_UNICODETEXT which should work fine.

I'm no Windows and WinAPI expert, but according to [this doc][1] the system should be able to convert between textual clipboard formats. So maybe FreeRDP could get away by _not using_ CF_TEXT and CF_OEMTEXT at all so that the ball is in Windows' court to perform the necessary conversion. The application requests its 8-bit ANSI code page encoding, FreeRDP provides UTF-8 text, and Windows converts between those two.

[1]: https://docs.microsoft.com/en-us/windows/desktop/dataxchg/clipboard-formats#_win32_Synthesized_Clipboard_Formats

> Another way is to create CLI-switch to specify target and source encodings and to use an appropriate library for it (`libiconv`?)

I like this. Something like `/cliprdr-encoding:UTF-8` on the command-line and libiconv or someting performing the conversion behind the scenes. Ideally, there should be no command-line switch at all, but I'm not sure that the current code page is available over RDP.

Well, that's all technical talk. I guess I'll start by trying to reproduce the issue by denying Unicode formats and seeing how applications react, and then do so with legacy encodings.

If you could build FreeRDP with `WITH_DEBUG_CLIPRDR` option and run it with `WLOG_FILTER=com.freerdp.channels.cliprdr.client:DEBUG` environment variable — that would be enormous help with debugging the issue.

**Comment by akallabeth** [comment]
Sorry, I´m late to the discussion :)
As you already figured out, the application requesting the text is not supporting unicode, so a proper `CF_LOCALE` must be set.
Currently `clipboard_synthesize_cf_locale` is hardcoded and `xf_cliprdr_server_format_data_response` does not handle locale encoding either.
