### ISSUE TITLE
key "c" stops working, key "a" becomes "a-grave" eg., " à ".

### ISSUE THREAD

**Issue by samoring** [FreeRDP/FreeRDP#5389]
OS: openSUSE 15.0 and 15.1 (42.3 isn't affected negatively).

freerdp-2.0.0~rc4-lp150.2.3.1.x86_64.rpm

While using freerdp for a while against a Windows 10 workstation, the "c" key will stop functioning, also the "a" key becomes an "a-grave" character.  Using the /kbd:US switch doesn't have an impact on this observation.

The command being issued is: xfreerdp /v:<workstationdns> /u:<userid> /p:<password> /cert-ignore -sec-nla /multimon /sound /toggle-fullscreen +clipboard +fonts -floatbar /kbd:US

How does one diagnose what's going on to help developers?

**Comment by samoring** [comment]
Local keyboard:

samoring@lenovolappy:~> setxkbmap -print
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+inet(evdev)+terminate(ctrl_alt_bksp)"	};
	xkb_geometry  { include "pc(pc105)"	};
};

**Comment by samoring** [comment]
Currently testing with http://pub.freerdp.com/repositories/rpm/opensuse/sl15.0/freerdp-nightly/x86_64/ from May 7.

**Comment by akallabeth** [comment]
Interesting, I've never managed to reproduce something like this.
Which WM are you using?
X11 or wayland session?

**Comment by samoring** [comment]
openSUSE 15.0 uses wayland. I've not been able to recreate this using the older package on openSUSE 42.3.  One piece of information in recreating this symptom was provided to me today.  Issuing CTRL+ALT+ENTER then doing something on the host and going back to the remotely controlled windows machine (click the window, then CTRL+ALT+ENTER) creates this symptom reliably.

**Comment by samoring** [comment]
Sharing this observation in the event that it helps someone else behind me.  If we turn on +floatbar and use the minimize to go to the host machine, then go back to the guest that we're remotely controlling rather than issuing CTRL+ALT+ENTER, we do not see this behavior.  We do not lose keyboard or mouse scrolling button using +floatbar as do if we use CTRL+ALT+ENTER then go back.

Whats interesting, at least to me, is that -floatbar is the default in openSUSE 42.0, but +floatbar is the default in openSUSE 15.0.

**Comment by fourjay** [comment]
FWIW I'm seeing the same symptoms (also on leap 15). I'm using the suse package of freerdp version (but that's RC4).

**Comment by samoring** [comment]
> FWIW I'm seeing the same symptoms (also on leap 15). I'm using the suse package of freerdp version (but that's RC4).

I'm curious if you see the issue while the floatbar is present, also if this only happens when you have more than one monitor.

**Comment by Ionic** [comment]
I am also seeing "a bit" of this, but not all of it (most importantly the a-grave thing).

For me, a workaround is forcing refocussing by moving the mouse cursor into the session again (which fixes the issue temporarily while the mouse cursor is within the session window) or clicking into the RDP session window.

This happens quite often to me because I use Ctrl-Alt-Cursor Keys to switch between workspaces. Doing this only works while my mouse cursor is NOT inside the RDP session window, so I typically keep it off the session window. Keyboard input is still making it to the session as long as I don't focus another window, which is fine. However, if I move around my workspaces, "Ctrl-Alt" will get stuck within the session and once I get back to the workspace with the RDP session open, I usually can enter text normally, but pressing enter will trigger fullscreen mode. Not a big deal, since switching back using Cltr-Alt-Enter is easy enough and will get rid of the "stuck modifier keys" situation as well. However, the focus will halfway switch to the window that is ordered right before the RDP session *if* the mouse cursor is not placed within the session, with odd side effects. Pressing most keys makes it to the RDP session, but "c" for instance will go to the other window. Moving the mouse cursor into the session window, every key press makes it to the session just as should be. Forcing a refocus by clicking into the RDP session or switching to windows will make that problem go away - i.e., after that, the mouse cursor can be moved out of the session window, but text entered still completely makes it into the session.

Note that I do not use a focus-follows-mouse feature.

**Comment by Ionic** [comment]
I also think that this issue, #5342 and #4966 (and maybe others) are at least closely related, if not duplicates.

**Comment by Kreijstal** [comment]
I had this happen to me once, I exited and restarted it again, it was fixed, weird bug indeed.
