### ISSUE TITLE
Unable to connect to an existing user session on the latest Windows

### ISSUE THREAD

**Issue by yoonjm** [FreeRDP/FreeRDP#5548]
**Describe the bug**
As long as a user is signed in (regardless of the session being in the disconnected or connected state), FreeRDP client is unable to connect to the user session. In order for FreeRDP client to connect, the user must be signed out.

Unable to reproduce on Windows 10 Version 1809 Build 17763.437.
Able to reproduce 100% on Windows 10 Version 1903 Build 18362.295.
(These are OS versions that I've attempted to connect to)

**To Reproduce**
1. Use mstsc to connect to a user session
2. Disconnect from RDP (do NOT sign out)
3. Use FreeRDP client to connect to the same user session
4. See error (black screen)
(Steps to get around the problem: if you sign the user out in step 2, then you will get the user session in step 3.)

**Expected behavior**
Get the user session and be able to use the remote desktop.

**Screenshots**
Just a black screen.

** Application details
* Version of FreeRDP
tried with the stable-1.1 build and the nightly build from 8/24/2019 (build 657)
* Command line used
wfreerdp.exe /u:username /p:password /v:ipaddress
* output of `/buildconfig`
N/A
* OS version connecting to
Windows 10 Version 1903 Build 18362.295 (server machine)
* If available the log output from a run with `/log-level:trace` 
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 1809 Build 17763.437 (client machine)

**Comment by akallabeth** [comment]
Does this work if you use ms rdp client (mstsc)?
If it does, please create a log (wfreerdp.exe /v:... >log.txt 2>&1)

**Comment by akallabeth** [comment]
Ok, did the certificate change?
Did you use /cert-ignore? If not there is a certificate problem.

**Comment by akallabeth** [comment]
Sorry, did miss the last line in you logs, so certificate is not the issue.
So,
* checked the specs, no changes there.
* From your description the authentication succeeds (you see something) so this may very well be a buggy windows update. Hard to tell at this point :/
Anything suspicious in the server side logs?

**Comment by akallabeth** [comment]
Oh, and one additional thought (or wild guess;)):
* MSTSC nowadays preferres GFX, so could you try with `/gfx /rfx /network:auto` and check if that changes something?

**Comment by akallabeth** [comment]
@yoonjm you could try `/gfx:avc444` (but you need a custom compile with openh264, current nightly has some issued due to mediafoundation support is buggy)

Sadly, from the looks of it this is a server side issue and we can only try to use the same settings that work with mstsc in this case (nothing we can really fix - just wait for the next iteration of the patch that broke this :/)

for debugging you can try and build freerdp shadow(or sample) server with capability debugging enabled and connect with mstsc to that and then do the same with freerdp to get the differences in capabilities announced

**Comment by jacksondk** [comment]
I have seen the exact same behavior using wfreerdp.exe with a Win10 1903 target. It also had the crash files with similar constent to the one that @yoonjm posted.

**Comment by DouglasHeriot** [comment]
I have exactly the same issue running Guacamole/guacd 1.0.0 connecting to Windows 10 Pro 1903 machines. The same setup connects fine to older versions of Windows.

What can I do to help track down the cause of this bug? We really need to work out a solution.

**Comment by yoonjm** [comment]
You could try what @akallabeth suggested to find the right setting to bypass the problem since it's still working for mstsc.

> for debugging you can try and build freerdp shadow(or sample) server with capability debugging enabled and connect with mstsc to that and then do the same with freerdp to get the differences in capabilities announced

**Comment by akallabeth** [comment]
Ok, here some update:
* Tried today with a naked windows 10 1903 professional x64
* Only activated RDP access `System/Remote settings/` with `Allow remote connections to this computer`
* Connections are working!

So, I assume you have some policy in place that is incompatible with freerdp or something other hidden?
Could you post your policy from `gpedit.msc` `Computer Configuration/Administrative Templates/Windows   Components/Remote Desktop Services/Remote Desktop Session Host` as well as the configuration of your os (standalone/active    directory/...)?

**Comment by DouglasHeriot** [comment]
* All Windows systems I've tried have been standalone (no domains involved), VMs installed on an ESXI cluster.
* I'm trying against a mostly-clean Windows 10 install I did earlier this week. I created it as a template in VMWare with just a couple of things configured (WinRM for Ansible to connect later, bloatware apps removed)
* I don't have any group policy configured – `gpedit.msc` shows everything under that `Remote Desktop Session Host` as "Not configured"
* I tried running `freerdp-shadow-cli` on an Ubuntu 1804 VM, but it just sefaults on start in `RSA_generate_key_ex` like #4094. Not sure yet if it's because Ubuntu has an old package, or something else.

I've also just now tested connecting to a physical laptop running Windows 1903. And it works! So you're right – it's not as simple as this issue is with 1903. There's got to be some setting that's doing it…

**Comment by akallabeth** [comment]
@DouglasHeriot I´d try with `xfreerdp` to connect to a server, `freerdp-shadow-cli` is for mirroring the local session via RDP ;) (X11 only)

**Comment by akallabeth** [comment]
@DouglasHeriot and yes, the package in ubuntu might be a bit outdated.

**Comment by yoonjm** [comment]
@akallabeth Could you confirm the build OS of the remote server you are connecting to? I think this issue occurs on specific sub-versions of Windows 10 Version 1903. The remote server that I had this problem on is build OS 18362.295.

**Comment by DouglasHeriot** [comment]
@yoonjm hmm, that's weird. I've just tested that I have machines running 1903 18362.295 and they work fine. But when upgrading to 1903 18362.329 they stop working (that's update KB4512941)

There seems to be an issue with CPU usage in that happens when disconnecting RDP. Disabling WDDM does indeed fix the CPU usage issue, but does not fix the FreeRDP freezing issue. I think the CPU Usage issue is what causes the host console to lock up for a little while after RDP disconnect.
https://borncity.com/win/2019/08/28/windows-10-v1903-rdp-dwm-exe-causes-high-cpu-load-freezes-vms/

**Comment by DouglasHeriot** [comment]
I just did a clean install of Windows 10 1903 ISO from Microsoft. Literally all I did was install VMWare tools, and turn on "Allow remote connections to this computer" in System Properties. It's running 1903 18362.30. 
FreeRDP still doesn't work. Using `wfreerdp.exe`, it authenticates, connects, displays the desktop then about a second later `wfreerdp.exe` closes itself. I'm running a nightly build from Jenkins on 5/9/2019.

On the other hand, I've got a physical Surface Pro running the latest 1903 18362.329 and `wfreerdp.exe` works just fine.

So I'm thinking maybe it's something related to the combination of VMWare and 1903?

**Comment by yoonjm** [comment]
Thank you @DouglasHeriot ! Disabling WDDM for RDP in Group Policy worked for me, and I am able to successfully connect to my remote host.

With regards to your latest comment about VMWare vs. Surface Pro, from reading this article (https://borncity.com/win/2019/07/12/windows-10-v1903-remote-desktop-shows-black-screen/), it looks like the root cause is an old display driver. It may be that your Surface Pro has a display driver that is "new enough" while your VMWare doesn't.

It's interesting how disabling WDDM resolves the CPU issue but not the freezing issue for you. From what I read, high CPU consumption is the cause of VM freezes when not enough cores are allocated. I actually upgraded my remote host from 18362.295 to 18362.329, and they behave the same way (both work with the workaround of disabling WDDM and both fail without the workaround).

**Comment by akallabeth** [comment]
So this seems to be a virtualisation issue (the machine I´ve tried was virtualized with KVM, so it seems specific to some implementations only)
Could you test the following settings:
`Administrative Templates -> Windows Compnents -> Remote Desktop Services -> Remote Desktop Session Host`

1. `Use WDDM graphics display driver for Remote Desktop Connections -> Disable`
2. `Use hardware graphics adapters for all Remote Desktop Services sessions -> Disable`

**Comment by akallabeth** [comment]
@yoonjm Ok, looks like you beat me (silly page refresh missing)

**Comment by DouglasHeriot** [comment]
I think my mistake was I had "Allow connections only from computer running Remote Desktop with Network Level Authentication" turned on still. This has a somewhat similar result where the connection started successfully, and then quits after a few seconds (like a crash instead of just freezing though)

You are right - when I set the GPO "Use WDDM graphics display driver for Remote Desktop Connections -> Disable" it does fix the CPU issue and the freezing issue.

I was further confused while going through our company internal firewall to get between VRFs from my workstation to VMware host - this is also causing TCP connections to start at first and then fail after a few seconds (still trying to track down that separate issue with the firewall...)

So, I think I'm all good now! I'll just leave WDDM disabled until Microsoft comes out with a fix I guess.

**Comment by destroy-everything** [comment]
I tried every variation of settings on my client , Glyhs , different video installed and built from git, all to no avail, just stuck on please wait screen. I switched to KRDC and it works so no more freerdp for now. https://apps.kde.org/krdc/

**Comment by akallabeth** [comment]
@destroy-everything funny, `krdc` uses `xfreerdp` as RDP client internally
