### ISSUE TITLE
No USB passtrough to Windows Terminalserver 2016

### ISSUE THREAD

**Issue by HyperShake** [FreeRDP/FreeRDP#5565]
Hello guys,
I recently installed a ThinClient HP t430 with all the newest patches available (July, 21st)
The TC identified all USB Devices (Mouse, Keyboard, Smartcardreader,USB-Storage) and I allowed all devices to be able to passthrough to a Terminalsession.
When I connect to the Terminalserver via FreeRDP everything works except the passthrough of the USB Devices.
When I connect to the Termialsession via  Windows RemoteDesktop everything works fine.
Does the FreeRDP not Support USB-Passthrough or am I missing a Setting?

**Comment by akallabeth** [comment]
For questions please use our mailing list.
(Some details here: https://github.com/FreeRDP/FreeRDP/wiki/BugReporting)

Since you did not provide enough information the question can not be answered (or only partly).
There are certain USB devices that are not allowed to be redirected as USB devices (HID, MASS STORAGE, ...) but all normal devices should work.
