### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [FreeRDP/FreeRDP#5608]
I think that it would be good to flush currently committed changes and make new final release :)

**Comment by fxcoudert** [comment]
On 2019-12-31, OpenSSL 1.0 will become unsupported, with not even security fixes. This means distros, such as Homebrew for macOS, will stop shipping it.

FreeRDP's latest version (1.0.2) does not support OpenSSL 1.1, so we would like to request a release be made before 2019-12-31. Otherwise, we will have to remove FreeRDP from Homebrew, and it has a large number of users (we count 635 installs per month).

**Comment by akallabeth** [comment]
@fxcoudert there are already the `2.0.0-rc` releases, might be a good idea to check these.

**Comment by fxcoudert** [comment]
Homebrew only ships stable releases, not alpha, beta, or release candidates.

**Comment by kloczek** [comment]
Do you still have something on outstanding list before make new release?

**Comment by akallabeth** [comment]
@kloczek not much, mostly testing (and time enough to make a proper release)

**Comment by Neustradamus** [comment]
Any news since 20 November 2018?
More one year?

**Comment by joakim-tjernlund** [comment]
A new RC would be appreciated as current freerdp is not ABI compatible with rc4, remmina suffers from this.

**Comment by bmiklautz** [comment]
https://github.com/FreeRDP/FreeRDP/releases/tag/2.0.0

**Comment by Neustradamus** [comment]
Thanks @bmiklautz!
