### ISSUE TITLE
H264 hardware decoding doesn't work with AVC420 (only with AVC444)

### ISSUE THREAD

**Issue by vscfreire** [FreeRDP/FreeRDP#5861]
**Description**
H264 hardware decoding doesn't work with AVC420, only with AVC444.

**To Reproduce**
1. Connect to a server with AVC support using the /AVC444 switch.
2. With the respective GPU utilities, validate that your graphic card is being used for video decoding.
3. Now connect with /AVC420. Using the same utilities you will see that no video decoding is occurring in your GPU.

**Application details:**
* Based on tree e4a2287f4dc1cfdda98ed778ab056746ef96ddf9, with VAAPI support compiled in.
* Windows Server 2016

**Desktop:**
 - OS: Linux

**Additional context**
It looks like when we use AVC420, the hw decoding pipeline isn't used.

**Comment by akallabeth** [comment]
Thanks for testing, but I´m afraid you fell for a trap.
1. AVC444/AVC420 is just a suggestion by the client and the server decides what is actually used. (check with debug logging which codec is really in use)
Recent windows versions have AVC420 deactivated due to certain issues in the format itself.

1. As for FreeRDP, both, AVC444 and AVC420 use the SAME h264 decoder so it is impossible that one uses it and the other does not. (AVC444 is a funny format decoding 2 AVC420 frames to one AVC444 frame)

**Comment by vscfreire** [comment]
@akallabeth Interesting, thanks for the clarification. So, what codec does freerdp use when we specify the /AVC420 switch?
