### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by the-spyke** [FreeRDP/FreeRDP#6044]
**Is your feature request related to a problem? Please describe.**

1. Improved discoverability of the project by users from [SnapStore](https://snapcraft.io/store)
2. One click installation without deps
3. Ability to easy track/switch between stable/beta/nightly
4. Ability to install stable/nightly simultaneously
5. Single package supported by 21 Linux distributions
6. Sandboxed app is secure for users.

**Describe the solution you'd like**

Please add a Snap package for FreeRDP.

**Describe alternatives you've considered**

Support for FlatPack is welcomed too.

**Additional context**

**Comment by brlin-tw** [comment]
An advantage for using snap is that it allows exposing the `xfreerdp` command directly to the system, one can call it natively instead of `flatpak run com.freerdp.FreeRDP`

**Comment by joezhouchenye** [comment]
Flatpak is bad. It messes up with my computer's Nvidia driver especially if I have CUDA toolkit installed.

**Comment by akallabeth** [comment]
I´m maintaining a [flatpak](https://github.com/flathub/com.freerdp.FreeRDP) and that is (beside the nightly builds) so far our only package provided.
from my experience with snap that is too much of a hassle to keep up to date, so no interest in maintaining such an extra just for unbuntu (forget snap on other distros, just does not work well)
since there has not been any activity for a year now I´m closing this.
