### ISSUE TITLE
Possible bugs found by Sonarcloud and Cppcheck

### ISSUE THREAD

**Issue by qarmin** [FreeRDP/FreeRDP#6085]
**Describe the bug**
For more check
- Sonarcloud - https://sonarcloud.io/project/issues?id=qarmin_freerdp&languages=c%2Cjava%2Cpy&resolved=false&types=BUG
- Cppcheck - https://gitlab.com/qarmin/freerdp/-/jobs/507872182/artifacts/download

Duplicated switch cases
https://github.com/FreeRDP/FreeRDP/blob/032574cc8f16eb01b84bde4e50fd405bd9971371/client/X11/xf_floatbar.c#L431-L445

[Java] Strings should be compared with equals() instead ==
https://github.com/FreeRDP/FreeRDP/blob/02614cce49ce6ff120a1306962c5d3ff6b05ea75/client/Android/Studio/freeRDPCore/src/main/java/com/freerdp/freerdpcore/presentation/HomeActivity.java#L116

Issuer and subject have changed positions with each others 

https://github.com/FreeRDP/FreeRDP/blob/6ac1b6d78e844fb1f0bf91e3664766664dd167d7/libfreerdp/crypto/crypto.c#L869
https://github.com/FreeRDP/FreeRDP/blob/71feb974ac9854a6df390ed17715080f12dd1ad0/libfreerdp/crypto/certificate.c#L679-L680
**Application details**
* Version of FreeRDP - Master GIT

**Comment by akallabeth** [comment]
@qarmin thank you for the report.
Only your second claim is actually an issue (the java string compare).
The duplicate switch is intentional (could also be fall through)

The last one (mixup of arguments) is ugly but has no impact. Changing it now would invalidate all stored host information (again), so we will keep it.
