### ISSUE TITLE
Remote App RDP Session Disconnection Issue on RemoteApp Window Open/Close

### ISSUE THREAD

**Issue by sarathy365** [FreeRDP/FreeRDP#6371]
Remote App RDP Session Disconnection Issue on RemoteApp Window Open/Close/Resize

RDP with remote app session is successfull.
But, in that session if a new window is opened or resized or a window is closed, the rdp connection itself gets disconnected.

I want to know whether anybody else facing the same issue & Is there anyway to fix that?

**Comment by fpauser** [comment]
Others have the same problem, see for example: https://bugzilla.redhat.com/show_bug.cgi?id=1855226

**Comment by giox069** [comment]
If you see the error ```Invalid bmf 129``` in the debug output, then it hass been fixed with commit ce1a9d8d1969ecbb4d24b9f4812654638a44abc2. This commit/fix is only available on the master branch, and candidate to be backported to stable-2.0 branch for the nex stable version.

Another interesting fix for windows 2008 R2/win7 is commit 9f7e475c1652c2b1e30e0406ec0bc7ea3f2330ff just merged in master branch and candidate to be backported to stable-2.0 too.

**Comment by akallabeth** [comment]
Ok, the referenced commit was backported to 2.2.0, so closing this.
