### ISSUE TITLE
/cert:ignore and /cert:tofu seams to be ignored

### ISSUE THREAD

**Issue by cork** [FreeRDP/FreeRDP#6443]
Connecting to several freerdp servers over ssh with proxyjumps so connecting on localhost with the same port.

`ssh -J proxy1:port,proxy2:port  -L3489:server:3389 landserver`

`xfreerdp /cert:ignore localhost:3489`
`xfreerdp /cert:tofu localhost:3489`

both still show certificate accept prompt or `!!!Certificate for localhost:3489 (RDP-Server) has changed!!!`

multiple entries for `localhost 3489` only keeps the last entry in `.config/freerdp/known_hosts2`.

only way to get it to work that i've found is to shuffle around known_hosts2 files in `.config/freerdp/`
`cp ~/.config/freerdp/known_hosts2.server3 ~/.config/freerdp/known_hosts2`

**Comment by akallabeth** [comment]
@cork sorry, but you should simply update `xfreerdp` ;)
The message indicates a version many years old and current releases do not have such an issue.

**Comment by cork** [comment]
This was with freerdp 2.2.0 on the client side. The server is the default version on ubuntu didn't check it's version.

**Comment by akallabeth** [comment]
@cork just tested with `2.2.0` and it ignores `known_hosts2` completely with `/cert:ignore`.
The message you posted also is not used anywhere since a couple of years, so this was definitely no `2.2.0` you tested with.
(check yourself, `client_cli_verify_changed_certificate` is not used anywhere in the code, it has been replaced by `client_cli_verify_changed_certificate_ex`)

**Comment by cork** [comment]
I'm using the default package in archlinux, but its fine the workaround works.
