### ISSUE TITLE
Render dropped frames

### ISSUE THREAD

**Issue by shh230** [FreeRDP/FreeRDP#6691]
Releated pull request for master: 

```
xfreerdp /v:ip /cert:ignore /u:username /p:****** /size:1920x1080 /sound:latency:60,quality:9 -grab-keyboard +async-update +async-input +async-channels /audio-mode:0 /gdi:hw -offscreen-cache -fast-path +compression /video /codec-cache:rfx /dynamic-resolution /admin
```

As video. Interface rendering abnormal.

https://user-images.githubusercontent.com/38716757/103125479-26999380-46c6-11eb-98f9-6cc91aac121e.mov

**Comment by pnowack** [comment]
Not sure what you mean with "Render dropped frames", but why do you disable the FastPath?  
Framerate controlling can only be done with GFX as far as I know, since only under GFX clients can acknowledge frames with the frame_acknowledge_pdu (which the server can process to control the framerate and not flood the client with too many frames).

The only option for proper performance you need is `/network:auto`, you can drop the other ones (especially the part where you disable the FastPath).

**Comment by akallabeth** [comment]
Only thing I can see in this scenario is that the bitmap move is too slow and visible (the split second duplicate browser window)
You might just use `/network:auto` with a h264 enabled build to get better results.
and just like @pnowack mentioned, drop the ricer options `-offscreen-cache -fast-path +compression  /codec-cache:rfx +async-update +async-input +async-channels`
I´m also pretty sure you don´t want `/admin` unless you just adiminster the server and don´t require performance...
`/gdi:hw` might speed things up a little bit, but be aware that it can result in graphical glitches, so best always check with`/gdi:sw` first and only use it if it is not sufficient.
And last, `/sound` and `/audio-mode:0 ` are pretty much the same thing, you can also drop the ricer options on these and simply use one of the options
