### ISSUE TITLE
[Regression] Connections without credentials

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#7108]
Sometime after [V2.3.2](https://github.com/FreeRDP/FreeRDP/releases/tag/2.3.2) the behavior of the [Authenticate callback](https://github.com/FreeRDP/FreeRDP/blob/master/include/freerdp/freerdp.h#L370) changed.

While previously (including in V2.3.2) it wasn't called for connections that don't require username/domain/password (2003 Server with RDP security for instance) it is now called always, even for non-NLA connections.

I haven't looked into when this was introduced but it definitely causes issues with users who have hosts where no authentication is required to reach the login screen.

To work around the issue, those users now have to specify an empty set of credentials during the connection phase. While this works, it's irritating and the previous behavior is obviously more intuitive.

Can this be reverted to the previous behavior?

**Comment by mfleisz** [comment]
The reason why the authenticate callback is now called is that a client might wants to allow the user to enter/store his credentials even for non-NLA connections. I.e. mstsc also asks the user for his credentials when you are connecting with TLS.

In order to restore the old behavior you can simply add the following code in your client's auth callback (unfortunately the `#define`s for `SelectedProtocol` are not yet exposed by the FreeRDP API - 2 means `PROTOCOL_HYBRID`):

```
// Return if a non-NLA connection is established
if (freerdp_settings_get_uint32(settings, FreeRDP_SelectedProtocol) < 2)
    return TRUE;
```

Hope that helps!

**Comment by lemonmojo** [comment]
@mfleisz Thx for getting back to me and explaining the change.
Your proposed solution would definitely work but I'm not sure if this is the best way to handle it.

Wouldn't it make more sense to somehow tell the consumer of the `Authenticate` callback why it's called? Previously it was clear that it was called because the provided set of credentials didn't work. Now, it might also be called if no authentication was attempted just because username/pw are empty. I'm thinking something along the lines of an `AuthenticationReason` enum.

Alternatively, I would even prefer a separate setting to signal to FreeRDP that I want the library to not prompt if empty credentials are provided. There already is a [`PromptForCredentials`](https://github.com/FreeRDP/FreeRDP/blob/master/include/freerdp/settings.h#L1159) flag which doesn't appear to be used apart from writing to .rdp files. I haven't heard about that .rdp file setting before, maybe you can educate me as to what it does in Microsoft's clients?
Anyway, while looking through the settings struct I was expecting this to somehow trigger the new behavior but it's off by default.
Could this be used to control the behavior of the `Authenticate` callback. So by default `PromptForCredentials` would be on and prompt the user for credentials if none have been provided and when it's off, `Authenticate` wouldn't be called for cases where no credentials have been provided but obviously it would still be called when NLA is on and auth failed.

**Comment by mfleisz** [comment]
I don't think `PromptForCredentials` is the right setting/flag to use for this purpose. According to https://www.donkz.nl/overview-rdp-file-settings/ it is used as an override to ask for a password even if there is a previously stored password available.

We can add a new setting that simply disables the `Authenticate` callback for non-NLA connections if set?

**Comment by lemonmojo** [comment]
@mfleisz Sure, a new setting would also do the trick. Something like `AllowEmptyCredentials`?

**Comment by mfleisz** [comment]
@lemonmojo Sounds good 👍

**Comment by igh-gr** [comment]
Is there any updates on this ? 
I want to use the xrdp login window to connect to a server because I have multiple users that want to connect.

I don't know their passwords, so I can't just leave them in a file to read.

I also create a desktop file for them to connect. So they have no prompt to enter a password. Giving an empty password (hardcoded /p: ) then fails login and they have to press back to get to the login window. That works ofcourse, but seems rather tedious.

I can make it work by modifying the function utils_authenticate() in libfreerdp/core/utils.c.
If I return a AUTH_SKIP for case AUTH_RDP and case AUTH_TLS I don't get asked for a password. It still works when I supply a password though. 

I really want to use prebuilds, but since the TLS and RDP connection always wants a password I have to compile FreeRDP each time.

**Comment by akallabeth** [comment]
if you know that you will not use `NLA` just append `/sec:tls` (or `-sec-nla`) and you no longer need a password and get to the login screen.
Tested on debian 11 with `xfreerdp /v:<server> /u:someusername -sec-nla` and you get prefilled username on the login screen without any password prompt

**Comment by igh-gr** [comment]
Sadly this does not work when connecting to a xrdp server. When connecting to a windows server this works fine though.
I think the fault is probably on the server side because of this. Thank you for your answer!
