### ISSUE TITLE
Multimon / Multiple Monitors in wlfreerdp

### ISSUE THREAD

**Issue by kayfoe** [FreeRDP/FreeRDP#7181]
Releated pull request for master: 
It is not possible to create a RDP-Session with more than 1 monitor with waylands wlfreerdp.
No matter what system i use and what configuration of parameters i use i only have one single monitor.
For example i tested it with the latest Ubuntu and it detects both monitors but it still does not use the secondary monitor in the RDP-Session.

**Comment by cmidkiff87** [comment]
I've been doing some research regarding implementing this myself.  
It appears that wayland doesn't provide *direct* support for this.  The wayland [set fullscreen protocol](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_fullscreen:arg:output) only allows for specifying one output (monitor) for the client requesting fullscreen.  

However, [it can be emulated using multiple wayland clients / windows](https://doc.qt.io/qt-6/qtwaylandcompositor-spanning-screens-example.html), one for each output / monitor

Having one wayland client per remote screen also allows for some neat possibilities such as minimizing one rdp screen, leaving the rest open

The other approach is to have 1 wayland client that is not fullscreened, but maximized across all displays (I don't like this approach)

**Comment by cmidkiff87** [comment]
Ok, so it turns out, I'm an idiot, and the XWayland solution works fine (for me).  I was having an issue with KDE Plasma stealing hotkeys / global shortcuts such as `alt + tab` when running xfreerdp from Wayland.

It turns out, you can have plasma disable global shortcuts when you have certain windows focused:
[Instructions originally found here](https://askubuntu.com/questions/1286400/how-do-i-disable-global-keyboard-shortcuts-for-a-specific-application)
> In KDE you can do this using "Window Rules".
> 
> - Open System Settings.
> 
>   - Navigate to Window Management > Window Rules.
> 
>   - (Alternatively, you can search for and launch "Window Rules" directly from the Application launcher.)
> 
>   - Click "New..." to create a new window rule.
> 
>   - On the "Window Matching" tab, you will set the conditions for your window rule:
>        - Give your rule an easy to remember name under "Description".
>        - Next to "Window class (application)", change the drop down to "Exact Match" and set the value of the adjacent field to `xfreerdp`.
>        - Under "Window types", make sure that "Normal Window" is selected.
> 
>   - Switch to the "Appearance and Fixes" tab:
>        - Select "Ignore global shortcuts".
>        - In the adjacent fields, change the drop down to "Force" and set the radio button to "Yes".
> 
>   - Click "OK" to save the new rule and click "Apply" to apply the new rule.

---

I'll still work on this feature, but it's less pressing for me currently

**Comment by dln949** [comment]
Is this still a problem that wlfreerdp cannot handle displaying on multiple monitors on the client?  I ask because I have a fresh installation of Ubuntu 22.04 (wayland), and using wlfreerdp, no matter the settings I select, the display appears on only one monitor.  But I don't know if the problem is with wlfreerdp, or if I am doing something wrong.....  (I tried Remmina, the problem with that is that it insists on using ALL the monitors.  That won't work for me.)

**Comment by cmidkiff87** [comment]
@dln949 from the little I've looked into it, and from the [related Remmina bug](https://gitlab.com/Remmina/Remmina/-/issues/2686), the issue has to do with Wayland itself.  Unlike X11, Wayland doesn't provide a native way to bind a single "surface" (or window) to multiple "displays" (or monitors).  

There might be a way to fake multi-mon support by opening a window per monitor.  But from what I've looked into it, Wayland's protocols only allow for one surface to have fullscreen status at a time.  It might be possible to work around that, but sadly I don't have the experience with C, X11, Wayland, nor freerdp to figure this out

**Comment by mattvarghese** [comment]
I am also running into this (or I think this) issue on Ubuntu-MATE 24.04 (and I think I hit this on 23.10 too)

I have 3 monitors with three different resolutions 4k, 1440p, and 1080p, and so I have them in what I call a butterfly configuration.
![image](https://github.com/FreeRDP/FreeRDP/assets/16229800/b3569910-4f08-4963-a825-0e8a1676a38f)

When I do "xfreerdp /u:... /v:... /f /multimon", it ends up making a giant canvas that overlays a rectangle spanning the longest width and the greatest height so that I end up with three non-displayable areas of this canvas against my screens - as my monitors don't form a perfect rectangle. Specifying monitors:0,1,2 doesn't help either. 

Is it the same issue, or am I just unaware of some other options I could pass to xfreerdp?
