### ISSUE TITLE
Pen remoting feature

### ISSUE THREAD

**Issue by myjimmy** [FreeRDP/FreeRDP#7260]
Hello, everyone

I hope FreeRDP to be a powerful tool for remote desktops.

I found the fact that the FreeRDP doesn't support the pen remoting feature.
When using the Remote Desktop Connection client (mstsc.exe), I am able to use the pen remoting feature in the RDS as in the local computer.
https://techcommunity.microsoft.com/t5/security-compliance-and-identity/introducing-pen-remoting-for-windows-10-and-windows-server-2016/ba-p/249299

I tested the pen remoting feature with the mstsc.exe and the latest wfreerdp.exe in the following environment:
- My OS: Windows 10 Pro Version 20H2 (OS Build 19042.985)
- RDS OS: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1817)

When connecting with the mstsc.exe, not only the cursor movement, clicking but also the pen pressure works very well.
![image](https://user-images.githubusercontent.com/52309150/131335193-2ab1babc-7065-4cfd-8607-66d21ef52b0b.png)

But, only the cursor movement and clicking works with the FreeRDP.
I downloaded the latest [wfreerdp.exe](https://ci.freerdp.com/job/freerdp-nightly-windows/lastBuild/arch=win64,label=vs2013/artifact/build/Release/wfreerdp.exe) (Build win64,vs2013, Aug 28, 2021, 2:45:07 AM) and tested it.
The pointer of the pen appears as the mouse pointer and especially, the pen pressure doesn't work.
Also, the line drawing isn't smooth, as well.
![image](https://user-images.githubusercontent.com/52309150/131335874-3ffa02ba-ce2e-446b-b93b-ae2642f2f9a9.png)

I think that the FreeRDP can support this feature because the mstsc.exe supports it.
Thanks.

**Comment by hardening** [comment]
Yes we could support that but in the current state we don't handle pens at all in any client.

**Comment by myjimmy** [comment]
@hardening Thanks for your reply.
I have one question.

What is (are) the RDP specification(s) for the pen remoting feature?
That's, I'd like to know the title of the main RDP specifications needed to implement this feature.

For example:
- [MS-RDPEGDI]: Remote Desktop Protocol: Graphics Device Interface (GDI) Acceleration Extensions
- [MS-RDPEI]: Remote Desktop Protocol: Input Virtual Channel Extension

Thanks.

**Comment by hardening** [comment]
@myjimmy well MS-RDPEI has been updated for pens, we have multitouch implemented in FreeRDP (so based on MS-RDPEI), but we have not done the work to implement the last version of the specification. 
(BTW I don't think MS-RDPEGDI talks of pens as input devices)

**Comment by akallabeth** [comment]
@myjimmy FreeRDP `rdpei` channel already supports the current RDP standard for pen redirection.
What is missing is the glue code to `X11` in `xf_input.c`
We´d appreciate a pull request for such a thing, as it is low on our priority list (e.g. we´re focusing on getting internals up to date and more robust)

**Comment by myjimmy** [comment]
@akallabeth Thanks for your reply.
> FreeRDP rdpei channel already supports the current RDP standard for pen redirection.

I tried the pen redirection by using wfreerdp.exe, but the pen works as only the mouse and other actions (such as pen pressure) of the pen don't work.
Also, there are no command-line parameters related to the pen redirection.
Please let me know how to use the pen remoting feature in wfreerdp.exe / xfreerdp.

> What is missing is the glue code to `X11` in `xf_input.c`

Sorry, I can't understand this. Please explain this in more detail.

**Comment by akallabeth** [comment]
@myjimmy that means that the `channel` (e.g. the thing sending/receiving the pen related data) already has support, but the `client` (e.g. `xfreerdp`, `wfreerdp`, ...) have not been updated to forward the local events to the remote.

**Comment by digitalsignalperson** [comment]
I started looking at this with https://github.com/ApoorvaJ/EasyTab as a reference, but it might take me awhile if I can wrap my head around it.

**Comment by digitalsignalperson** [comment]
I've had some success with this: working pen & pressure, semi-working eraser, or semi-semi working eraser and pen-hover events, but it's not ready for a PR. Details below

# How X11 works with pens

Pen stuff is very similar to multitouch, except while X11 gives explicit events for XI_TouchBegin, XI_TouchUpdate, and XI_TouchEnd, as far as I could see for pen stuff you only get XI_ButtonPress, XI_Motion, and XI_ButtonRelease, and it's up to you to correctly interpret what's going on. Furthermore, a challenge is that pen not only has a active state, but a hovering state. So a complete picture would be PenHoverBegin, PenHoverUpdate, PenHoverEnd, PenDrawBegin, PenDrawUpdate, PenDrawEnd, all while complying with [[MS-RDPEI] 3.1.1.1 Touch Contact State Transitions](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpei/797930c0-d5ca-4da5-a801-97813d3b750e)

![](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpei/ms-rdpei_files/image002.png)

Some helpful tools to see what all the states are before starting coding:
- `libinput debug-events`
- `xinput test-xi2 --root`
 
Possibly useful observations from xinput:
- I see `EVENT type 1 (DeviceChanged)` every time between switching to a different input device (mouse, touch, pen, keyboard)

Example switching to pen:
```
EVENT type 1 (DeviceChanged)
    device: 2 (22)
    reason: SlaveSwitch
	Reporting 6 classes:
		Class originated from: 22. Type: XIButtonClass
		Buttons supported: 7
		Button labels: None None None None None None None
		Button state:
		Class originated from: 22. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Abs X
		  Range: 0.000000 - 16777215.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000
		Class originated from: 22. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Abs Y
		  Range: 0.000000 - 16777215.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000
		Class originated from: 22. Type: XIValuatorClass
		Detail for Valuator 2:
		  Label: Abs Pressure
		  Range: 0.000000 - 2047.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000
		Class originated from: 22. Type: XIValuatorClass
		Detail for Valuator 3:
		  Label: Abs Tilt X
		  Range: -64.000000 - 64.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000
		Class originated from: 22. Type: XIValuatorClass
		Detail for Valuator 4:
		  Label: Abs Tilt Y
		  Range: -64.000000 - 64.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000
```

- Initially only a "ipts 045E:001F Pen Pen (0)" was seen on my Surface Pro 5 (surface linux kernel with ipts), but on first time using the eraser I got a HierarchyChanged event where a "ipts ... Pen Eraser ..."  device was added.
    - **should probably detect HierarchyChanged and re-initialize xf_input_init when that happens**

Additional info and notes:
- Browsing various X11 touch/stylus implementations, they all seem to rely on the fact that pressure is always the 3rd valuator value. In my implementation, I used this index, but we can also do a string comparison because the valuator name should have "Pressure" in it.
- max_pressure must be determined from querying the input devices, so this should also be refreshed whenever devices are added/removed
- rdpei has MAX_PEN_CONTACTS = 4 so simultaneous pen contacts are apparently possible, but directly on my Surface Pro 5 in windows 10 this does not seem to work with the 2 pens I have. It may need special devices like Surface Hub or similar.

# Implementation notes

## master - doesn't work
Initially I started working off master, but when things weren't working I realized that when I built master without any changes multitouch wasn't working (Test: RDP into Windows 10 machine, open MS Paint, and try using 2 fingers with a brush  (yes MS Paint is multitouch!)). Here's where I left off with that branch anyway:
https://github.com/FreeRDP/FreeRDP/compare/master...digitalsignalperson:FreeRDP:master-pendev


## 2.10.0 - working pen+pressure, and semi-working eraser
So I went back to 2.10.0 where I could see multitouch working from the archlinux package. I refactored my patch and after a few more adjustments I have pen with pressure working, and sort-of working eraser:
https://github.com/digitalsignalperson/FreeRDP/commit/b94da5b6a66b9ab844fe50a69c0f86fb52e74556
https://github.com/FreeRDP/FreeRDP/compare/2.10.0...digitalsignalperson:FreeRDP:2.10.0_archlinux-pendev?expand=1

My testing with an eraser is a stylus from a Surface Pro 5. And I'm testing it on both the SP5 and an ASUS X16 Flow.
The SP5 with surface linux kernel uses ipts and the xinput devices have "Pen Pen" or "Pen Eraser" for which end of the pen you are using. For the ASUS the devices have "Stylus Pen" and "Stylus Eraser".

The MS-RDPEI docs are kind of opaque on how to use an eraser, but I figured it must be the penFlags PEN_FLAG_INVERTED, and that proved correct. 

A simple way to test the eraser is in Powerpoint, which while isn't multitouch, has drawing with pens, pressure, and eraser functions.

So if I draw something with the pen, then flip it around to use the eraser, here's what happens:
- first time touch pen to screen with eraser side then move it: it draws another line
- lift pen
- second time touch pen to screen with eraser side then move it: it is now in eraser mode and will erase lines
- continue using the eraser keeps working
- flip pen around to the drawing tip side, touch screen with tip and move it: still in eraser mode
- lift pen
- second time touch pen tip and move it: back to drawing mode

So it takes two touches for state change to eraser mode and vice-versa to go back to pen mode.

One suspect area is using `rdpei->PenEnd(rdpei, pen_index, 0, x, y);` because ending the pen movement would hit `ERROR_OUTOFMEMORY` from `rdpei_write_pen_frame` at `rdpei_write_4byte_unsigned(s, contact->penFlags)`.  But not giving penFlags or pressure for the PenEnd seems to work. But I think switching to eraser mode might require pen hovering so I tried that angle next.

## POC of pen hover for eraser
Normally when you hold the stylus hovering above the screen, you see a dot or paint brush if using the pen tip, and an eraser icon if using the eraser side. That is the normal precursor to actually using the eraser. Entirely skipping the hovering step might not trigger the correct states to switch to the eraser in whatever program we are using.

So here's my quick hack to see if using hover would do the trick
https://github.com/FreeRDP/FreeRDP/commit/9f71d0cb99d37cca9068b0c58f067e096777ef58
https://github.com/FreeRDP/FreeRDP/compare/2.10.0...digitalsignalperson:FreeRDP:2.10.0_archlinux-pendev_hover

and yes I think that does do the trick, but this hack isn't super thought out and input stops working after a couple touches.

**Comment by digitalsignalperson** [comment]
Implemented for X11, but could leave the issue open for wayland. Maybe I will try that later.

**Comment by akallabeth** [comment]
@digitalsignalperson wayland client is dead, better look at the SDL client ;)

**Comment by digitalsignalperson** [comment]
TODO
- case insensitive device name matching per @ichaoX note here https://github.com/FreeRDP/FreeRDP/pull/9080#issuecomment-1703850358
- Check the status of stuff that broke in refactor: https://github.com/FreeRDP/FreeRDP/pull/9086#issuecomment-1603171372

**Comment by michaelcadilhac** [comment]
Is this also supposed to work with `freerdp-shadow-cli3`?  My use case is: Cintiq Tablet running Windows 10, connecting to a `freerdp-shadow-cli3` server started on Arch Linux, running `xournalpp` .  This is not working out of the box using the latest freerdp package on Arch; happy to try `master` if that's the matter.

**Comment by akallabeth** [comment]
> Is this also supposed to work with `freerdp-shadow-cli3`? My use case is: Cintiq Tablet running Windows 10, connecting to a `freerdp-shadow-cli3` server started on Arch Linux, running `xournalpp` . This is not working out of the box using the latest freerdp package on Arch; happy to try `master` if that's the matter.

no.
this issue is for client side implementation (`xfreerdp`)

**Comment by michaelcadilhac** [comment]
> no. this issue is for client side implementation (`xfreerdp`)

Appreciated.  Would it make sense to open another feature request for this?

**Comment by akallabeth** [comment]
@michaelcadilhac well, yes and no.
yes as in there is an issue you can reference, no as in a pull request has more success of getting this upstream ;)
