### ISSUE TITLE
Floatbar frozen randomly in my session

### ISSUE THREAD

**Issue by Eu-CL** [FreeRDP/FreeRDP#7297]
When launching a remote session (to windows server 2019), sometimes the connection suddenly freezes, and i cant do anything, only restart the computer. It can happen at 10 minutes or at 8 hours, it is very randomly. I have done tests and my  conclusion that without the Floatbar  this circumstance does not happen. At no time does he get out of the session, he just freezes (he can only move the mouse). I have managed to reproduce this problem by quickly moving the floatbar in my session, which also gives quite a few graphical glitches and slowdowns. Tried changing display options.

As data, if I add the parameter ```/smart-sizing``` something happens related to the previous case but without getting completely blocked.

#

**Aplication details**

_FreeRDP Version_: 3.2; 2.0; 2.2; 

_Command line_: ```xfreerdp /f /cert-ignore -decorations -themes +fonts /drive:media,/media +auto-reconnect /floatbar:sticky:off,default:hidden,show:fullscreen  /auto-reconnect-max-retries:5 /sound /microphone /video /gfx:AVC444```

#

**Enviroments**

The tests have been done on Debian 10, Ubuntu 20.4 and other linux distributions, giving the same problem in all.

 #

**Logs**

```
[08:59:44:754] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_sw_end_paint
[08:59:44:754] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_sw_end_paint
[08:59:44:756] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_sw_end_paint
[08:59:44:757] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_sw_end_paint
[08:59:44:757] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_sw_end_paint
[08:59:44:763] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_sw_end_paint
[08:59:44:099] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:44:099] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:45:860] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:45:940] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:46:643] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:46:644] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:47:554] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:49:463] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:49:819] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:49:820] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:49:890] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:49:982] [27696:27697] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_process_x_events
[08:59:50:936] [27696:27731] [ERROR][com.freerdp.codec.progressive] - Invalid total tile count, maximum 558
[08:59:50:936] [27696:27731] [ERROR][com.freerdp.gdi] - progressive_decompress_ex failure: -1027
[08:59:50:936] [27696:27731] [ERROR][com.freerdp.channels.rdpgfx.client] - context->SurfaceCommand failed with error 1359
[08:59:50:936] [27696:27731] [ERROR][com.freerdp.channels.rdpgfx.client] - rdpgfx_recv_wire_to_surface_2_pdu failed with error 1359!
[08:59:50:936] [27696:27731] [ERROR][com.freerdp.channels.rdpgfx.client] - Error while processing GFX cmdId: RDPGFX_CMDID_WIRETOSURFACE_2 (0x0002)
[08:59:50:936] [27696:27731] [ERROR][com.freerdp.channels.rdpgfx.client] - rdpgfx_recv_pdu failed with error 1359!
[08:59:50:944] [27696:27731] [ERROR][com.freerdp.channels.drdynvc.client] - ChannelId 7 not found!

```
**Images**

![wefeww](https://user-images.githubusercontent.com/78023786/133439280-45818047-0e85-4366-9406-60359abd7183.png)

![wefw](https://user-images.githubusercontent.com/78023786/133439287-9542bff4-15da-4f32-b2b4-4119e2065a81.png)

**Comment by akallabeth** [comment]
@Eu-CL sorry for the delay.
this is basic `X11` window drawing, mostly influenced by your `Xorg` and graphics drivers. Any information about these?

**Comment by Eu-CL** [comment]
> @Eu-CL sorry for the delay.
> this is basic `X11` window drawing, mostly influenced by your `Xorg` and graphics drivers. Any information about these?

Hi, this is my system information:

00:02.0 VGA compatible controller: Intel Corporation HD Graphics 500 (rev 0b)
    Subsystem: Elitegroup Computer Systems HD Graphics 500
    Kernel driver in use: i915
00:0e.0 Audio device: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster (rev 0b)

**Comment by whitpa** [comment]
FYI our (thinlinx.com's) customers are also encountering this problem, at least as late as FreeRDP 2.4.1, and I expect that it is still an issue in 2.6.0, 2.6.1 and 2.7.0 also.  It's difficult to reliably reproduce, but setting the floatbar to auto-hide and then using the mouse to expose, hide and drag it will generally produce a lock-up pretty quickly.

We think that this is a deadlock in FreeRDP that must somehow be related to desktop composition, because using "-aero" seems to be a reliable workaround.  As far as we are aware, the RDP server version is immaterial (occurs with Windows Server 2016 and Windows 10 at the very least).

Our O/S is Debian 10 (i386, amd64 and armhf, with most customers using armhf) with some relatively minor modifications (principally use of AUFS layering and Reiser4).  Versions are similar to those quoted above:

xserver-xorg-core 2:1.20.4-1+deb10u4
xserver-xorg-input-libinput 0.28.2-2
xserver-xorg-video-amdgpu 18.1.99+git20190207-1
xserver-xorg-video-ati 1:19.0.1-1
xserver-xorg-video-intel 2:2.99.917+git20180925-2
xserver-xorg-video-nouveau 1:1.0.16-1
xserver-xorg-video-radeon 1:19.0.1-1
i965-va-driver-shaders 2.3.0-1
mesa-va-drivers 18.3.6-2+deb10u1
vdpau-va-driver 0.7.4-7
mesa-vdpau-drivers 18.3.6-2+deb10u1

(ARM versions of the O/S lack everything AMD/Intel/nVidia/VA-API/VDPAU-related)

Example buildconfig:

This is FreeRDP version 2.4.1 (2.4.1)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=ON WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -O2 -m64 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 8.3.0
Target architecture: x64

(ARM versions lack WITH_SSE2=ON and WITH_VAAPI=ON and add WITH_NEON=ON, but are otherwise the same)

Example command line:

xfreerdp /client-hostname:n94c69118b1c3 /f /floatbar:sticky:off,default:hidden,show:fullscreen /multimon /dynamic-resolution /bpp:32 /cert:ignore /u:Administrator /d:TEST /from-stdin:force /network:auto /rfx /gfx:AVC420 +clipboard /audio-mode:0 /sound:sys:pulse,quality:high /microphone:sys:pulse /drive:storage,/media /printer /v:192.168.1.98

**Comment by uuksu** [comment]
Can confirm, this same bug is also happening on my machine. Floatbar frozes and it also frozes the whole RDP session. I've found that only solution after that is restarting lightdm process or the whole machine. Killing the xreerdp process does not help as the image of the session is "stuck" on the screen.

My host machine is running Manjaro 21.2.6 with Linux 5.17.9. Target machine is Windows 10.

Log is full of these lines:

> [07:53:18:667] [2255:2256] [WARN][com.freerdp.client.x11] - xf_lock_x11_:	[1] recursive lock from xf_sw_end_paint
> [07:53:18:667] [2255:2256] [WARN][com.freerdp.client.x11] - xf_lock_x11_:	[1] recursive lock from xf_sw_end_paint
> [07:53:18:668] [2255:2256] [WARN][com.freerdp.client.x11] - xf_lock_x11_:	[1] recursive lock from xf_sw_end_paint
> [07:53:18:675] [2255:2256] [WARN][com.freerdp.client.x11] - xf_lock_x11_:	[1] recursive lock from xf_sw_end_paint
> [07:53:18:675] [2255:2256] [WARN][com.freerdp.client.x11] - xf_lock_x11_:	[1] recursive lock from xf_sw_end_paint
> [07:53:18:675] [2255:2256] [WARN][com.freerdp.client.x11] - xf_lock_x11_:	[1] recursive lock from xf_sw_end_paint
> [07:53:18:683] [2255:2256] [WARN][com.freerdp.client.x11] - xf_lock_x11_:	[1] recursive lock from xf_sw_end_paint

Example command line:
`xfreerdp /sec:tls /d:AzureAD /u:<username> /p:<password> /v:<host-ip> /floatbar:sticky:off,show:fullscreen /f /multimon +fonts /sound`

I'm running Xorg (xorg-server 21.1.3-4) with nVidia drivers (linux517-nvidia 510.73.05-1).

**Comment by whitpa** [comment]
BTW, our customers have told us that adding "-aero" is *not* a viable workaround, although it apparently reduces the frequency of the problem.

The problem continues to occur in FreeRDP 2.7.0.

**Comment by uuksu** [comment]
> BTW, our customers have told us that adding "-aero" is _not_ a viable workaround, although it apparently reduces the frequency of the problem.
> 
> The problem continues to occur in FreeRDP 2.7.0.

I can also confirm both of these statements. I was missing my FreeRDP version from my report but I'm on the 2.7.0. I've tried using the "-aero" option but indeed this seems to reduce the frequency but the problem is still happening sometimes.

**Comment by akallabeth** [comment]
Anyway, reviewing the initial problem description again and I did miss the obvious:
1. It was a decoder error (`[08:59:50:936] [27696:27731] [ERROR][com.freerdp.codec.progressive] - Invalid total tile count, maximum 558`)
2. with `+auto-reconnect` that ended in a endless reconnect loop. 

Since the description of @whitpa and @uuksu is different, I think we´re talking about different problems here.

**Comment by uuksu** [comment]
@akallabeth 

> Yes, -areo never was and never will have anything to do with any of this (sorry, it just does nothing with anything newer than windows 7, and with windows 7 it just tells the server we want some other decorations - which is just a bitmap as any other for the client)

Oh well, it was then good ol' placebo. As a old Windows 7 users I should have known better that the Aero is a think of the past.

> Your description of Killing the xfreerdp process does not help as the image of the session is "stuck" on the screen. suggests there is something wrong with your system rather than FreeRDP (killing xfreerdp and it is gone for sure), maybe a bug in the graphics drivers?

That's totally possible, the nVidia Linux drivers are not known to be the most stable thing existed. I'm still thinking that the problem might be in the FreeRDP as no other application behaves this way.

I've killed the xfreerdp process and I know it's gone. This leaves the session screen black, only the floatbar is visible on the top. Floatbar is not usable before or after killing the process so I can't exit the application normally.

> The log messages can be ignored (I´ve just not backported the fix to stable-2.0 yet, fixed with Removed recursive xf_lock_x11 warning #7938

Ok, good to know. Those lines were the ones that lead me to this issue so thougth they might be related.

**Comment by akallabeth** [comment]
@whitpa btw, you are disabling `AVC` support with that command line (`AVC420` was only supported with windows 8.1)

**Comment by whitpa** [comment]
Yes, I doubted that either the debug output or strace output would be of much use.  The log really did stop mid-line once frozen, so it must occur between buffer flushes.

P.S. That's twice in this thread alone that you have admitted that options that the manpage implies do something in fact do nothing.   FreeRDP documentation leaves much to be desired!  Perhaps you need to qualify in the manpage what versions of the RDP protocol each option is applicable to?

**Comment by hardening** [comment]
`That's twice in this thread alone that you have admitted that options that the manpage implies do something in fact do nothing. FreeRDP documentation leaves much to be desired! Perhaps you need to qualify in the manpage what versions of the RDP protocol each option is applicable to?` => we're always opened to PR ;)

**Comment by akallabeth** [comment]
@whitpa no, the options do what they tell, but the client announced stuff will only be used `by the server` if it supports it too (e.g. `AVC420`)

You can not force the server to something it is not willing to use, the final decision of what of the supported options will be used is always up to the server

Best thing to do is just use the defaults (if you are on 2.7.0) or add `/network:auto` to have the most recent stuff enabled.

**Comment by mrweir** [comment]
> ...so a full `strace` might help

Hey @akallabeth , we're having the same issue - interacting with the floatbar will sometimes freeze up xfreerdp, but if we kill the xfreerdp process the system is otherwise unaffected.  We're currently running FreeRDP 2.10.0.

You mentioned a full `strace` might help, I'd be happy to gather anything that would be useful.  I used `strace -f -p 5369 -o xfreerdp_trace.txt` to save the output to a file, but it seemed to be writing endlessly so I stopped it when it got to ~100K lines.

Mostly it's just a lot of this, with the middle block repeating every now and again:
```
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1 <unfinished ...>
5402  <... poll resumed>)               = 0 (Timeout)
5402  getpid()                          = 5369
5402  write(61, "W", 1)                 = 1
5402  write(61, "W", 1)                 = 1
5402  write(61, "W", 1)                 = 1
5402  read(60, "WWW", 10)               = 3
5402  write(62, "\1\0\0\0\0\0\0\0", 8)  = 8
5402  read(60, 0x7f202a7fb93e, 10)      = -1 EAGAIN (Resource temporarily unavailable)
5402  poll([{fd=60, events=POLLIN}, {fd=63, events=POLLIN}, {fd=64, events=POLLIN}], 3, 1500) = 1 ([{fd=64, revents=POLLIN}])
5402  read(64, "\1\0\0\0\0\0\0\0", 8)   = 8
5402  read(60, 0x7f202a7fb93e, 10)      = -1 EAGAIN (Resource temporarily unavailable)
5399  <... poll resumed>)               = 0 (Timeout)
5402  poll([{fd=60, events=POLLIN}, {fd=63, events=POLLIN}, {fd=64, events=POLLIN}], 3, 1500 <unfinished ...>
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
5399  poll([{fd=50, events=POLLIN}, {fd=52, events=POLLIN}, {fd=56, events=POLLOUT}, {fd=57, events=POLLOUT}], 4, 1) = 0 (Timeout)
```

[xfreerdp_trace.txt.zip](https://github.com/FreeRDP/FreeRDP/files/13031612/xfreerdp_trace.txt.zip)

Please let me know if there are any different options you'd need me to use when running `strace`, or I can build xfreerdp with specific flags, etc.

Thanks!

**Comment by whitpa** [comment]
I think that this problem may have been (incidentally/unintentionally) fixed in recent releases, although I'm not sure which one.  Your symptom sounds diffferent to / less severe than the one we had originally.
