### ISSUE TITLE
when i launch wfreerdp.exe

### ISSUE THREAD

**Issue by Lez1S** [FreeRDP/FreeRDP#7556]
it literally just doesnt appear. not even in background processes.

**Comment by akallabeth** [comment]
`wfreerdp.exe` requires command line arguments or an RDP-file as argument.
Due to some limitations of the Windows API the started program detaches from the starting terminal and you can not see the output to `stdout`.
Try `wfreerdp.exe >log.txt 2>&1 ` from a folder you have write permissions to and check what has been written to `log.txt`
