### ISSUE TITLE
HiDPI for wayland system when WM scale factor is set

### ISSUE THREAD

**Issue by meklonets** [FreeRDP/FreeRDP#7608]
For example I use swaywm with 24' monitor, 4k. 
And I have "scale 2" set in my sway config. It is system-wide setting. Everything's smooth and every app gets 4k. 
Besides wlfreerdp. Remote system gets FullHD instead UHD.

**Comment by akallabeth** [comment]
you need to choose:
1. Scale locally (that can be done with `/smart-sizing` argument)
2. Scale remotely (`/scale*` options, require support of remote OS)

**Comment by meklonets** [comment]
> you need to choose:
> 
> 1. Scale locally (that can be done with `/smart-sizing` argument)
> 2. Scale remotely (`/scale*` options, require support of remote OS)

I meant "pixels per inch".  
Two features, you mentioned, change the sizes of interface's elements, making icons (for example) bigger or dynamic, but the resolution (grain) still FullHD.
If I remove the scale factor from Sway settings (all elements are tiny for 24', system-wide), then - yes, freerdp gets UHD, and only set we have is scale 125|140|180 scale. But 180 isn't enough scaling for 24" UHD monitors. But again in this case all other apps on swaywm are tiny.

**Comment by akallabeth** [comment]
@meklonets ok, so your problem is that with the `sway` scale factor the session size is reduced to `FullHD`?
Problem here is (just guessing from how it is done in gnome) that the `scale factor` just scales the application window locally.
`FreeRDP` on the other hand requires you to do this without any local scaling if you want a session matching your local resolution.

So, short answer: Can´t work that way, you always need `FreeRDP` without scale factor if you want the proper resolution for the RDP session.
(the `/scale*` options match what is supported by windows, so nothing we can do client wise)

**Comment by meklonets** [comment]
@akallabeth Got it. Thank you.

**Comment by microcai** [comment]
with scale=2, wlfreerdp did not tell compositor that it supports hidpi, so wlfreerdp window is  scaled by compositor, thus the remote desktop is double scaled if you specify /scale* options.
