### ISSUE TITLE
codesign failed - the main executable or Info.plist must be a regular file

### ISSUE THREAD

**Issue by woodchuckkkk** [FreeRDP/FreeRDP#7828]
**Describe the bug**

We have built FreeRDP for Mac successfully And trying to run codesign on the bundle. Codesign produces an error "the main executable or Info.plist must be a regular file (no symlinks, etc.)."

**Screenshots**
<img width="2012" alt="3f9401febdb8c27daf86704a5c05be6b" src="https://user-images.githubusercontent.com/5895217/165130409-f66231da-bf59-43f5-865f-3619e44f9514.png">

**Environment (please complete the following information):**

 - OS: Mac
 - Version/Distribution: 12.3 (21E230)

**Comment by akallabeth** [comment]
well, yes?
looks like you did something wrong, but can´t tell what (the interesting part of `how did you build` is missing here ;))

FYI: A build fresh from master 2ad18aa8093507c1f7f4aedade8485fe125a8775
 
```
 ls -shla client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP 
144 -rwxr-xr-x  1 dev  staff    70K 26 Apr 07:26 client/Mac/cli/MacFreeRDP.app/Contents/MacOS/MacFreeRDP

ls -shla client/Mac/cli/MacFreeRDP.app/Contents/Info.plist 
8 -rw-r--r--  1 dev  staff   1,3K 26 Apr 07:24 client/Mac/cli/MacFreeRDP.app/Contents/Info.plist
```

**Comment by woodchuckkkk** [comment]
well i tried to build master but it didn't solve the problem. here is the steps:
1. git clone https://github.com/FreeRDP/FreeRDP.git
2. export PKG_CONFIG_PATH=$(brew --prefix)/opt/openssl/lib/pkgconfig
3. cmake -G Xcode .
4. find the Xcode project -  **MacFreeRDP.xcodeproj** and build **MacFreeRDP** target
5. codesign the output
codesign --deep -fs  "Developer ID Application: xxxxxx (xxxxxxx) Network Co., Ltd. (xxxxxxxxxx)" --options=runtime client/Mac/cli/Debug/MacFreeRDP.app
6. codesign shows error: 
`client/Mac/cli/Debug/MacFreeRDP.app: replacing existing signature
client/Mac/cli/Debug/MacFreeRDP.app: the main executable or Info.plist must be a regular file (no symlinks, etc.)
In subcomponent: client/Mac/cli/Debug/MacFreeRDP.app/Contents/Frameworks/MacFreeRDP.framework
`

**Comment by akallabeth** [comment]
ok, so you´re using `CMake -GXCode`, have not done that in a long time ;)
we usually build with:
```
cmake -B<builddir> -S<srcdir>
cmake --build <builddir> --target <yourtarget>
```

but that should not be the issue.
1. Mac client has not seen many updates in recent years, and code signing requires some configuration. (Pull requests to improve the situation are very welcome ;))
2. did you check the build `.app` does have all required libraries set up correctly?

Since you seem to use `brew` as dependencies I doubt the `.app` contains everything required (our build process only provides the most basic setup, the rest is up to you)

but back to the code signing error, check if there are symlinks somewhere in the generated `.app` and replace them with actual copies of the files required
