### ISSUE TITLE
xfreerdp - TS Session Broker - NUM Lock state and led not synced

### ISSUE THREAD

**Issue by bmiklautz** [FreeRDP/FreeRDP#794]
If NUM lock is on when connecting to session broker and the client gets redirected to another server Num lock led stays on but NUM lock state is off. When pressing NUM lock again led is off but state is on.

**Comment by trentasis** [comment]
hi  @BattousaiDeDo 

Have you solved?
Tried with same environment you have described with thinstation 5.4 and latest freerdp and session broker... 

Can you give details?

thanks

**Comment by BattousaiDeDo** [comment]
Honestly I have no idea. I didnt have to look at it for over 3 years now. And i dont work in the company anymore. Although, I know they still use the same build since when i left. 
Then again I use freerdp on raspberry pi at the moment and didn't encounter this problem. Seems like the problem was fixed in the meantime.

**Comment by trentasis** [comment]
I have tested with latest version and with some situations error is reproduced, I don't know how to solve...
If we restart freerdp then numlock is resync and working during some time...
