### ISSUE TITLE
Crash with kwin (KDE plasma)

### ISSUE THREAD

**Issue by grosjo** [FreeRDP/FreeRDP#8114]
**Bug description**
Starting a RDP connection under latest Kwin (plasma kde) reaches an error in KDE:

août 07 04:42:30 gjlaptop kwin_x11[604]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2786, resource id: 16784298, major code: 20 (GetProperty), minor code: 0
août 07 04:42:30 gjlaptop kwin_x11[604]: kwin_core: XCB error: 152 (BadDamage), sequence: 2883, resource id: 16784320, major code: 143 (DAMAGE), minor code: 3 (Subtract)

**To Reproduce**
-  Ensure latest KDE Plasma (version 5.25.4)
-  Launch any RDP connection
- Refer to journal for error

**Expected behavior**
No crach

**Screenshots**
Log extract
août 07 04:42:30 gjlaptop kwin_x11[604]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2786, resource id: 16784298, major code: 20 (GetProperty), minor code: 0
août 07 04:42:30 gjlaptop kwin_x11[604]: kwin_core: XCB error: 152 (BadDamage), sequence: 2883, resource id: 16784320, major code: 143 (DAMAGE), minor code: 3 (Subtract)

**Application details**
* FreeRDP version (`xfreerdp /version`) : 2.8.0
* Command line used : Using Remmina
* OS version connecting to (server side) : Windows Server 2008 R2 Standard
* OS version (client side) : Archlinux

**Environment (please complete the following information):**
 - OS: Archlinux
 - Version/Distribution: Latest rolling
 - Architecture: [amd64, arm]: amd64

**Comment by grosjo** [comment]
If I connect to a Win7 server, I get the following error:
août 07 05:49:30 gjlaptop kwin_x11[604]: kwin_core: XCB error: 152 (BadDamage), sequence: 63427, resource id: 16916565, major code: 143 (DAMAGE), minor code: 3 (Subtract)

**Comment by mfleisz** [comment]
@grosjo the log messages indicate a problem with the UI (Remmina) rather than the library (FreeRDP) - if these log messages are the real source of the issue that is.

**Comment by grosjo** [comment]
@mfleisz Not sure, as the bug does not appear with other version of windows on server side

**Comment by akallabeth** [comment]
@grosjo this looks like an invalid drawing command is issued by remmina.
can you reproduce this with `xfreerdp` or `wlfreerdp`?

**Comment by dmitry-azaraev** [comment]
I have similar issue, but it probably bit different, but generally looks same:

Arch Linux:
1) labwc/wlroots as backend: wlfreerdp (2.11.4) - generally works fine.
2) kwin - exactly same
3) I'm using 1.25x output scale (QHD monitor): and if host output is 1.0 (e.g. not scaled) - then `/scale:100 /scale-desktop:125` - works nice and pixel perfectly. But once I'm using 1.25x scale on host - whole geometry looks correct, but rdp's image bit crispy and blurred. Somehow they are did not agreed on dimensions. Again, same on wlroots (which had some minor issues with fractional scales), and on kwin too.
4) Sometimes it just crash, possibly on resizes.

I'm tried some latest wlfreerdp 3.x version recently (compiled myself), and this leads to (when using 1.25x scale): 
1) scales are not somehow respected at all, or it is hard to understand
2) damage regions are looks like incorrect, because RDP's updates sometimes leave some lines/pixels from closed menu/app/etc.
3) attempt to resize window (i'm using dynamic resolution) - definitely lead to crash

I'm probably can try handle/fix this myself, but would like to hear and pointers, if they are exist.

Thanks!

**Comment by akallabeth** [comment]
looks like resource exhaustion.
most likely already fixed for `xfreerdp` (@dmitry-azaraev sorry, your `wlfreerdp` issue is something else, not related to this)
