### ISSUE TITLE
Connecting to Windows 10\Windows Server 2019 Session 0 through FreeRDP

### ISSUE THREAD

**Issue by Ranga1987** [FreeRDP/FreeRDP#8222]
We are looking for help to connect Windows Session 0 through FreeRDP from C#.NET
Is FreeRDP feasible to connect to Windows Session 0?

**Comment by akallabeth** [comment]
@Ranga1987 well, as long as you speak `RDP` it should work. (`Session 0` is a server side thing - only relevant stuff is what are the authentication requirements)
That is, I assume you want to use `FreeRDP` as a client, correct?

**Comment by mfleisz** [comment]
@Ranga1987 since Windows 7/Server 2008 R2, session isolation was introduced which means session 0 is no more the (formerly known) "console session" but now hosts all services running on the system.

Further more it has no access to the video/display device, limited network access and there is no way you can authenticate to that session as it runs using the built-in SYSTEM account (and there is no way you have the password for that).

**Comment by Ranga1987** [comment]
@akallabeth, @mfleisz , yes Session 0 is no more interactive in latest Windows Versions, but here we are looking to access Session 0 through FreeRDP to control the Services (pass messages to services to run on demand).

**Comment by mfleisz** [comment]
@Ranga1987 you won't be able to access session 0 through RDP (due to the aforementioned reasons). If you want to communicate with services in session 0 you will have to use some sort of IPC (named pipes, sockets, RPC, ... to name a few).

**Comment by Ranga1987** [comment]
@akallabeth, @mfleisz , thank you for your prompt response. Please provide us the clarification on below queries
Is it possible to create non-interactive user session through FreeRDP?
If yes, can we open non-interactive user session using FreeRDP in C# application (windows service)?
