### ISSUE TITLE
Mouse events arrive before peer activation

### ISSUE THREAD

**Issue by ManMower** [FreeRDP/FreeRDP#8473]
In certain situations, FreeRDP can call the MouseEvent callback before the Activate callback.

For me the reproducer case is to run the windows mstsc client, set it to open in fullscreen, and make sure the launcher window is on the same monitor that the RDP window will be on.

My server is weston's RDP backend, which crashes in this case because the input routing isn't safely set up until the Activate callback.

**Comment by pnowack** [comment]
> In certain situations, FreeRDP can call the MouseEvent callback before the Activate callback.

@ManMower FYI, this is allowed and expected behaviour according to the spec. Quoting:

> Once the client has sent the Confirm Active PDU, it can start sending mouse and keyboard input to
the server, and upon receipt of the Font List PDU the server can start sending graphics output to
the client.

The `Activate` callback is called, when the (re)connection sequence is finished (because during that sequence no other core PDUs are afaik allowed to be sent by the server. The client side is however allowed to send input PDUs just after the Confirm Active PDU was sent by the client, which is not the last PDU in that (re)connection sequence.
