### ISSUE TITLE
[NTOWFv1A,NTOWFv2A,NTOWFv2FromHashA] created invalid hash for non ASCII characters

### ISSUE THREAD

**Issue by pnowack** [FreeRDP/FreeRDP#8599]
Affected version: 2.9.0 (also happens with earlier versions)

When using an FreeRDP based server with NLA (which uses NTLM on (at least the) stable-2.0 branch), then passwords must not contain characters with their integer value being > 127, because otherwise the authentication fails.
This is reproducible regardless of the client, e.g. reproducible with xfreerdp (regardless of whether from stable-2.0 or maser branch) and mstsc.

Test case 1: Use the following credentials with NTLM with a FreeRDP-based server (could be g-r-d, could also be the shadow server here inside FreeRDP): Username: `TEST`, Password: `1234` (no chars with values > 127 here)
Observation: The authentication succeeds, when the server is configured with a SAM file with these credentials.

Test case 2: Username: `TEST`, Password: `1234ä` (has char with value > 127 here)
Observation: The authentication never succeeds.

The following is logged in case 2:

```
[ERROR][com.winpr.sspi.NTLM] - Message Integrity Check (MIC) verification failed! 
[WARN][com.winpr.sspi] - CompleteAuthToken status SEC_E_MESSAGE_ALTERED [0x8009030F]
[WARN][com.freerdp.core.nla] - CompleteAuthToken status SEC_E_MESSAGE_ALTERED [0x8009030F]
[ERROR][com.freerdp.core.transport] - client authentication failure
[ERROR][com.freerdp.core.peer] - peer_recv_callback: CONNECTION_STATE_INITIAL - rdp_server_accept_nego() fail
[ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1
```

This issue was also mentioned a few times in the FreeRDP Matrix channel in the past. Creating this issue here, so it won't get lost.

**Comment by akallabeth** [comment]
@pnowack can not reproduce (neither with `master` nor `stable-2.0`).
Here is what I did (with `Xephyr` as test X-server):
1. `winpr-hash -u test  -p 1234ä -f sam -v 1 >>sam.txt`
2. `Xephyr :23`
3. `DISPLAY=:23 xterm`
4. `DISPLAY=:23 metacity`
5. `DISPLAY=:23 freerdp-shadow-cli /sam-file:sam.txt  /port:3333`
6. `xfreerdp /v:localhost:3333 /u:test /p:1234ä`

that works quite fine. Did you, by chance, use `winpr-hash -u test  -p 1234ä -f sam -v 2` to create the hash? That produces the exact error message you describe (but that is caused by using the wrong hash type for the `SAM` file)

**Comment by pnowack** [comment]
> Did you, by chance, use winpr-hash -u test  -p 1234ä -f sam -v 2 to create the hash?

No, I create v1 hashes here. Basically the handling in g-r-d is https://gitlab.gnome.org/GNOME/gnome-remote-desktop/-/blob/master/src/grd-rdp-sam.c#L61 (the allocated memory is zero initialized).

That matches with the output of `winpr-hash -u TEST -p 1234ä -f sam`, i.e. `TEST:::c15707b1dd86f71f048c8eda7d1cbe92:::`

**Comment by akallabeth** [comment]
Fixed with #8604

**Comment by akallabeth** [comment]
so, to summarize the bug:
the functions `NTOWFv1A`, `NTOWFv2A` and `NTOWFv2FromHashA` assumed that the `WCHAR` character count matched the `UTF8` character count and passed on strings with wrong value. The calculated hash therefore did not only contain the password, but depending on multi byte characters, some data after the end of the password (due to using `calloc` the data was always `\0` initialized and so the hash was always the same wrong value)

**Comment by pnowack** [comment]
> Fixed with https://github.com/FreeRDP/FreeRDP/pull/8604

Yup. Closing.
