### ISSUE TITLE
can't access to local resources

### ISSUE THREAD

**Issue by kerimdk** [FreeRDP/FreeRDP#8661]
hello, i'm trying to share a local input device from ubuntu pc to use it on remote pc through FreeRDP, i used thincast but the microphone is not running on client side.
i tried using remmina too but same (can't access local resources) 
any idea would be appreciated..

**Comment by akallabeth** [comment]
@kerimdk ok, please try again, I don´t get what you´re trying to tell.
It might be helpful if you also add a description of `what exactly` you have tried already.

**Comment by kerimdk** [comment]
I have tried to connect to a windows pc remotely from my Ubuntu pc using both Remmina and Thincast.
- On Remmina, I was unable to access any local resources such as (webcam-microphone) from my ubuntu pc on the remote PC side.
- On Thincast, I was only able to access the webcam, but the microphone wasn't redirected. To resolve this issue, I added the line 'redirect-microphone:i:1' to the .rdp connection file. This allowed the remote  PC to see the microphone, but that was not enough to make it running correctly on the remote PC.

**Comment by akallabeth** [comment]
@kerimdk ok, so:
1. `Remmina ` and `xfreerdp` only support `usb` redirection, so your success with webcams depends on luck.
   * If you use `usb` redirection the whole USB device is redirected, so if your microphone is on that device it will not work.
   * The `usb` redirection only redirects one function of the `usb` device and windows filters some device classes (e.g. `human input device`, `mass storage`, `audio` devices and others) so your microphone will not work if it is on the same `usb` device
4.  As for `thincast client` could you please be a bit more specific with `not enough to make it running correctly`? Hard to help if we do not know what exactly your problem is. (note: Both `Remmina` and `Thincast Client` have options to enable microphone redirection from the UI, take a look ;) `Remmina` in `advanced tab/Redirect local microphone` and `Thincast Client` in `Local Resources Tab` )

**Comment by kerimdk** [comment]
Thank you very much for your explanation. I got it very well now. So, it's not possible to use both the webcam and microphone on a common USB.
Yes, I know the options to enable microphone redirection from the user interface in Remmina and Thincast Client and they're awesome! but my problem is in running two different devices on a common USB, Could a USB hub solve the issue? Sorry if the question seems illogical. I have only three USB ports, and I am using them for the keyboard and the mouse, the remaining one is for either the webcam or the microphone.

**Comment by akallabeth** [comment]
@kerimdk yes, the problem with not having both on the same USB device is valid for `xfreerdp`, what was your issue with `Thincast Client`? (it uses [\[MS-RDPECAM\]](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpecam/92af6790-b79c-4813-9c07-7c545bed0242) redirection which is not affected by these limitations

**Comment by kerimdk** [comment]
the issue is the Thincast Client is not available on armbian ubuntu22 system, i'm using orange thin client device, i tried the Thincast Client on my PC first but didn't found it on my thin client device then

**Comment by kerimdk** [comment]
when i run `$ flatpak install flathub com.thincast.client`
the output is
```
Looking for matches…
error: Nothing matches com.thincast.client in remote flathub
```

**Comment by akallabeth** [comment]
@kerimdk then your config is broken, see https://flathub.org/apps/details/com.thincast.client

**Comment by kerimdk** [comment]
Please help me find the Thincast Client on Armbian. I think I've tried everything in https://flathub.org/apps/details/com.thincast.client 
![Screenshot from 2023-02-03 15-41-42](https://user-images.githubusercontent.com/60518370/216608946-b25c6666-52ec-4c7b-99fd-d3fa531e493b.png)

**Comment by akallabeth** [comment]
@kerimdk there is no build for 32bit arm, only `aarch64` . Install the 64bit os, then you have it.
