### ISSUE TITLE
How FreeRDP can improve audio play back performance

### ISSUE THREAD

**Issue by zhengguimin** [FreeRDP/FreeRDP#8814]
**Describe the bug**
Our project needs to improve audio playback performance. We can see in the log that the server is playing a frame of PCM data stream at an interval of 50 ms.
The log is as follows:
**[08:51:33:961] [7065:7098] [DEBUG][com.freerdp.channels.rdpsnd.client] - [dynamic] Wave2PDU: cBlockNo: 37 wFormatNo: 0 [WAVE_FORMAT_PCM] , align=4
[08:51:33:961] [7065:7098] [DEBUG][com.freerdp.channels.rdpsnd.client] - [dynamic] Wave: cBlockNo: 37 wTimeStamp: 58851, size: 8820
[08:51:33:961] [7065:7098] [DEBUG][com.freerdp.channels.rdpsnd.client] - WAVE_FORMAT_PCM:        wFormatTag: 0x0001 nChannels: 2 nSamplesPerSec: 44100 nAvgBytesPerSec: 176400 nBlockAlign: 4 wBitsPerSample: 16 cbSize: 0**

As far as we know, the formula for calculating the amount of sound data is:
The amount of data(bytes/second) = (sampling frequency* number of sampling bits * number of channels) / 8，bring the information mentioned in the log into this formula,  The amount of data(bytes/second) = (44100*16*2)/8*(50/1000) = 8820。

We also refer to the function rdpsnd_server_select_format in channels/rdpsnd/server/rdpsnd_main.c
        **if (context->latency <= 0)
                context->latency = 50;

        context->priv->out_frames = context->src_format->nSamplesPerSec * context->latency / 1000;**
From here we can know that the server can set the audio performance according to the latency attribute in FreeRDP, but how to set this attribute in the windows server?

**Application details**

FreeRDP version
master
Command line used
xfreerdp /f /u: /p:
OS version connecting to (server side)
Windows server 2022

OS: Linux
Version/Distribution: Rockchip RK3568
Architecture: arm64

**Comment by akallabeth** [comment]
@zhengguimin first, please define `performance`. (the term tends to  mean something differen for each person, so some clarity might ease helping out)
from your formulas I suspect you want to minimize latency?

the whole audio pipeline is a self regulating control loop where the server tries to guess the latency by the data (ACK) the client sends back so that it can buffer samples according to the estimated delay (but not too much  so you don´t have samples played minutes after you stop the stream)
it also regulates the packet frequency according to that.

**Comment by akallabeth** [comment]
no, that is a (combined) property of the server side encoder, network and client decoder
