### ISSUE TITLE
xfreerdp : local client h264 gpu decoding

### ISSUE THREAD

**Issue by benth42** [FreeRDP/FreeRDP#9122]
Hello,

I'm currently testing rdp for remote desktop for light duty desktop.

I have setup some VM with nvidia vGPU A2-1Q, xrdp and xorgxrdp compiled with hardware h264 and nvenc acceleration. 
When I'm connect with xfreerdp client or with microsoft rdp client, i see the usage of the nvidia card by xorgxrdp (nvidia-smi report it). Xorg vgpu Acceleration is ok : glxinfo, firefox or chrome webgl and nvidia-smi report it.

But I didn't manage to have the local xfreerdp client using my GPU on my computer where I connect. 
With a windows 10 workstation, nvidia-smi reports the mstsc process using the video cards.

Can xfreerdp use the GPU for decoding ? I try many compilation options whithout success for now ... 

For exemple (with git  branch master or the 2.10.0) : 
cmake -DWITH_OPENH264=ON -DWITH_KRB5=OFF -DCMAKE_BUILD_TYPE=Release .

cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON -DWITH_FFMPEG=ON -DWITH_OPENH264=OFF -DWITH_SWSCALE=ON -DWITH_CAIRO=ON -DWITH_GFX_H264=ON -DWITH_KRB5=OFF -DCMAKE_BUILD_TYPE=Release .

I have installed cuda-toolkit-12 from nvidia, driver are 525.116.04. I have recompiled openh264 but not ffmpeg.

Thank you in advance.

**Comment by akallabeth** [comment]
well, that depends on a lot of things:
1. you need to have a session utilizing `AVC444` mode (both, client and server! if only the client announces the format support it is not guaranteed that the server will use it)
2. you need `FFMPEG` as `H264` decoder as that one has some versions that utilize some hardware backed decoders (and you need to have one of these versions)

so, in case you have this `FFMPEG` the answer is: a little bit, otherwise no.
Why? `RDP` utilizes a non standard stream (2 `H264` streams in `YUV4:2:2` mode recombined to one `YUV4:4:4` image) so the decoded images must be copied back to system memory and the expensive operations are still done by the `CPU`

so, if you have not enough `CPU` you can ensure you utilize hardware accelerated `SSL` (that is actually the thing eating most `CPU` with `FreeRDP` ;)

**Comment by benth42** [comment]
Hello,

Thank you. 

Well not so easy and not so important for performance regarding other aspect.

xrdp reports usage of x264 encoding but without precision about the avc (440 vs 420). I will look deeper here.
`xrdp_encoder_create: starting h264 codec session gfx`

There is this informations too, but I don't know to "decode" them : 
```
xrdp_mm_egfx_caps_advertise:
  version 0x00080004 flags 0x00000001 (index: 0)
  version 0x00080105 flags 0x00000013 (index: 1)
  version 0x000a0002 flags 0x00000002 (index: 2)
  version 0x000a0200 flags 0x00000002 (index: 3)
  version 0x000a0301 flags 0x00000040 (index: 4)
  version 0x000a0400 flags 0x00000042 (index: 5)
  version 0x000a0502 flags 0x00000042 (index: 6)
  version 0x000a0600 flags 0x00000042 (index: 7)
  version 0x000a0601 flags 0x00000042 (index: 8)
  version 0x000a0701 flags 0x000000c2 (index: 9)
  replying version 0x000a0400 flags 0x00000042
xrdp_mm_egfx_caps_advertise: xrdp_egfx_send_capsconfirm error 0 best_index 5
```

**Comment by akallabeth** [comment]
@benth42 it is using `AVC444v2` (see [MS-RDPEGFX](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegfx/da5c75f9-cd99-450c-98c4-014a496942b0) 2.2.1.6 RDPGFX_CAPSET

**Comment by akallabeth** [comment]
@benth42 closing this as it is more of a question than an issue.
