### ISSUE TITLE
2.11.0 escape full screen via ctrl-alt-enter 

### ISSUE THREAD

**Issue by NespaLa** [FreeRDP/FreeRDP#9461]
OpenSUSE Tumbleweed up to date
xfreerdp 2.11.0 starts session in full screen ( based on a ad hoc downloaded rdp generated by a remote Netscaler ).

To escape fullscreen in order to return to the local desktop, ctrl-alt-enter sometimes works, so one can drag the xfreerdp session to the side, or move it to another virtual desktop.

However sometimes the xfreerdp session flashes, and stays full screen. Possibly a part of the window manager crashes or disappears ( borders round applications are gone ). Unclear to me there is a problem inside or outside the xfreerdp process.

I wonder is there is a way to send a signal (7) from command line to the xfreerdp process in order to trigger it to go out full screen mode. This would be more convenient and subtle to killing the process.

**Comment by akallabeth** [comment]
well, the key combo works (since we have that in use since before 2.0) so it is most likely the combination with your window manager?

and for signals / other means consult your window manager of choice, that should allow setting fullscreen/no fullscreen.

and please do not double post, you can just add comments to issues even if they are closed.

also closing as it is not an issue but a question.

**Comment by NespaLa** [comment]
Thank you for the warm welcome @akallabeth !
